// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"engflex-api/internal/modules/conversations/services"

	mock "github.com/stretchr/testify/mock"
)

// NewMockVoiceClient creates a new instance of MockVoiceClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockVoiceClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockVoiceClient {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockVoiceClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockVoiceClient is an autogenerated mock type for the VoiceClient type
type MockVoiceClient struct {
	mock.Mock
}

type MockVoiceClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockVoiceClient) EXPECT() *MockVoiceClient_Expecter {
	return &MockVoiceClient_Expecter{mock: &_m.Mock}
}

// Offer provides a mock function for the type MockVoiceClient
func (_mock *MockVoiceClient) Offer(ctx context.Context, engineSessionID string, method string, body []byte) ([]byte, int, error) {
	ret := _mock.Called(ctx, engineSessionID, method, body)

	if len(ret) == 0 {
		panic("no return value specified for Offer")
	}

	var r0 []byte
	var r1 int
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, []byte) ([]byte, int, error)); ok {
		return returnFunc(ctx, engineSessionID, method, body)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, []byte) []byte); ok {
		r0 = returnFunc(ctx, engineSessionID, method, body)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, []byte) int); ok {
		r1 = returnFunc(ctx, engineSessionID, method, body)
	} else {
		r1 = ret.Get(1).(int)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string, string, []byte) error); ok {
		r2 = returnFunc(ctx, engineSessionID, method, body)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockVoiceClient_Offer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Offer'
type MockVoiceClient_Offer_Call struct {
	*mock.Call
}

// Offer is a helper method to define mock.On call
//   - ctx context.Context
//   - engineSessionID string
//   - method string
//   - body []byte
func (_e *MockVoiceClient_Expecter) Offer(ctx any, engineSessionID any, method any, body any) *MockVoiceClient_Offer_Call {
	return &MockVoiceClient_Offer_Call{Call: _e.mock.On("Offer", ctx, engineSessionID, method, body)}
}

func (_c *MockVoiceClient_Offer_Call) Run(run func(ctx context.Context, engineSessionID string, method string, body []byte)) *MockVoiceClient_Offer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 []byte
		if args[3] != nil {
			arg3 = args[3].([]byte)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockVoiceClient_Offer_Call) Return(bytes []byte, n int, err error) *MockVoiceClient_Offer_Call {
	_c.Call.Return(bytes, n, err)
	return _c
}

func (_c *MockVoiceClient_Offer_Call) RunAndReturn(run func(ctx context.Context, engineSessionID string, method string, body []byte) ([]byte, int, error)) *MockVoiceClient_Offer_Call {
	_c.Call.Return(run)
	return _c
}

// Start provides a mock function for the type MockVoiceClient
func (_mock *MockVoiceClient) Start(ctx context.Context, req services.StartRequest) (*services.StartResponse, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Start")
	}

	var r0 *services.StartResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, services.StartRequest) (*services.StartResponse, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, services.StartRequest) *services.StartResponse); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*services.StartResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, services.StartRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockVoiceClient_Start_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Start'
type MockVoiceClient_Start_Call struct {
	*mock.Call
}

// Start is a helper method to define mock.On call
//   - ctx context.Context
//   - req services.StartRequest
func (_e *MockVoiceClient_Expecter) Start(ctx any, req any) *MockVoiceClient_Start_Call {
	return &MockVoiceClient_Start_Call{Call: _e.mock.On("Start", ctx, req)}
}

func (_c *MockVoiceClient_Start_Call) Run(run func(ctx context.Context, req services.StartRequest)) *MockVoiceClient_Start_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 services.StartRequest
		if args[1] != nil {
			arg1 = args[1].(services.StartRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockVoiceClient_Start_Call) Return(startResponse *services.StartResponse, err error) *MockVoiceClient_Start_Call {
	_c.Call.Return(startResponse, err)
	return _c
}

func (_c *MockVoiceClient_Start_Call) RunAndReturn(run func(ctx context.Context, req services.StartRequest) (*services.StartResponse, error)) *MockVoiceClient_Start_Call {
	_c.Call.Return(run)
	return _c
}
