// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockLLMClient creates a new instance of MockLLMClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLLMClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLLMClient {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockLLMClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockLLMClient is an autogenerated mock type for the LLMClient type
type MockLLMClient struct {
	mock.Mock
}

type MockLLMClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLLMClient) EXPECT() *MockLLMClient_Expecter {
	return &MockLLMClient_Expecter{mock: &_m.Mock}
}

// CompleteStructured provides a mock function for the type MockLLMClient
func (_mock *MockLLMClient) CompleteStructured(ctx context.Context, prompt string, output any, schemaName string, schema map[string]any) error {
	ret := _mock.Called(ctx, prompt, output, schemaName, schema)

	if len(ret) == 0 {
		panic("no return value specified for CompleteStructured")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, any, string, map[string]any) error); ok {
		r0 = returnFunc(ctx, prompt, output, schemaName, schema)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockLLMClient_CompleteStructured_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CompleteStructured'
type MockLLMClient_CompleteStructured_Call struct {
	*mock.Call
}

// CompleteStructured is a helper method to define mock.On call
//   - ctx context.Context
//   - prompt string
//   - output any
//   - schemaName string
//   - schema map[string]any
func (_e *MockLLMClient_Expecter) CompleteStructured(ctx any, prompt any, output any, schemaName any, schema any) *MockLLMClient_CompleteStructured_Call {
	return &MockLLMClient_CompleteStructured_Call{Call: _e.mock.On("CompleteStructured", ctx, prompt, output, schemaName, schema)}
}

func (_c *MockLLMClient_CompleteStructured_Call) Run(run func(ctx context.Context, prompt string, output any, schemaName string, schema map[string]any)) *MockLLMClient_CompleteStructured_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 any
		if args[2] != nil {
			arg2 = args[2].(any)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 map[string]any
		if args[4] != nil {
			arg4 = args[4].(map[string]any)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockLLMClient_CompleteStructured_Call) Return(err error) *MockLLMClient_CompleteStructured_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockLLMClient_CompleteStructured_Call) RunAndReturn(run func(ctx context.Context, prompt string, output any, schemaName string, schema map[string]any) error) *MockLLMClient_CompleteStructured_Call {
	_c.Call.Return(run)
	return _c
}

// CompleteText provides a mock function for the type MockLLMClient
func (_mock *MockLLMClient) CompleteText(ctx context.Context, prompt string) (string, error) {
	ret := _mock.Called(ctx, prompt)

	if len(ret) == 0 {
		panic("no return value specified for CompleteText")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return returnFunc(ctx, prompt)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = returnFunc(ctx, prompt)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, prompt)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockLLMClient_CompleteText_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CompleteText'
type MockLLMClient_CompleteText_Call struct {
	*mock.Call
}

// CompleteText is a helper method to define mock.On call
//   - ctx context.Context
//   - prompt string
func (_e *MockLLMClient_Expecter) CompleteText(ctx any, prompt any) *MockLLMClient_CompleteText_Call {
	return &MockLLMClient_CompleteText_Call{Call: _e.mock.On("CompleteText", ctx, prompt)}
}

func (_c *MockLLMClient_CompleteText_Call) Run(run func(ctx context.Context, prompt string)) *MockLLMClient_CompleteText_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockLLMClient_CompleteText_Call) Return(s string, err error) *MockLLMClient_CompleteText_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockLLMClient_CompleteText_Call) RunAndReturn(run func(ctx context.Context, prompt string) (string, error)) *MockLLMClient_CompleteText_Call {
	_c.Call.Return(run)
	return _c
}
