// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"engflex-api/internal/database/repositories"

	mock "github.com/stretchr/testify/mock"
	"gorm.io/gorm"
)

// NewMockLessonBookmarkRepository creates a new instance of MockLessonBookmarkRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLessonBookmarkRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLessonBookmarkRepository {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockLessonBookmarkRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockLessonBookmarkRepository is an autogenerated mock type for the LessonBookmarkRepository type
type MockLessonBookmarkRepository struct {
	mock.Mock
}

type MockLessonBookmarkRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLessonBookmarkRepository) EXPECT() *MockLessonBookmarkRepository_Expecter {
	return &MockLessonBookmarkRepository_Expecter{mock: &_m.Mock}
}

// WithTx provides a mock function for the type MockLessonBookmarkRepository
func (_mock *MockLessonBookmarkRepository) WithTx(tx *gorm.DB) repositories.LessonBookmarkRepository {
	ret := _mock.Called(tx)

	if len(ret) == 0 {
		panic("no return value specified for WithTx")
	}

	var r0 repositories.LessonBookmarkRepository
	if returnFunc, ok := ret.Get(0).(func(*gorm.DB) repositories.LessonBookmarkRepository); ok {
		r0 = returnFunc(tx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(repositories.LessonBookmarkRepository)
		}
	}
	return r0
}

// MockLessonBookmarkRepository_WithTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WithTx'
type MockLessonBookmarkRepository_WithTx_Call struct {
	*mock.Call
}

// WithTx is a helper method to define mock.On call
//   - tx *gorm.DB
func (_e *MockLessonBookmarkRepository_Expecter) WithTx(tx any) *MockLessonBookmarkRepository_WithTx_Call {
	return &MockLessonBookmarkRepository_WithTx_Call{Call: _e.mock.On("WithTx", tx)}
}

func (_c *MockLessonBookmarkRepository_WithTx_Call) Run(run func(tx *gorm.DB)) *MockLessonBookmarkRepository_WithTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *gorm.DB
		if args[0] != nil {
			arg0 = args[0].(*gorm.DB)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockLessonBookmarkRepository_WithTx_Call) Return(lessonBookmarkRepository repositories.LessonBookmarkRepository) *MockLessonBookmarkRepository_WithTx_Call {
	_c.Call.Return(lessonBookmarkRepository)
	return _c
}

func (_c *MockLessonBookmarkRepository_WithTx_Call) RunAndReturn(run func(tx *gorm.DB) repositories.LessonBookmarkRepository) *MockLessonBookmarkRepository_WithTx_Call {
	_c.Call.Return(run)
	return _c
}
