// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"engflex-api/internal/database/models"
	"engflex-api/internal/database/repositories"

	mock "github.com/stretchr/testify/mock"
	"gorm.io/gorm"
)

// NewMockVideoCategoryRepository creates a new instance of MockVideoCategoryRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockVideoCategoryRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockVideoCategoryRepository {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockVideoCategoryRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockVideoCategoryRepository is an autogenerated mock type for the VideoCategoryRepository type
type MockVideoCategoryRepository struct {
	mock.Mock
}

type MockVideoCategoryRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockVideoCategoryRepository) EXPECT() *MockVideoCategoryRepository_Expecter {
	return &MockVideoCategoryRepository_Expecter{mock: &_m.Mock}
}

// Count provides a mock function for the type MockVideoCategoryRepository
func (_mock *MockVideoCategoryRepository) Count(ctx context.Context) (int64, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Count")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (int64, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) int64); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockVideoCategoryRepository_Count_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Count'
type MockVideoCategoryRepository_Count_Call struct {
	*mock.Call
}

// Count is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockVideoCategoryRepository_Expecter) Count(ctx any) *MockVideoCategoryRepository_Count_Call {
	return &MockVideoCategoryRepository_Count_Call{Call: _e.mock.On("Count", ctx)}
}

func (_c *MockVideoCategoryRepository_Count_Call) Run(run func(ctx context.Context)) *MockVideoCategoryRepository_Count_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockVideoCategoryRepository_Count_Call) Return(n int64, err error) *MockVideoCategoryRepository_Count_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockVideoCategoryRepository_Count_Call) RunAndReturn(run func(ctx context.Context) (int64, error)) *MockVideoCategoryRepository_Count_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function for the type MockVideoCategoryRepository
func (_mock *MockVideoCategoryRepository) Create(ctx context.Context, category *models.VideoCategory) error {
	ret := _mock.Called(ctx, category)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *models.VideoCategory) error); ok {
		r0 = returnFunc(ctx, category)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockVideoCategoryRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockVideoCategoryRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - category *models.VideoCategory
func (_e *MockVideoCategoryRepository_Expecter) Create(ctx any, category any) *MockVideoCategoryRepository_Create_Call {
	return &MockVideoCategoryRepository_Create_Call{Call: _e.mock.On("Create", ctx, category)}
}

func (_c *MockVideoCategoryRepository_Create_Call) Run(run func(ctx context.Context, category *models.VideoCategory)) *MockVideoCategoryRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *models.VideoCategory
		if args[1] != nil {
			arg1 = args[1].(*models.VideoCategory)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockVideoCategoryRepository_Create_Call) Return(err error) *MockVideoCategoryRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockVideoCategoryRepository_Create_Call) RunAndReturn(run func(ctx context.Context, category *models.VideoCategory) error) *MockVideoCategoryRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockVideoCategoryRepository
func (_mock *MockVideoCategoryRepository) Delete(ctx context.Context, id string) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockVideoCategoryRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockVideoCategoryRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockVideoCategoryRepository_Expecter) Delete(ctx any, id any) *MockVideoCategoryRepository_Delete_Call {
	return &MockVideoCategoryRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockVideoCategoryRepository_Delete_Call) Run(run func(ctx context.Context, id string)) *MockVideoCategoryRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockVideoCategoryRepository_Delete_Call) Return(err error) *MockVideoCategoryRepository_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockVideoCategoryRepository_Delete_Call) RunAndReturn(run func(ctx context.Context, id string) error) *MockVideoCategoryRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type MockVideoCategoryRepository
func (_mock *MockVideoCategoryRepository) GetByID(ctx context.Context, id string) (*models.VideoCategory, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *models.VideoCategory
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*models.VideoCategory, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *models.VideoCategory); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.VideoCategory)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockVideoCategoryRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockVideoCategoryRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockVideoCategoryRepository_Expecter) GetByID(ctx any, id any) *MockVideoCategoryRepository_GetByID_Call {
	return &MockVideoCategoryRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockVideoCategoryRepository_GetByID_Call) Run(run func(ctx context.Context, id string)) *MockVideoCategoryRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockVideoCategoryRepository_GetByID_Call) Return(videoCategory *models.VideoCategory, err error) *MockVideoCategoryRepository_GetByID_Call {
	_c.Call.Return(videoCategory, err)
	return _c
}

func (_c *MockVideoCategoryRepository_GetByID_Call) RunAndReturn(run func(ctx context.Context, id string) (*models.VideoCategory, error)) *MockVideoCategoryRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockVideoCategoryRepository
func (_mock *MockVideoCategoryRepository) List(ctx context.Context, limit int, offset int) ([]*models.VideoCategory, error) {
	ret := _mock.Called(ctx, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*models.VideoCategory
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int) ([]*models.VideoCategory, error)); ok {
		return returnFunc(ctx, limit, offset)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int) []*models.VideoCategory); ok {
		r0 = returnFunc(ctx, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.VideoCategory)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, int) error); ok {
		r1 = returnFunc(ctx, limit, offset)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockVideoCategoryRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockVideoCategoryRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - limit int
//   - offset int
func (_e *MockVideoCategoryRepository_Expecter) List(ctx any, limit any, offset any) *MockVideoCategoryRepository_List_Call {
	return &MockVideoCategoryRepository_List_Call{Call: _e.mock.On("List", ctx, limit, offset)}
}

func (_c *MockVideoCategoryRepository_List_Call) Run(run func(ctx context.Context, limit int, offset int)) *MockVideoCategoryRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockVideoCategoryRepository_List_Call) Return(videoCategorys []*models.VideoCategory, err error) *MockVideoCategoryRepository_List_Call {
	_c.Call.Return(videoCategorys, err)
	return _c
}

func (_c *MockVideoCategoryRepository_List_Call) RunAndReturn(run func(ctx context.Context, limit int, offset int) ([]*models.VideoCategory, error)) *MockVideoCategoryRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockVideoCategoryRepository
func (_mock *MockVideoCategoryRepository) Update(ctx context.Context, category *models.VideoCategory) error {
	ret := _mock.Called(ctx, category)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *models.VideoCategory) error); ok {
		r0 = returnFunc(ctx, category)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockVideoCategoryRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockVideoCategoryRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - category *models.VideoCategory
func (_e *MockVideoCategoryRepository_Expecter) Update(ctx any, category any) *MockVideoCategoryRepository_Update_Call {
	return &MockVideoCategoryRepository_Update_Call{Call: _e.mock.On("Update", ctx, category)}
}

func (_c *MockVideoCategoryRepository_Update_Call) Run(run func(ctx context.Context, category *models.VideoCategory)) *MockVideoCategoryRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *models.VideoCategory
		if args[1] != nil {
			arg1 = args[1].(*models.VideoCategory)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockVideoCategoryRepository_Update_Call) Return(err error) *MockVideoCategoryRepository_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockVideoCategoryRepository_Update_Call) RunAndReturn(run func(ctx context.Context, category *models.VideoCategory) error) *MockVideoCategoryRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// WithTx provides a mock function for the type MockVideoCategoryRepository
func (_mock *MockVideoCategoryRepository) WithTx(tx *gorm.DB) repositories.VideoCategoryRepository {
	ret := _mock.Called(tx)

	if len(ret) == 0 {
		panic("no return value specified for WithTx")
	}

	var r0 repositories.VideoCategoryRepository
	if returnFunc, ok := ret.Get(0).(func(*gorm.DB) repositories.VideoCategoryRepository); ok {
		r0 = returnFunc(tx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(repositories.VideoCategoryRepository)
		}
	}
	return r0
}

// MockVideoCategoryRepository_WithTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WithTx'
type MockVideoCategoryRepository_WithTx_Call struct {
	*mock.Call
}

// WithTx is a helper method to define mock.On call
//   - tx *gorm.DB
func (_e *MockVideoCategoryRepository_Expecter) WithTx(tx any) *MockVideoCategoryRepository_WithTx_Call {
	return &MockVideoCategoryRepository_WithTx_Call{Call: _e.mock.On("WithTx", tx)}
}

func (_c *MockVideoCategoryRepository_WithTx_Call) Run(run func(tx *gorm.DB)) *MockVideoCategoryRepository_WithTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *gorm.DB
		if args[0] != nil {
			arg0 = args[0].(*gorm.DB)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockVideoCategoryRepository_WithTx_Call) Return(videoCategoryRepository repositories.VideoCategoryRepository) *MockVideoCategoryRepository_WithTx_Call {
	_c.Call.Return(videoCategoryRepository)
	return _c
}

func (_c *MockVideoCategoryRepository_WithTx_Call) RunAndReturn(run func(tx *gorm.DB) repositories.VideoCategoryRepository) *MockVideoCategoryRepository_WithTx_Call {
	_c.Call.Return(run)
	return _c
}
