// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"engflex-api/internal/database/models"
	"engflex-api/internal/database/repositories"

	mock "github.com/stretchr/testify/mock"
	"gorm.io/gorm"
)

// NewMockVideoExerciseRepository creates a new instance of MockVideoExerciseRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockVideoExerciseRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockVideoExerciseRepository {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockVideoExerciseRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockVideoExerciseRepository is an autogenerated mock type for the VideoExerciseRepository type
type MockVideoExerciseRepository struct {
	mock.Mock
}

type MockVideoExerciseRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockVideoExerciseRepository) EXPECT() *MockVideoExerciseRepository_Expecter {
	return &MockVideoExerciseRepository_Expecter{mock: &_m.Mock}
}

// Count provides a mock function for the type MockVideoExerciseRepository
func (_mock *MockVideoExerciseRepository) Count(ctx context.Context) (int64, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Count")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (int64, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) int64); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockVideoExerciseRepository_Count_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Count'
type MockVideoExerciseRepository_Count_Call struct {
	*mock.Call
}

// Count is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockVideoExerciseRepository_Expecter) Count(ctx any) *MockVideoExerciseRepository_Count_Call {
	return &MockVideoExerciseRepository_Count_Call{Call: _e.mock.On("Count", ctx)}
}

func (_c *MockVideoExerciseRepository_Count_Call) Run(run func(ctx context.Context)) *MockVideoExerciseRepository_Count_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockVideoExerciseRepository_Count_Call) Return(n int64, err error) *MockVideoExerciseRepository_Count_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockVideoExerciseRepository_Count_Call) RunAndReturn(run func(ctx context.Context) (int64, error)) *MockVideoExerciseRepository_Count_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function for the type MockVideoExerciseRepository
func (_mock *MockVideoExerciseRepository) Create(ctx context.Context, lesson *models.VideoExercise) error {
	ret := _mock.Called(ctx, lesson)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *models.VideoExercise) error); ok {
		r0 = returnFunc(ctx, lesson)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockVideoExerciseRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockVideoExerciseRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - lesson *models.VideoExercise
func (_e *MockVideoExerciseRepository_Expecter) Create(ctx any, lesson any) *MockVideoExerciseRepository_Create_Call {
	return &MockVideoExerciseRepository_Create_Call{Call: _e.mock.On("Create", ctx, lesson)}
}

func (_c *MockVideoExerciseRepository_Create_Call) Run(run func(ctx context.Context, lesson *models.VideoExercise)) *MockVideoExerciseRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *models.VideoExercise
		if args[1] != nil {
			arg1 = args[1].(*models.VideoExercise)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockVideoExerciseRepository_Create_Call) Return(err error) *MockVideoExerciseRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockVideoExerciseRepository_Create_Call) RunAndReturn(run func(ctx context.Context, lesson *models.VideoExercise) error) *MockVideoExerciseRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockVideoExerciseRepository
func (_mock *MockVideoExerciseRepository) Delete(ctx context.Context, id string) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockVideoExerciseRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockVideoExerciseRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockVideoExerciseRepository_Expecter) Delete(ctx any, id any) *MockVideoExerciseRepository_Delete_Call {
	return &MockVideoExerciseRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockVideoExerciseRepository_Delete_Call) Run(run func(ctx context.Context, id string)) *MockVideoExerciseRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockVideoExerciseRepository_Delete_Call) Return(err error) *MockVideoExerciseRepository_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockVideoExerciseRepository_Delete_Call) RunAndReturn(run func(ctx context.Context, id string) error) *MockVideoExerciseRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type MockVideoExerciseRepository
func (_mock *MockVideoExerciseRepository) GetByID(ctx context.Context, id string) (*models.VideoExercise, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *models.VideoExercise
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*models.VideoExercise, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *models.VideoExercise); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.VideoExercise)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockVideoExerciseRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockVideoExerciseRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockVideoExerciseRepository_Expecter) GetByID(ctx any, id any) *MockVideoExerciseRepository_GetByID_Call {
	return &MockVideoExerciseRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockVideoExerciseRepository_GetByID_Call) Run(run func(ctx context.Context, id string)) *MockVideoExerciseRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockVideoExerciseRepository_GetByID_Call) Return(videoExercise *models.VideoExercise, err error) *MockVideoExerciseRepository_GetByID_Call {
	_c.Call.Return(videoExercise, err)
	return _c
}

func (_c *MockVideoExerciseRepository_GetByID_Call) RunAndReturn(run func(ctx context.Context, id string) (*models.VideoExercise, error)) *MockVideoExerciseRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetDetail provides a mock function for the type MockVideoExerciseRepository
func (_mock *MockVideoExerciseRepository) GetDetail(ctx context.Context, id string) (*models.VideoExercise, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetDetail")
	}

	var r0 *models.VideoExercise
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*models.VideoExercise, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *models.VideoExercise); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.VideoExercise)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockVideoExerciseRepository_GetDetail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDetail'
type MockVideoExerciseRepository_GetDetail_Call struct {
	*mock.Call
}

// GetDetail is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockVideoExerciseRepository_Expecter) GetDetail(ctx any, id any) *MockVideoExerciseRepository_GetDetail_Call {
	return &MockVideoExerciseRepository_GetDetail_Call{Call: _e.mock.On("GetDetail", ctx, id)}
}

func (_c *MockVideoExerciseRepository_GetDetail_Call) Run(run func(ctx context.Context, id string)) *MockVideoExerciseRepository_GetDetail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockVideoExerciseRepository_GetDetail_Call) Return(videoExercise *models.VideoExercise, err error) *MockVideoExerciseRepository_GetDetail_Call {
	_c.Call.Return(videoExercise, err)
	return _c
}

func (_c *MockVideoExerciseRepository_GetDetail_Call) RunAndReturn(run func(ctx context.Context, id string) (*models.VideoExercise, error)) *MockVideoExerciseRepository_GetDetail_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockVideoExerciseRepository
func (_mock *MockVideoExerciseRepository) List(ctx context.Context, limit int, offset int) ([]*models.VideoExercise, error) {
	ret := _mock.Called(ctx, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*models.VideoExercise
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int) ([]*models.VideoExercise, error)); ok {
		return returnFunc(ctx, limit, offset)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int) []*models.VideoExercise); ok {
		r0 = returnFunc(ctx, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.VideoExercise)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, int) error); ok {
		r1 = returnFunc(ctx, limit, offset)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockVideoExerciseRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockVideoExerciseRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - limit int
//   - offset int
func (_e *MockVideoExerciseRepository_Expecter) List(ctx any, limit any, offset any) *MockVideoExerciseRepository_List_Call {
	return &MockVideoExerciseRepository_List_Call{Call: _e.mock.On("List", ctx, limit, offset)}
}

func (_c *MockVideoExerciseRepository_List_Call) Run(run func(ctx context.Context, limit int, offset int)) *MockVideoExerciseRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockVideoExerciseRepository_List_Call) Return(videoExercises []*models.VideoExercise, err error) *MockVideoExerciseRepository_List_Call {
	_c.Call.Return(videoExercises, err)
	return _c
}

func (_c *MockVideoExerciseRepository_List_Call) RunAndReturn(run func(ctx context.Context, limit int, offset int) ([]*models.VideoExercise, error)) *MockVideoExerciseRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockVideoExerciseRepository
func (_mock *MockVideoExerciseRepository) Update(ctx context.Context, lesson *models.VideoExercise) error {
	ret := _mock.Called(ctx, lesson)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *models.VideoExercise) error); ok {
		r0 = returnFunc(ctx, lesson)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockVideoExerciseRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockVideoExerciseRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - lesson *models.VideoExercise
func (_e *MockVideoExerciseRepository_Expecter) Update(ctx any, lesson any) *MockVideoExerciseRepository_Update_Call {
	return &MockVideoExerciseRepository_Update_Call{Call: _e.mock.On("Update", ctx, lesson)}
}

func (_c *MockVideoExerciseRepository_Update_Call) Run(run func(ctx context.Context, lesson *models.VideoExercise)) *MockVideoExerciseRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *models.VideoExercise
		if args[1] != nil {
			arg1 = args[1].(*models.VideoExercise)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockVideoExerciseRepository_Update_Call) Return(err error) *MockVideoExerciseRepository_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockVideoExerciseRepository_Update_Call) RunAndReturn(run func(ctx context.Context, lesson *models.VideoExercise) error) *MockVideoExerciseRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// WithTx provides a mock function for the type MockVideoExerciseRepository
func (_mock *MockVideoExerciseRepository) WithTx(tx *gorm.DB) repositories.VideoExerciseRepository {
	ret := _mock.Called(tx)

	if len(ret) == 0 {
		panic("no return value specified for WithTx")
	}

	var r0 repositories.VideoExerciseRepository
	if returnFunc, ok := ret.Get(0).(func(*gorm.DB) repositories.VideoExerciseRepository); ok {
		r0 = returnFunc(tx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(repositories.VideoExerciseRepository)
		}
	}
	return r0
}

// MockVideoExerciseRepository_WithTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WithTx'
type MockVideoExerciseRepository_WithTx_Call struct {
	*mock.Call
}

// WithTx is a helper method to define mock.On call
//   - tx *gorm.DB
func (_e *MockVideoExerciseRepository_Expecter) WithTx(tx any) *MockVideoExerciseRepository_WithTx_Call {
	return &MockVideoExerciseRepository_WithTx_Call{Call: _e.mock.On("WithTx", tx)}
}

func (_c *MockVideoExerciseRepository_WithTx_Call) Run(run func(tx *gorm.DB)) *MockVideoExerciseRepository_WithTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *gorm.DB
		if args[0] != nil {
			arg0 = args[0].(*gorm.DB)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockVideoExerciseRepository_WithTx_Call) Return(videoExerciseRepository repositories.VideoExerciseRepository) *MockVideoExerciseRepository_WithTx_Call {
	_c.Call.Return(videoExerciseRepository)
	return _c
}

func (_c *MockVideoExerciseRepository_WithTx_Call) RunAndReturn(run func(tx *gorm.DB) repositories.VideoExerciseRepository) *MockVideoExerciseRepository_WithTx_Call {
	_c.Call.Return(run)
	return _c
}
