// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"engflex-api/internal/database/repositories"

	mock "github.com/stretchr/testify/mock"
	"gorm.io/gorm"
)

// NewMockVocabularyItemRepository creates a new instance of MockVocabularyItemRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockVocabularyItemRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockVocabularyItemRepository {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockVocabularyItemRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockVocabularyItemRepository is an autogenerated mock type for the VocabularyItemRepository type
type MockVocabularyItemRepository struct {
	mock.Mock
}

type MockVocabularyItemRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockVocabularyItemRepository) EXPECT() *MockVocabularyItemRepository_Expecter {
	return &MockVocabularyItemRepository_Expecter{mock: &_m.Mock}
}

// WithTx provides a mock function for the type MockVocabularyItemRepository
func (_mock *MockVocabularyItemRepository) WithTx(tx *gorm.DB) repositories.VocabularyItemRepository {
	ret := _mock.Called(tx)

	if len(ret) == 0 {
		panic("no return value specified for WithTx")
	}

	var r0 repositories.VocabularyItemRepository
	if returnFunc, ok := ret.Get(0).(func(*gorm.DB) repositories.VocabularyItemRepository); ok {
		r0 = returnFunc(tx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(repositories.VocabularyItemRepository)
		}
	}
	return r0
}

// MockVocabularyItemRepository_WithTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WithTx'
type MockVocabularyItemRepository_WithTx_Call struct {
	*mock.Call
}

// WithTx is a helper method to define mock.On call
//   - tx *gorm.DB
func (_e *MockVocabularyItemRepository_Expecter) WithTx(tx any) *MockVocabularyItemRepository_WithTx_Call {
	return &MockVocabularyItemRepository_WithTx_Call{Call: _e.mock.On("WithTx", tx)}
}

func (_c *MockVocabularyItemRepository_WithTx_Call) Run(run func(tx *gorm.DB)) *MockVocabularyItemRepository_WithTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *gorm.DB
		if args[0] != nil {
			arg0 = args[0].(*gorm.DB)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockVocabularyItemRepository_WithTx_Call) Return(vocabularyItemRepository repositories.VocabularyItemRepository) *MockVocabularyItemRepository_WithTx_Call {
	_c.Call.Return(vocabularyItemRepository)
	return _c
}

func (_c *MockVocabularyItemRepository_WithTx_Call) RunAndReturn(run func(tx *gorm.DB) repositories.VocabularyItemRepository) *MockVocabularyItemRepository_WithTx_Call {
	_c.Call.Return(run)
	return _c
}
