// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"engflex-api/internal/database/models"
	"engflex-api/internal/database/repositories"

	mock "github.com/stretchr/testify/mock"
	"gorm.io/gorm"
)

// NewMockVocabularyDeckItemRepository creates a new instance of MockVocabularyDeckItemRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockVocabularyDeckItemRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockVocabularyDeckItemRepository {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockVocabularyDeckItemRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockVocabularyDeckItemRepository is an autogenerated mock type for the VocabularyDeckItemRepository type
type MockVocabularyDeckItemRepository struct {
	mock.Mock
}

type MockVocabularyDeckItemRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockVocabularyDeckItemRepository) EXPECT() *MockVocabularyDeckItemRepository_Expecter {
	return &MockVocabularyDeckItemRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockVocabularyDeckItemRepository
func (_mock *MockVocabularyDeckItemRepository) Create(ctx context.Context, i *models.VocabularyDeckItem) error {
	ret := _mock.Called(ctx, i)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *models.VocabularyDeckItem) error); ok {
		r0 = returnFunc(ctx, i)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockVocabularyDeckItemRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockVocabularyDeckItemRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - i *models.VocabularyDeckItem
func (_e *MockVocabularyDeckItemRepository_Expecter) Create(ctx any, i any) *MockVocabularyDeckItemRepository_Create_Call {
	return &MockVocabularyDeckItemRepository_Create_Call{Call: _e.mock.On("Create", ctx, i)}
}

func (_c *MockVocabularyDeckItemRepository_Create_Call) Run(run func(ctx context.Context, i *models.VocabularyDeckItem)) *MockVocabularyDeckItemRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *models.VocabularyDeckItem
		if args[1] != nil {
			arg1 = args[1].(*models.VocabularyDeckItem)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockVocabularyDeckItemRepository_Create_Call) Return(err error) *MockVocabularyDeckItemRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockVocabularyDeckItemRepository_Create_Call) RunAndReturn(run func(ctx context.Context, i *models.VocabularyDeckItem) error) *MockVocabularyDeckItemRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockVocabularyDeckItemRepository
func (_mock *MockVocabularyDeckItemRepository) Delete(ctx context.Context, id string) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockVocabularyDeckItemRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockVocabularyDeckItemRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockVocabularyDeckItemRepository_Expecter) Delete(ctx any, id any) *MockVocabularyDeckItemRepository_Delete_Call {
	return &MockVocabularyDeckItemRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockVocabularyDeckItemRepository_Delete_Call) Run(run func(ctx context.Context, id string)) *MockVocabularyDeckItemRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockVocabularyDeckItemRepository_Delete_Call) Return(err error) *MockVocabularyDeckItemRepository_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockVocabularyDeckItemRepository_Delete_Call) RunAndReturn(run func(ctx context.Context, id string) error) *MockVocabularyDeckItemRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type MockVocabularyDeckItemRepository
func (_mock *MockVocabularyDeckItemRepository) GetByID(ctx context.Context, id string) (*models.VocabularyDeckItem, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *models.VocabularyDeckItem
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*models.VocabularyDeckItem, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *models.VocabularyDeckItem); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.VocabularyDeckItem)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockVocabularyDeckItemRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockVocabularyDeckItemRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockVocabularyDeckItemRepository_Expecter) GetByID(ctx any, id any) *MockVocabularyDeckItemRepository_GetByID_Call {
	return &MockVocabularyDeckItemRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockVocabularyDeckItemRepository_GetByID_Call) Run(run func(ctx context.Context, id string)) *MockVocabularyDeckItemRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockVocabularyDeckItemRepository_GetByID_Call) Return(vocabularyDeckItem *models.VocabularyDeckItem, err error) *MockVocabularyDeckItemRepository_GetByID_Call {
	_c.Call.Return(vocabularyDeckItem, err)
	return _c
}

func (_c *MockVocabularyDeckItemRepository_GetByID_Call) RunAndReturn(run func(ctx context.Context, id string) (*models.VocabularyDeckItem, error)) *MockVocabularyDeckItemRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// ListByDeck provides a mock function for the type MockVocabularyDeckItemRepository
func (_mock *MockVocabularyDeckItemRepository) ListByDeck(ctx context.Context, deckID string) ([]*models.VocabularyDeckItem, error) {
	ret := _mock.Called(ctx, deckID)

	if len(ret) == 0 {
		panic("no return value specified for ListByDeck")
	}

	var r0 []*models.VocabularyDeckItem
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]*models.VocabularyDeckItem, error)); ok {
		return returnFunc(ctx, deckID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []*models.VocabularyDeckItem); ok {
		r0 = returnFunc(ctx, deckID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.VocabularyDeckItem)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, deckID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockVocabularyDeckItemRepository_ListByDeck_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByDeck'
type MockVocabularyDeckItemRepository_ListByDeck_Call struct {
	*mock.Call
}

// ListByDeck is a helper method to define mock.On call
//   - ctx context.Context
//   - deckID string
func (_e *MockVocabularyDeckItemRepository_Expecter) ListByDeck(ctx any, deckID any) *MockVocabularyDeckItemRepository_ListByDeck_Call {
	return &MockVocabularyDeckItemRepository_ListByDeck_Call{Call: _e.mock.On("ListByDeck", ctx, deckID)}
}

func (_c *MockVocabularyDeckItemRepository_ListByDeck_Call) Run(run func(ctx context.Context, deckID string)) *MockVocabularyDeckItemRepository_ListByDeck_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockVocabularyDeckItemRepository_ListByDeck_Call) Return(vocabularyDeckItems []*models.VocabularyDeckItem, err error) *MockVocabularyDeckItemRepository_ListByDeck_Call {
	_c.Call.Return(vocabularyDeckItems, err)
	return _c
}

func (_c *MockVocabularyDeckItemRepository_ListByDeck_Call) RunAndReturn(run func(ctx context.Context, deckID string) ([]*models.VocabularyDeckItem, error)) *MockVocabularyDeckItemRepository_ListByDeck_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockVocabularyDeckItemRepository
func (_mock *MockVocabularyDeckItemRepository) Update(ctx context.Context, i *models.VocabularyDeckItem) error {
	ret := _mock.Called(ctx, i)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *models.VocabularyDeckItem) error); ok {
		r0 = returnFunc(ctx, i)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockVocabularyDeckItemRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockVocabularyDeckItemRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - i *models.VocabularyDeckItem
func (_e *MockVocabularyDeckItemRepository_Expecter) Update(ctx any, i any) *MockVocabularyDeckItemRepository_Update_Call {
	return &MockVocabularyDeckItemRepository_Update_Call{Call: _e.mock.On("Update", ctx, i)}
}

func (_c *MockVocabularyDeckItemRepository_Update_Call) Run(run func(ctx context.Context, i *models.VocabularyDeckItem)) *MockVocabularyDeckItemRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *models.VocabularyDeckItem
		if args[1] != nil {
			arg1 = args[1].(*models.VocabularyDeckItem)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockVocabularyDeckItemRepository_Update_Call) Return(err error) *MockVocabularyDeckItemRepository_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockVocabularyDeckItemRepository_Update_Call) RunAndReturn(run func(ctx context.Context, i *models.VocabularyDeckItem) error) *MockVocabularyDeckItemRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// WithTx provides a mock function for the type MockVocabularyDeckItemRepository
func (_mock *MockVocabularyDeckItemRepository) WithTx(tx *gorm.DB) repositories.VocabularyDeckItemRepository {
	ret := _mock.Called(tx)

	if len(ret) == 0 {
		panic("no return value specified for WithTx")
	}

	var r0 repositories.VocabularyDeckItemRepository
	if returnFunc, ok := ret.Get(0).(func(*gorm.DB) repositories.VocabularyDeckItemRepository); ok {
		r0 = returnFunc(tx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(repositories.VocabularyDeckItemRepository)
		}
	}
	return r0
}

// MockVocabularyDeckItemRepository_WithTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WithTx'
type MockVocabularyDeckItemRepository_WithTx_Call struct {
	*mock.Call
}

// WithTx is a helper method to define mock.On call
//   - tx *gorm.DB
func (_e *MockVocabularyDeckItemRepository_Expecter) WithTx(tx any) *MockVocabularyDeckItemRepository_WithTx_Call {
	return &MockVocabularyDeckItemRepository_WithTx_Call{Call: _e.mock.On("WithTx", tx)}
}

func (_c *MockVocabularyDeckItemRepository_WithTx_Call) Run(run func(tx *gorm.DB)) *MockVocabularyDeckItemRepository_WithTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *gorm.DB
		if args[0] != nil {
			arg0 = args[0].(*gorm.DB)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockVocabularyDeckItemRepository_WithTx_Call) Return(vocabularyDeckItemRepository repositories.VocabularyDeckItemRepository) *MockVocabularyDeckItemRepository_WithTx_Call {
	_c.Call.Return(vocabularyDeckItemRepository)
	return _c
}

func (_c *MockVocabularyDeckItemRepository_WithTx_Call) RunAndReturn(run func(tx *gorm.DB) repositories.VocabularyDeckItemRepository) *MockVocabularyDeckItemRepository_WithTx_Call {
	_c.Call.Return(run)
	return _c
}
