// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"engflex-api/internal/database/models"
	"engflex-api/internal/database/repositories"

	mock "github.com/stretchr/testify/mock"
	"gorm.io/gorm"
)

// NewMockVocabularyDeckRepository creates a new instance of MockVocabularyDeckRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockVocabularyDeckRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockVocabularyDeckRepository {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockVocabularyDeckRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockVocabularyDeckRepository is an autogenerated mock type for the VocabularyDeckRepository type
type MockVocabularyDeckRepository struct {
	mock.Mock
}

type MockVocabularyDeckRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockVocabularyDeckRepository) EXPECT() *MockVocabularyDeckRepository_Expecter {
	return &MockVocabularyDeckRepository_Expecter{mock: &_m.Mock}
}

// CountByUser provides a mock function for the type MockVocabularyDeckRepository
func (_mock *MockVocabularyDeckRepository) CountByUser(ctx context.Context, userID string) (int64, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for CountByUser")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (int64, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) int64); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockVocabularyDeckRepository_CountByUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountByUser'
type MockVocabularyDeckRepository_CountByUser_Call struct {
	*mock.Call
}

// CountByUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockVocabularyDeckRepository_Expecter) CountByUser(ctx any, userID any) *MockVocabularyDeckRepository_CountByUser_Call {
	return &MockVocabularyDeckRepository_CountByUser_Call{Call: _e.mock.On("CountByUser", ctx, userID)}
}

func (_c *MockVocabularyDeckRepository_CountByUser_Call) Run(run func(ctx context.Context, userID string)) *MockVocabularyDeckRepository_CountByUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockVocabularyDeckRepository_CountByUser_Call) Return(n int64, err error) *MockVocabularyDeckRepository_CountByUser_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockVocabularyDeckRepository_CountByUser_Call) RunAndReturn(run func(ctx context.Context, userID string) (int64, error)) *MockVocabularyDeckRepository_CountByUser_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function for the type MockVocabularyDeckRepository
func (_mock *MockVocabularyDeckRepository) Create(ctx context.Context, d *models.VocabularyDeck) error {
	ret := _mock.Called(ctx, d)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *models.VocabularyDeck) error); ok {
		r0 = returnFunc(ctx, d)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockVocabularyDeckRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockVocabularyDeckRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - d *models.VocabularyDeck
func (_e *MockVocabularyDeckRepository_Expecter) Create(ctx any, d any) *MockVocabularyDeckRepository_Create_Call {
	return &MockVocabularyDeckRepository_Create_Call{Call: _e.mock.On("Create", ctx, d)}
}

func (_c *MockVocabularyDeckRepository_Create_Call) Run(run func(ctx context.Context, d *models.VocabularyDeck)) *MockVocabularyDeckRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *models.VocabularyDeck
		if args[1] != nil {
			arg1 = args[1].(*models.VocabularyDeck)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockVocabularyDeckRepository_Create_Call) Return(err error) *MockVocabularyDeckRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockVocabularyDeckRepository_Create_Call) RunAndReturn(run func(ctx context.Context, d *models.VocabularyDeck) error) *MockVocabularyDeckRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockVocabularyDeckRepository
func (_mock *MockVocabularyDeckRepository) Delete(ctx context.Context, id string) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockVocabularyDeckRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockVocabularyDeckRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockVocabularyDeckRepository_Expecter) Delete(ctx any, id any) *MockVocabularyDeckRepository_Delete_Call {
	return &MockVocabularyDeckRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockVocabularyDeckRepository_Delete_Call) Run(run func(ctx context.Context, id string)) *MockVocabularyDeckRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockVocabularyDeckRepository_Delete_Call) Return(err error) *MockVocabularyDeckRepository_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockVocabularyDeckRepository_Delete_Call) RunAndReturn(run func(ctx context.Context, id string) error) *MockVocabularyDeckRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type MockVocabularyDeckRepository
func (_mock *MockVocabularyDeckRepository) GetByID(ctx context.Context, id string) (*models.VocabularyDeck, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *models.VocabularyDeck
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*models.VocabularyDeck, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *models.VocabularyDeck); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.VocabularyDeck)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockVocabularyDeckRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockVocabularyDeckRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockVocabularyDeckRepository_Expecter) GetByID(ctx any, id any) *MockVocabularyDeckRepository_GetByID_Call {
	return &MockVocabularyDeckRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockVocabularyDeckRepository_GetByID_Call) Run(run func(ctx context.Context, id string)) *MockVocabularyDeckRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockVocabularyDeckRepository_GetByID_Call) Return(vocabularyDeck *models.VocabularyDeck, err error) *MockVocabularyDeckRepository_GetByID_Call {
	_c.Call.Return(vocabularyDeck, err)
	return _c
}

func (_c *MockVocabularyDeckRepository_GetByID_Call) RunAndReturn(run func(ctx context.Context, id string) (*models.VocabularyDeck, error)) *MockVocabularyDeckRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetDetail provides a mock function for the type MockVocabularyDeckRepository
func (_mock *MockVocabularyDeckRepository) GetDetail(ctx context.Context, id string) (*models.VocabularyDeck, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetDetail")
	}

	var r0 *models.VocabularyDeck
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*models.VocabularyDeck, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *models.VocabularyDeck); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.VocabularyDeck)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockVocabularyDeckRepository_GetDetail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDetail'
type MockVocabularyDeckRepository_GetDetail_Call struct {
	*mock.Call
}

// GetDetail is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockVocabularyDeckRepository_Expecter) GetDetail(ctx any, id any) *MockVocabularyDeckRepository_GetDetail_Call {
	return &MockVocabularyDeckRepository_GetDetail_Call{Call: _e.mock.On("GetDetail", ctx, id)}
}

func (_c *MockVocabularyDeckRepository_GetDetail_Call) Run(run func(ctx context.Context, id string)) *MockVocabularyDeckRepository_GetDetail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockVocabularyDeckRepository_GetDetail_Call) Return(vocabularyDeck *models.VocabularyDeck, err error) *MockVocabularyDeckRepository_GetDetail_Call {
	_c.Call.Return(vocabularyDeck, err)
	return _c
}

func (_c *MockVocabularyDeckRepository_GetDetail_Call) RunAndReturn(run func(ctx context.Context, id string) (*models.VocabularyDeck, error)) *MockVocabularyDeckRepository_GetDetail_Call {
	_c.Call.Return(run)
	return _c
}

// ListByUser provides a mock function for the type MockVocabularyDeckRepository
func (_mock *MockVocabularyDeckRepository) ListByUser(ctx context.Context, userID string, limit int, offset int) ([]*models.VocabularyDeck, error) {
	ret := _mock.Called(ctx, userID, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for ListByUser")
	}

	var r0 []*models.VocabularyDeck
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int, int) ([]*models.VocabularyDeck, error)); ok {
		return returnFunc(ctx, userID, limit, offset)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int, int) []*models.VocabularyDeck); ok {
		r0 = returnFunc(ctx, userID, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.VocabularyDeck)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, int, int) error); ok {
		r1 = returnFunc(ctx, userID, limit, offset)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockVocabularyDeckRepository_ListByUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByUser'
type MockVocabularyDeckRepository_ListByUser_Call struct {
	*mock.Call
}

// ListByUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - limit int
//   - offset int
func (_e *MockVocabularyDeckRepository_Expecter) ListByUser(ctx any, userID any, limit any, offset any) *MockVocabularyDeckRepository_ListByUser_Call {
	return &MockVocabularyDeckRepository_ListByUser_Call{Call: _e.mock.On("ListByUser", ctx, userID, limit, offset)}
}

func (_c *MockVocabularyDeckRepository_ListByUser_Call) Run(run func(ctx context.Context, userID string, limit int, offset int)) *MockVocabularyDeckRepository_ListByUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockVocabularyDeckRepository_ListByUser_Call) Return(vocabularyDecks []*models.VocabularyDeck, err error) *MockVocabularyDeckRepository_ListByUser_Call {
	_c.Call.Return(vocabularyDecks, err)
	return _c
}

func (_c *MockVocabularyDeckRepository_ListByUser_Call) RunAndReturn(run func(ctx context.Context, userID string, limit int, offset int) ([]*models.VocabularyDeck, error)) *MockVocabularyDeckRepository_ListByUser_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockVocabularyDeckRepository
func (_mock *MockVocabularyDeckRepository) Update(ctx context.Context, d *models.VocabularyDeck) error {
	ret := _mock.Called(ctx, d)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *models.VocabularyDeck) error); ok {
		r0 = returnFunc(ctx, d)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockVocabularyDeckRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockVocabularyDeckRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - d *models.VocabularyDeck
func (_e *MockVocabularyDeckRepository_Expecter) Update(ctx any, d any) *MockVocabularyDeckRepository_Update_Call {
	return &MockVocabularyDeckRepository_Update_Call{Call: _e.mock.On("Update", ctx, d)}
}

func (_c *MockVocabularyDeckRepository_Update_Call) Run(run func(ctx context.Context, d *models.VocabularyDeck)) *MockVocabularyDeckRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *models.VocabularyDeck
		if args[1] != nil {
			arg1 = args[1].(*models.VocabularyDeck)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockVocabularyDeckRepository_Update_Call) Return(err error) *MockVocabularyDeckRepository_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockVocabularyDeckRepository_Update_Call) RunAndReturn(run func(ctx context.Context, d *models.VocabularyDeck) error) *MockVocabularyDeckRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// WithTx provides a mock function for the type MockVocabularyDeckRepository
func (_mock *MockVocabularyDeckRepository) WithTx(tx *gorm.DB) repositories.VocabularyDeckRepository {
	ret := _mock.Called(tx)

	if len(ret) == 0 {
		panic("no return value specified for WithTx")
	}

	var r0 repositories.VocabularyDeckRepository
	if returnFunc, ok := ret.Get(0).(func(*gorm.DB) repositories.VocabularyDeckRepository); ok {
		r0 = returnFunc(tx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(repositories.VocabularyDeckRepository)
		}
	}
	return r0
}

// MockVocabularyDeckRepository_WithTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WithTx'
type MockVocabularyDeckRepository_WithTx_Call struct {
	*mock.Call
}

// WithTx is a helper method to define mock.On call
//   - tx *gorm.DB
func (_e *MockVocabularyDeckRepository_Expecter) WithTx(tx any) *MockVocabularyDeckRepository_WithTx_Call {
	return &MockVocabularyDeckRepository_WithTx_Call{Call: _e.mock.On("WithTx", tx)}
}

func (_c *MockVocabularyDeckRepository_WithTx_Call) Run(run func(tx *gorm.DB)) *MockVocabularyDeckRepository_WithTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *gorm.DB
		if args[0] != nil {
			arg0 = args[0].(*gorm.DB)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockVocabularyDeckRepository_WithTx_Call) Return(vocabularyDeckRepository repositories.VocabularyDeckRepository) *MockVocabularyDeckRepository_WithTx_Call {
	_c.Call.Return(vocabularyDeckRepository)
	return _c
}

func (_c *MockVocabularyDeckRepository_WithTx_Call) RunAndReturn(run func(tx *gorm.DB) repositories.VocabularyDeckRepository) *MockVocabularyDeckRepository_WithTx_Call {
	_c.Call.Return(run)
	return _c
}
