// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"engflex-api/internal/database/repositories"

	mock "github.com/stretchr/testify/mock"
	"gorm.io/gorm"
)

// NewMockUserVocabularyRepository creates a new instance of MockUserVocabularyRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserVocabularyRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserVocabularyRepository {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockUserVocabularyRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockUserVocabularyRepository is an autogenerated mock type for the UserVocabularyRepository type
type MockUserVocabularyRepository struct {
	mock.Mock
}

type MockUserVocabularyRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserVocabularyRepository) EXPECT() *MockUserVocabularyRepository_Expecter {
	return &MockUserVocabularyRepository_Expecter{mock: &_m.Mock}
}

// WithTx provides a mock function for the type MockUserVocabularyRepository
func (_mock *MockUserVocabularyRepository) WithTx(tx *gorm.DB) repositories.UserVocabularyRepository {
	ret := _mock.Called(tx)

	if len(ret) == 0 {
		panic("no return value specified for WithTx")
	}

	var r0 repositories.UserVocabularyRepository
	if returnFunc, ok := ret.Get(0).(func(*gorm.DB) repositories.UserVocabularyRepository); ok {
		r0 = returnFunc(tx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(repositories.UserVocabularyRepository)
		}
	}
	return r0
}

// MockUserVocabularyRepository_WithTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WithTx'
type MockUserVocabularyRepository_WithTx_Call struct {
	*mock.Call
}

// WithTx is a helper method to define mock.On call
//   - tx *gorm.DB
func (_e *MockUserVocabularyRepository_Expecter) WithTx(tx any) *MockUserVocabularyRepository_WithTx_Call {
	return &MockUserVocabularyRepository_WithTx_Call{Call: _e.mock.On("WithTx", tx)}
}

func (_c *MockUserVocabularyRepository_WithTx_Call) Run(run func(tx *gorm.DB)) *MockUserVocabularyRepository_WithTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *gorm.DB
		if args[0] != nil {
			arg0 = args[0].(*gorm.DB)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockUserVocabularyRepository_WithTx_Call) Return(userVocabularyRepository repositories.UserVocabularyRepository) *MockUserVocabularyRepository_WithTx_Call {
	_c.Call.Return(userVocabularyRepository)
	return _c
}

func (_c *MockUserVocabularyRepository_WithTx_Call) RunAndReturn(run func(tx *gorm.DB) repositories.UserVocabularyRepository) *MockUserVocabularyRepository_WithTx_Call {
	_c.Call.Return(run)
	return _c
}
