// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"engflex-api/internal/database/repositories"

	mock "github.com/stretchr/testify/mock"
	"gorm.io/gorm"
)

// NewMockLessonActivityRepository creates a new instance of MockLessonActivityRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLessonActivityRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLessonActivityRepository {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockLessonActivityRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockLessonActivityRepository is an autogenerated mock type for the LessonActivityRepository type
type MockLessonActivityRepository struct {
	mock.Mock
}

type MockLessonActivityRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLessonActivityRepository) EXPECT() *MockLessonActivityRepository_Expecter {
	return &MockLessonActivityRepository_Expecter{mock: &_m.Mock}
}

// WithTx provides a mock function for the type MockLessonActivityRepository
func (_mock *MockLessonActivityRepository) WithTx(tx *gorm.DB) repositories.LessonActivityRepository {
	ret := _mock.Called(tx)

	if len(ret) == 0 {
		panic("no return value specified for WithTx")
	}

	var r0 repositories.LessonActivityRepository
	if returnFunc, ok := ret.Get(0).(func(*gorm.DB) repositories.LessonActivityRepository); ok {
		r0 = returnFunc(tx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(repositories.LessonActivityRepository)
		}
	}
	return r0
}

// MockLessonActivityRepository_WithTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WithTx'
type MockLessonActivityRepository_WithTx_Call struct {
	*mock.Call
}

// WithTx is a helper method to define mock.On call
//   - tx *gorm.DB
func (_e *MockLessonActivityRepository_Expecter) WithTx(tx any) *MockLessonActivityRepository_WithTx_Call {
	return &MockLessonActivityRepository_WithTx_Call{Call: _e.mock.On("WithTx", tx)}
}

func (_c *MockLessonActivityRepository_WithTx_Call) Run(run func(tx *gorm.DB)) *MockLessonActivityRepository_WithTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *gorm.DB
		if args[0] != nil {
			arg0 = args[0].(*gorm.DB)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockLessonActivityRepository_WithTx_Call) Return(lessonActivityRepository repositories.LessonActivityRepository) *MockLessonActivityRepository_WithTx_Call {
	_c.Call.Return(lessonActivityRepository)
	return _c
}

func (_c *MockLessonActivityRepository_WithTx_Call) RunAndReturn(run func(tx *gorm.DB) repositories.LessonActivityRepository) *MockLessonActivityRepository_WithTx_Call {
	_c.Call.Return(run)
	return _c
}
