// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"engflex-api/internal/database/models"
	"engflex-api/internal/database/repositories"

	mock "github.com/stretchr/testify/mock"
	"gorm.io/gorm"
)

// NewMockFeedbackRepository creates a new instance of MockFeedbackRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFeedbackRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFeedbackRepository {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockFeedbackRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockFeedbackRepository is an autogenerated mock type for the FeedbackRepository type
type MockFeedbackRepository struct {
	mock.Mock
}

type MockFeedbackRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFeedbackRepository) EXPECT() *MockFeedbackRepository_Expecter {
	return &MockFeedbackRepository_Expecter{mock: &_m.Mock}
}

// ListForSubjects provides a mock function for the type MockFeedbackRepository
func (_mock *MockFeedbackRepository) ListForSubjects(ctx context.Context, userID string, subjectType string, subjectIDs []string) ([]*models.Feedback, error) {
	ret := _mock.Called(ctx, userID, subjectType, subjectIDs)

	if len(ret) == 0 {
		panic("no return value specified for ListForSubjects")
	}

	var r0 []*models.Feedback
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, []string) ([]*models.Feedback, error)); ok {
		return returnFunc(ctx, userID, subjectType, subjectIDs)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, []string) []*models.Feedback); ok {
		r0 = returnFunc(ctx, userID, subjectType, subjectIDs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Feedback)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, []string) error); ok {
		r1 = returnFunc(ctx, userID, subjectType, subjectIDs)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFeedbackRepository_ListForSubjects_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListForSubjects'
type MockFeedbackRepository_ListForSubjects_Call struct {
	*mock.Call
}

// ListForSubjects is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - subjectType string
//   - subjectIDs []string
func (_e *MockFeedbackRepository_Expecter) ListForSubjects(ctx any, userID any, subjectType any, subjectIDs any) *MockFeedbackRepository_ListForSubjects_Call {
	return &MockFeedbackRepository_ListForSubjects_Call{Call: _e.mock.On("ListForSubjects", ctx, userID, subjectType, subjectIDs)}
}

func (_c *MockFeedbackRepository_ListForSubjects_Call) Run(run func(ctx context.Context, userID string, subjectType string, subjectIDs []string)) *MockFeedbackRepository_ListForSubjects_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 []string
		if args[3] != nil {
			arg3 = args[3].([]string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockFeedbackRepository_ListForSubjects_Call) Return(feedbacks []*models.Feedback, err error) *MockFeedbackRepository_ListForSubjects_Call {
	_c.Call.Return(feedbacks, err)
	return _c
}

func (_c *MockFeedbackRepository_ListForSubjects_Call) RunAndReturn(run func(ctx context.Context, userID string, subjectType string, subjectIDs []string) ([]*models.Feedback, error)) *MockFeedbackRepository_ListForSubjects_Call {
	_c.Call.Return(run)
	return _c
}

// Upsert provides a mock function for the type MockFeedbackRepository
func (_mock *MockFeedbackRepository) Upsert(ctx context.Context, f *models.Feedback) error {
	ret := _mock.Called(ctx, f)

	if len(ret) == 0 {
		panic("no return value specified for Upsert")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *models.Feedback) error); ok {
		r0 = returnFunc(ctx, f)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockFeedbackRepository_Upsert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Upsert'
type MockFeedbackRepository_Upsert_Call struct {
	*mock.Call
}

// Upsert is a helper method to define mock.On call
//   - ctx context.Context
//   - f *models.Feedback
func (_e *MockFeedbackRepository_Expecter) Upsert(ctx any, f any) *MockFeedbackRepository_Upsert_Call {
	return &MockFeedbackRepository_Upsert_Call{Call: _e.mock.On("Upsert", ctx, f)}
}

func (_c *MockFeedbackRepository_Upsert_Call) Run(run func(ctx context.Context, f *models.Feedback)) *MockFeedbackRepository_Upsert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *models.Feedback
		if args[1] != nil {
			arg1 = args[1].(*models.Feedback)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFeedbackRepository_Upsert_Call) Return(err error) *MockFeedbackRepository_Upsert_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockFeedbackRepository_Upsert_Call) RunAndReturn(run func(ctx context.Context, f *models.Feedback) error) *MockFeedbackRepository_Upsert_Call {
	_c.Call.Return(run)
	return _c
}

// WithTx provides a mock function for the type MockFeedbackRepository
func (_mock *MockFeedbackRepository) WithTx(tx *gorm.DB) repositories.FeedbackRepository {
	ret := _mock.Called(tx)

	if len(ret) == 0 {
		panic("no return value specified for WithTx")
	}

	var r0 repositories.FeedbackRepository
	if returnFunc, ok := ret.Get(0).(func(*gorm.DB) repositories.FeedbackRepository); ok {
		r0 = returnFunc(tx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(repositories.FeedbackRepository)
		}
	}
	return r0
}

// MockFeedbackRepository_WithTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WithTx'
type MockFeedbackRepository_WithTx_Call struct {
	*mock.Call
}

// WithTx is a helper method to define mock.On call
//   - tx *gorm.DB
func (_e *MockFeedbackRepository_Expecter) WithTx(tx any) *MockFeedbackRepository_WithTx_Call {
	return &MockFeedbackRepository_WithTx_Call{Call: _e.mock.On("WithTx", tx)}
}

func (_c *MockFeedbackRepository_WithTx_Call) Run(run func(tx *gorm.DB)) *MockFeedbackRepository_WithTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *gorm.DB
		if args[0] != nil {
			arg0 = args[0].(*gorm.DB)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockFeedbackRepository_WithTx_Call) Return(feedbackRepository repositories.FeedbackRepository) *MockFeedbackRepository_WithTx_Call {
	_c.Call.Return(feedbackRepository)
	return _c
}

func (_c *MockFeedbackRepository_WithTx_Call) RunAndReturn(run func(tx *gorm.DB) repositories.FeedbackRepository) *MockFeedbackRepository_WithTx_Call {
	_c.Call.Return(run)
	return _c
}
