// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"engflex-api/internal/database/models"
	"engflex-api/internal/database/repositories"

	mock "github.com/stretchr/testify/mock"
	"gorm.io/gorm"
)

// NewMockConversationTurnRepository creates a new instance of MockConversationTurnRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockConversationTurnRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockConversationTurnRepository {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockConversationTurnRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockConversationTurnRepository is an autogenerated mock type for the ConversationTurnRepository type
type MockConversationTurnRepository struct {
	mock.Mock
}

type MockConversationTurnRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockConversationTurnRepository) EXPECT() *MockConversationTurnRepository_Expecter {
	return &MockConversationTurnRepository_Expecter{mock: &_m.Mock}
}

// GetTurnByID provides a mock function for the type MockConversationTurnRepository
func (_mock *MockConversationTurnRepository) GetTurnByID(ctx context.Context, turnID string) (*models.ConversationTurn, error) {
	ret := _mock.Called(ctx, turnID)

	if len(ret) == 0 {
		panic("no return value specified for GetTurnByID")
	}

	var r0 *models.ConversationTurn
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*models.ConversationTurn, error)); ok {
		return returnFunc(ctx, turnID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *models.ConversationTurn); ok {
		r0 = returnFunc(ctx, turnID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.ConversationTurn)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, turnID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockConversationTurnRepository_GetTurnByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTurnByID'
type MockConversationTurnRepository_GetTurnByID_Call struct {
	*mock.Call
}

// GetTurnByID is a helper method to define mock.On call
//   - ctx context.Context
//   - turnID string
func (_e *MockConversationTurnRepository_Expecter) GetTurnByID(ctx any, turnID any) *MockConversationTurnRepository_GetTurnByID_Call {
	return &MockConversationTurnRepository_GetTurnByID_Call{Call: _e.mock.On("GetTurnByID", ctx, turnID)}
}

func (_c *MockConversationTurnRepository_GetTurnByID_Call) Run(run func(ctx context.Context, turnID string)) *MockConversationTurnRepository_GetTurnByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockConversationTurnRepository_GetTurnByID_Call) Return(conversationTurn *models.ConversationTurn, err error) *MockConversationTurnRepository_GetTurnByID_Call {
	_c.Call.Return(conversationTurn, err)
	return _c
}

func (_c *MockConversationTurnRepository_GetTurnByID_Call) RunAndReturn(run func(ctx context.Context, turnID string) (*models.ConversationTurn, error)) *MockConversationTurnRepository_GetTurnByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetTurnByPosition provides a mock function for the type MockConversationTurnRepository
func (_mock *MockConversationTurnRepository) GetTurnByPosition(ctx context.Context, conversationID string, position int) (*models.ConversationTurn, error) {
	ret := _mock.Called(ctx, conversationID, position)

	if len(ret) == 0 {
		panic("no return value specified for GetTurnByPosition")
	}

	var r0 *models.ConversationTurn
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int) (*models.ConversationTurn, error)); ok {
		return returnFunc(ctx, conversationID, position)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int) *models.ConversationTurn); ok {
		r0 = returnFunc(ctx, conversationID, position)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.ConversationTurn)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, int) error); ok {
		r1 = returnFunc(ctx, conversationID, position)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockConversationTurnRepository_GetTurnByPosition_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTurnByPosition'
type MockConversationTurnRepository_GetTurnByPosition_Call struct {
	*mock.Call
}

// GetTurnByPosition is a helper method to define mock.On call
//   - ctx context.Context
//   - conversationID string
//   - position int
func (_e *MockConversationTurnRepository_Expecter) GetTurnByPosition(ctx any, conversationID any, position any) *MockConversationTurnRepository_GetTurnByPosition_Call {
	return &MockConversationTurnRepository_GetTurnByPosition_Call{Call: _e.mock.On("GetTurnByPosition", ctx, conversationID, position)}
}

func (_c *MockConversationTurnRepository_GetTurnByPosition_Call) Run(run func(ctx context.Context, conversationID string, position int)) *MockConversationTurnRepository_GetTurnByPosition_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockConversationTurnRepository_GetTurnByPosition_Call) Return(conversationTurn *models.ConversationTurn, err error) *MockConversationTurnRepository_GetTurnByPosition_Call {
	_c.Call.Return(conversationTurn, err)
	return _c
}

func (_c *MockConversationTurnRepository_GetTurnByPosition_Call) RunAndReturn(run func(ctx context.Context, conversationID string, position int) (*models.ConversationTurn, error)) *MockConversationTurnRepository_GetTurnByPosition_Call {
	_c.Call.Return(run)
	return _c
}

// ListTurns provides a mock function for the type MockConversationTurnRepository
func (_mock *MockConversationTurnRepository) ListTurns(ctx context.Context, conversationID string) ([]*models.ConversationTurn, error) {
	ret := _mock.Called(ctx, conversationID)

	if len(ret) == 0 {
		panic("no return value specified for ListTurns")
	}

	var r0 []*models.ConversationTurn
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]*models.ConversationTurn, error)); ok {
		return returnFunc(ctx, conversationID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []*models.ConversationTurn); ok {
		r0 = returnFunc(ctx, conversationID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.ConversationTurn)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, conversationID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockConversationTurnRepository_ListTurns_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListTurns'
type MockConversationTurnRepository_ListTurns_Call struct {
	*mock.Call
}

// ListTurns is a helper method to define mock.On call
//   - ctx context.Context
//   - conversationID string
func (_e *MockConversationTurnRepository_Expecter) ListTurns(ctx any, conversationID any) *MockConversationTurnRepository_ListTurns_Call {
	return &MockConversationTurnRepository_ListTurns_Call{Call: _e.mock.On("ListTurns", ctx, conversationID)}
}

func (_c *MockConversationTurnRepository_ListTurns_Call) Run(run func(ctx context.Context, conversationID string)) *MockConversationTurnRepository_ListTurns_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockConversationTurnRepository_ListTurns_Call) Return(conversationTurns []*models.ConversationTurn, err error) *MockConversationTurnRepository_ListTurns_Call {
	_c.Call.Return(conversationTurns, err)
	return _c
}

func (_c *MockConversationTurnRepository_ListTurns_Call) RunAndReturn(run func(ctx context.Context, conversationID string) ([]*models.ConversationTurn, error)) *MockConversationTurnRepository_ListTurns_Call {
	_c.Call.Return(run)
	return _c
}

// ListTurnsWithFeedback provides a mock function for the type MockConversationTurnRepository
func (_mock *MockConversationTurnRepository) ListTurnsWithFeedback(ctx context.Context, conversationID string) ([]*models.ConversationTurn, error) {
	ret := _mock.Called(ctx, conversationID)

	if len(ret) == 0 {
		panic("no return value specified for ListTurnsWithFeedback")
	}

	var r0 []*models.ConversationTurn
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]*models.ConversationTurn, error)); ok {
		return returnFunc(ctx, conversationID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []*models.ConversationTurn); ok {
		r0 = returnFunc(ctx, conversationID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.ConversationTurn)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, conversationID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockConversationTurnRepository_ListTurnsWithFeedback_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListTurnsWithFeedback'
type MockConversationTurnRepository_ListTurnsWithFeedback_Call struct {
	*mock.Call
}

// ListTurnsWithFeedback is a helper method to define mock.On call
//   - ctx context.Context
//   - conversationID string
func (_e *MockConversationTurnRepository_Expecter) ListTurnsWithFeedback(ctx any, conversationID any) *MockConversationTurnRepository_ListTurnsWithFeedback_Call {
	return &MockConversationTurnRepository_ListTurnsWithFeedback_Call{Call: _e.mock.On("ListTurnsWithFeedback", ctx, conversationID)}
}

func (_c *MockConversationTurnRepository_ListTurnsWithFeedback_Call) Run(run func(ctx context.Context, conversationID string)) *MockConversationTurnRepository_ListTurnsWithFeedback_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockConversationTurnRepository_ListTurnsWithFeedback_Call) Return(conversationTurns []*models.ConversationTurn, err error) *MockConversationTurnRepository_ListTurnsWithFeedback_Call {
	_c.Call.Return(conversationTurns, err)
	return _c
}

func (_c *MockConversationTurnRepository_ListTurnsWithFeedback_Call) RunAndReturn(run func(ctx context.Context, conversationID string) ([]*models.ConversationTurn, error)) *MockConversationTurnRepository_ListTurnsWithFeedback_Call {
	_c.Call.Return(run)
	return _c
}

// UpsertTurns provides a mock function for the type MockConversationTurnRepository
func (_mock *MockConversationTurnRepository) UpsertTurns(ctx context.Context, conversationID string, turns []*models.ConversationTurn) (int, error) {
	ret := _mock.Called(ctx, conversationID, turns)

	if len(ret) == 0 {
		panic("no return value specified for UpsertTurns")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []*models.ConversationTurn) (int, error)); ok {
		return returnFunc(ctx, conversationID, turns)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []*models.ConversationTurn) int); ok {
		r0 = returnFunc(ctx, conversationID, turns)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, []*models.ConversationTurn) error); ok {
		r1 = returnFunc(ctx, conversationID, turns)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockConversationTurnRepository_UpsertTurns_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpsertTurns'
type MockConversationTurnRepository_UpsertTurns_Call struct {
	*mock.Call
}

// UpsertTurns is a helper method to define mock.On call
//   - ctx context.Context
//   - conversationID string
//   - turns []*models.ConversationTurn
func (_e *MockConversationTurnRepository_Expecter) UpsertTurns(ctx any, conversationID any, turns any) *MockConversationTurnRepository_UpsertTurns_Call {
	return &MockConversationTurnRepository_UpsertTurns_Call{Call: _e.mock.On("UpsertTurns", ctx, conversationID, turns)}
}

func (_c *MockConversationTurnRepository_UpsertTurns_Call) Run(run func(ctx context.Context, conversationID string, turns []*models.ConversationTurn)) *MockConversationTurnRepository_UpsertTurns_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []*models.ConversationTurn
		if args[2] != nil {
			arg2 = args[2].([]*models.ConversationTurn)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockConversationTurnRepository_UpsertTurns_Call) Return(n int, err error) *MockConversationTurnRepository_UpsertTurns_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockConversationTurnRepository_UpsertTurns_Call) RunAndReturn(run func(ctx context.Context, conversationID string, turns []*models.ConversationTurn) (int, error)) *MockConversationTurnRepository_UpsertTurns_Call {
	_c.Call.Return(run)
	return _c
}

// WithTx provides a mock function for the type MockConversationTurnRepository
func (_mock *MockConversationTurnRepository) WithTx(tx *gorm.DB) repositories.ConversationTurnRepository {
	ret := _mock.Called(tx)

	if len(ret) == 0 {
		panic("no return value specified for WithTx")
	}

	var r0 repositories.ConversationTurnRepository
	if returnFunc, ok := ret.Get(0).(func(*gorm.DB) repositories.ConversationTurnRepository); ok {
		r0 = returnFunc(tx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(repositories.ConversationTurnRepository)
		}
	}
	return r0
}

// MockConversationTurnRepository_WithTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WithTx'
type MockConversationTurnRepository_WithTx_Call struct {
	*mock.Call
}

// WithTx is a helper method to define mock.On call
//   - tx *gorm.DB
func (_e *MockConversationTurnRepository_Expecter) WithTx(tx any) *MockConversationTurnRepository_WithTx_Call {
	return &MockConversationTurnRepository_WithTx_Call{Call: _e.mock.On("WithTx", tx)}
}

func (_c *MockConversationTurnRepository_WithTx_Call) Run(run func(tx *gorm.DB)) *MockConversationTurnRepository_WithTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *gorm.DB
		if args[0] != nil {
			arg0 = args[0].(*gorm.DB)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockConversationTurnRepository_WithTx_Call) Return(conversationTurnRepository repositories.ConversationTurnRepository) *MockConversationTurnRepository_WithTx_Call {
	_c.Call.Return(conversationTurnRepository)
	return _c
}

func (_c *MockConversationTurnRepository_WithTx_Call) RunAndReturn(run func(tx *gorm.DB) repositories.ConversationTurnRepository) *MockConversationTurnRepository_WithTx_Call {
	_c.Call.Return(run)
	return _c
}
