// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"engflex-api/internal/database/repositories"

	mock "github.com/stretchr/testify/mock"
	"gorm.io/gorm"
)

// NewMockAttemptRepository creates a new instance of MockAttemptRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAttemptRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAttemptRepository {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockAttemptRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockAttemptRepository is an autogenerated mock type for the AttemptRepository type
type MockAttemptRepository struct {
	mock.Mock
}

type MockAttemptRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAttemptRepository) EXPECT() *MockAttemptRepository_Expecter {
	return &MockAttemptRepository_Expecter{mock: &_m.Mock}
}

// WithTx provides a mock function for the type MockAttemptRepository
func (_mock *MockAttemptRepository) WithTx(tx *gorm.DB) repositories.AttemptRepository {
	ret := _mock.Called(tx)

	if len(ret) == 0 {
		panic("no return value specified for WithTx")
	}

	var r0 repositories.AttemptRepository
	if returnFunc, ok := ret.Get(0).(func(*gorm.DB) repositories.AttemptRepository); ok {
		r0 = returnFunc(tx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(repositories.AttemptRepository)
		}
	}
	return r0
}

// MockAttemptRepository_WithTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WithTx'
type MockAttemptRepository_WithTx_Call struct {
	*mock.Call
}

// WithTx is a helper method to define mock.On call
//   - tx *gorm.DB
func (_e *MockAttemptRepository_Expecter) WithTx(tx any) *MockAttemptRepository_WithTx_Call {
	return &MockAttemptRepository_WithTx_Call{Call: _e.mock.On("WithTx", tx)}
}

func (_c *MockAttemptRepository_WithTx_Call) Run(run func(tx *gorm.DB)) *MockAttemptRepository_WithTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *gorm.DB
		if args[0] != nil {
			arg0 = args[0].(*gorm.DB)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAttemptRepository_WithTx_Call) Return(attemptRepository repositories.AttemptRepository) *MockAttemptRepository_WithTx_Call {
	_c.Call.Return(attemptRepository)
	return _c
}

func (_c *MockAttemptRepository_WithTx_Call) RunAndReturn(run func(tx *gorm.DB) repositories.AttemptRepository) *MockAttemptRepository_WithTx_Call {
	_c.Call.Return(run)
	return _c
}
