// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"engflex-api/internal/database/models"
	"engflex-api/internal/database/repositories"

	mock "github.com/stretchr/testify/mock"
	"gorm.io/gorm"
)

// NewMockLessonRepository creates a new instance of MockLessonRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLessonRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLessonRepository {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockLessonRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockLessonRepository is an autogenerated mock type for the LessonRepository type
type MockLessonRepository struct {
	mock.Mock
}

type MockLessonRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLessonRepository) EXPECT() *MockLessonRepository_Expecter {
	return &MockLessonRepository_Expecter{mock: &_m.Mock}
}

// Count provides a mock function for the type MockLessonRepository
func (_mock *MockLessonRepository) Count(ctx context.Context) (int64, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Count")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (int64, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) int64); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockLessonRepository_Count_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Count'
type MockLessonRepository_Count_Call struct {
	*mock.Call
}

// Count is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockLessonRepository_Expecter) Count(ctx any) *MockLessonRepository_Count_Call {
	return &MockLessonRepository_Count_Call{Call: _e.mock.On("Count", ctx)}
}

func (_c *MockLessonRepository_Count_Call) Run(run func(ctx context.Context)) *MockLessonRepository_Count_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockLessonRepository_Count_Call) Return(n int64, err error) *MockLessonRepository_Count_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockLessonRepository_Count_Call) RunAndReturn(run func(ctx context.Context) (int64, error)) *MockLessonRepository_Count_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function for the type MockLessonRepository
func (_mock *MockLessonRepository) Create(ctx context.Context, lesson *models.Lesson) error {
	ret := _mock.Called(ctx, lesson)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *models.Lesson) error); ok {
		r0 = returnFunc(ctx, lesson)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockLessonRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockLessonRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - lesson *models.Lesson
func (_e *MockLessonRepository_Expecter) Create(ctx any, lesson any) *MockLessonRepository_Create_Call {
	return &MockLessonRepository_Create_Call{Call: _e.mock.On("Create", ctx, lesson)}
}

func (_c *MockLessonRepository_Create_Call) Run(run func(ctx context.Context, lesson *models.Lesson)) *MockLessonRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *models.Lesson
		if args[1] != nil {
			arg1 = args[1].(*models.Lesson)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockLessonRepository_Create_Call) Return(err error) *MockLessonRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockLessonRepository_Create_Call) RunAndReturn(run func(ctx context.Context, lesson *models.Lesson) error) *MockLessonRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockLessonRepository
func (_mock *MockLessonRepository) Delete(ctx context.Context, id string) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockLessonRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockLessonRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockLessonRepository_Expecter) Delete(ctx any, id any) *MockLessonRepository_Delete_Call {
	return &MockLessonRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockLessonRepository_Delete_Call) Run(run func(ctx context.Context, id string)) *MockLessonRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockLessonRepository_Delete_Call) Return(err error) *MockLessonRepository_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockLessonRepository_Delete_Call) RunAndReturn(run func(ctx context.Context, id string) error) *MockLessonRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type MockLessonRepository
func (_mock *MockLessonRepository) GetByID(ctx context.Context, id string) (*models.Lesson, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *models.Lesson
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*models.Lesson, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *models.Lesson); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Lesson)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockLessonRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockLessonRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockLessonRepository_Expecter) GetByID(ctx any, id any) *MockLessonRepository_GetByID_Call {
	return &MockLessonRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockLessonRepository_GetByID_Call) Run(run func(ctx context.Context, id string)) *MockLessonRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockLessonRepository_GetByID_Call) Return(lesson *models.Lesson, err error) *MockLessonRepository_GetByID_Call {
	_c.Call.Return(lesson, err)
	return _c
}

func (_c *MockLessonRepository_GetByID_Call) RunAndReturn(run func(ctx context.Context, id string) (*models.Lesson, error)) *MockLessonRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockLessonRepository
func (_mock *MockLessonRepository) List(ctx context.Context, limit int, offset int) ([]*models.Lesson, error) {
	ret := _mock.Called(ctx, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*models.Lesson
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int) ([]*models.Lesson, error)); ok {
		return returnFunc(ctx, limit, offset)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int) []*models.Lesson); ok {
		r0 = returnFunc(ctx, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Lesson)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, int) error); ok {
		r1 = returnFunc(ctx, limit, offset)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockLessonRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockLessonRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - limit int
//   - offset int
func (_e *MockLessonRepository_Expecter) List(ctx any, limit any, offset any) *MockLessonRepository_List_Call {
	return &MockLessonRepository_List_Call{Call: _e.mock.On("List", ctx, limit, offset)}
}

func (_c *MockLessonRepository_List_Call) Run(run func(ctx context.Context, limit int, offset int)) *MockLessonRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockLessonRepository_List_Call) Return(lessons []*models.Lesson, err error) *MockLessonRepository_List_Call {
	_c.Call.Return(lessons, err)
	return _c
}

func (_c *MockLessonRepository_List_Call) RunAndReturn(run func(ctx context.Context, limit int, offset int) ([]*models.Lesson, error)) *MockLessonRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockLessonRepository
func (_mock *MockLessonRepository) Update(ctx context.Context, lesson *models.Lesson) error {
	ret := _mock.Called(ctx, lesson)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *models.Lesson) error); ok {
		r0 = returnFunc(ctx, lesson)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockLessonRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockLessonRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - lesson *models.Lesson
func (_e *MockLessonRepository_Expecter) Update(ctx any, lesson any) *MockLessonRepository_Update_Call {
	return &MockLessonRepository_Update_Call{Call: _e.mock.On("Update", ctx, lesson)}
}

func (_c *MockLessonRepository_Update_Call) Run(run func(ctx context.Context, lesson *models.Lesson)) *MockLessonRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *models.Lesson
		if args[1] != nil {
			arg1 = args[1].(*models.Lesson)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockLessonRepository_Update_Call) Return(err error) *MockLessonRepository_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockLessonRepository_Update_Call) RunAndReturn(run func(ctx context.Context, lesson *models.Lesson) error) *MockLessonRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// WithTx provides a mock function for the type MockLessonRepository
func (_mock *MockLessonRepository) WithTx(tx *gorm.DB) repositories.LessonRepository {
	ret := _mock.Called(tx)

	if len(ret) == 0 {
		panic("no return value specified for WithTx")
	}

	var r0 repositories.LessonRepository
	if returnFunc, ok := ret.Get(0).(func(*gorm.DB) repositories.LessonRepository); ok {
		r0 = returnFunc(tx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(repositories.LessonRepository)
		}
	}
	return r0
}

// MockLessonRepository_WithTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WithTx'
type MockLessonRepository_WithTx_Call struct {
	*mock.Call
}

// WithTx is a helper method to define mock.On call
//   - tx *gorm.DB
func (_e *MockLessonRepository_Expecter) WithTx(tx any) *MockLessonRepository_WithTx_Call {
	return &MockLessonRepository_WithTx_Call{Call: _e.mock.On("WithTx", tx)}
}

func (_c *MockLessonRepository_WithTx_Call) Run(run func(tx *gorm.DB)) *MockLessonRepository_WithTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *gorm.DB
		if args[0] != nil {
			arg0 = args[0].(*gorm.DB)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockLessonRepository_WithTx_Call) Return(lessonRepository repositories.LessonRepository) *MockLessonRepository_WithTx_Call {
	_c.Call.Return(lessonRepository)
	return _c
}

func (_c *MockLessonRepository_WithTx_Call) RunAndReturn(run func(tx *gorm.DB) repositories.LessonRepository) *MockLessonRepository_WithTx_Call {
	_c.Call.Return(run)
	return _c
}
