// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"engflex-api/internal/database/models"
	"engflex-api/internal/database/repositories"

	mock "github.com/stretchr/testify/mock"
	"gorm.io/gorm"
)

// NewMockScenarioRepository creates a new instance of MockScenarioRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockScenarioRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockScenarioRepository {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockScenarioRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockScenarioRepository is an autogenerated mock type for the ScenarioRepository type
type MockScenarioRepository struct {
	mock.Mock
}

type MockScenarioRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockScenarioRepository) EXPECT() *MockScenarioRepository_Expecter {
	return &MockScenarioRepository_Expecter{mock: &_m.Mock}
}

// Count provides a mock function for the type MockScenarioRepository
func (_mock *MockScenarioRepository) Count(ctx context.Context, topicID *string) (int64, error) {
	ret := _mock.Called(ctx, topicID)

	if len(ret) == 0 {
		panic("no return value specified for Count")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *string) (int64, error)); ok {
		return returnFunc(ctx, topicID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *string) int64); ok {
		r0 = returnFunc(ctx, topicID)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *string) error); ok {
		r1 = returnFunc(ctx, topicID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockScenarioRepository_Count_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Count'
type MockScenarioRepository_Count_Call struct {
	*mock.Call
}

// Count is a helper method to define mock.On call
//   - ctx context.Context
//   - topicID *string
func (_e *MockScenarioRepository_Expecter) Count(ctx any, topicID any) *MockScenarioRepository_Count_Call {
	return &MockScenarioRepository_Count_Call{Call: _e.mock.On("Count", ctx, topicID)}
}

func (_c *MockScenarioRepository_Count_Call) Run(run func(ctx context.Context, topicID *string)) *MockScenarioRepository_Count_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *string
		if args[1] != nil {
			arg1 = args[1].(*string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockScenarioRepository_Count_Call) Return(n int64, err error) *MockScenarioRepository_Count_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockScenarioRepository_Count_Call) RunAndReturn(run func(ctx context.Context, topicID *string) (int64, error)) *MockScenarioRepository_Count_Call {
	_c.Call.Return(run)
	return _c
}

// CountForUser provides a mock function for the type MockScenarioRepository
func (_mock *MockScenarioRepository) CountForUser(ctx context.Context, userID string) (int64, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for CountForUser")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (int64, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) int64); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockScenarioRepository_CountForUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountForUser'
type MockScenarioRepository_CountForUser_Call struct {
	*mock.Call
}

// CountForUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockScenarioRepository_Expecter) CountForUser(ctx any, userID any) *MockScenarioRepository_CountForUser_Call {
	return &MockScenarioRepository_CountForUser_Call{Call: _e.mock.On("CountForUser", ctx, userID)}
}

func (_c *MockScenarioRepository_CountForUser_Call) Run(run func(ctx context.Context, userID string)) *MockScenarioRepository_CountForUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockScenarioRepository_CountForUser_Call) Return(n int64, err error) *MockScenarioRepository_CountForUser_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockScenarioRepository_CountForUser_Call) RunAndReturn(run func(ctx context.Context, userID string) (int64, error)) *MockScenarioRepository_CountForUser_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function for the type MockScenarioRepository
func (_mock *MockScenarioRepository) Create(ctx context.Context, m *models.Scenario) error {
	ret := _mock.Called(ctx, m)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *models.Scenario) error); ok {
		r0 = returnFunc(ctx, m)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockScenarioRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockScenarioRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - m *models.Scenario
func (_e *MockScenarioRepository_Expecter) Create(ctx any, m any) *MockScenarioRepository_Create_Call {
	return &MockScenarioRepository_Create_Call{Call: _e.mock.On("Create", ctx, m)}
}

func (_c *MockScenarioRepository_Create_Call) Run(run func(ctx context.Context, m *models.Scenario)) *MockScenarioRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *models.Scenario
		if args[1] != nil {
			arg1 = args[1].(*models.Scenario)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockScenarioRepository_Create_Call) Return(err error) *MockScenarioRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockScenarioRepository_Create_Call) RunAndReturn(run func(ctx context.Context, m *models.Scenario) error) *MockScenarioRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type MockScenarioRepository
func (_mock *MockScenarioRepository) GetByID(ctx context.Context, id string) (*models.Scenario, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *models.Scenario
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*models.Scenario, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *models.Scenario); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Scenario)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockScenarioRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockScenarioRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockScenarioRepository_Expecter) GetByID(ctx any, id any) *MockScenarioRepository_GetByID_Call {
	return &MockScenarioRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockScenarioRepository_GetByID_Call) Run(run func(ctx context.Context, id string)) *MockScenarioRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockScenarioRepository_GetByID_Call) Return(scenario *models.Scenario, err error) *MockScenarioRepository_GetByID_Call {
	_c.Call.Return(scenario, err)
	return _c
}

func (_c *MockScenarioRepository_GetByID_Call) RunAndReturn(run func(ctx context.Context, id string) (*models.Scenario, error)) *MockScenarioRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetTopicBySlug provides a mock function for the type MockScenarioRepository
func (_mock *MockScenarioRepository) GetTopicBySlug(ctx context.Context, slug string) (*models.ScenarioTopic, error) {
	ret := _mock.Called(ctx, slug)

	if len(ret) == 0 {
		panic("no return value specified for GetTopicBySlug")
	}

	var r0 *models.ScenarioTopic
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*models.ScenarioTopic, error)); ok {
		return returnFunc(ctx, slug)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *models.ScenarioTopic); ok {
		r0 = returnFunc(ctx, slug)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.ScenarioTopic)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, slug)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockScenarioRepository_GetTopicBySlug_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTopicBySlug'
type MockScenarioRepository_GetTopicBySlug_Call struct {
	*mock.Call
}

// GetTopicBySlug is a helper method to define mock.On call
//   - ctx context.Context
//   - slug string
func (_e *MockScenarioRepository_Expecter) GetTopicBySlug(ctx any, slug any) *MockScenarioRepository_GetTopicBySlug_Call {
	return &MockScenarioRepository_GetTopicBySlug_Call{Call: _e.mock.On("GetTopicBySlug", ctx, slug)}
}

func (_c *MockScenarioRepository_GetTopicBySlug_Call) Run(run func(ctx context.Context, slug string)) *MockScenarioRepository_GetTopicBySlug_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockScenarioRepository_GetTopicBySlug_Call) Return(scenarioTopic *models.ScenarioTopic, err error) *MockScenarioRepository_GetTopicBySlug_Call {
	_c.Call.Return(scenarioTopic, err)
	return _c
}

func (_c *MockScenarioRepository_GetTopicBySlug_Call) RunAndReturn(run func(ctx context.Context, slug string) (*models.ScenarioTopic, error)) *MockScenarioRepository_GetTopicBySlug_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockScenarioRepository
func (_mock *MockScenarioRepository) List(ctx context.Context, topicID *string, limit int, offset int) ([]*models.Scenario, error) {
	ret := _mock.Called(ctx, topicID, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*models.Scenario
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *string, int, int) ([]*models.Scenario, error)); ok {
		return returnFunc(ctx, topicID, limit, offset)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *string, int, int) []*models.Scenario); ok {
		r0 = returnFunc(ctx, topicID, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Scenario)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *string, int, int) error); ok {
		r1 = returnFunc(ctx, topicID, limit, offset)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockScenarioRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockScenarioRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - topicID *string
//   - limit int
//   - offset int
func (_e *MockScenarioRepository_Expecter) List(ctx any, topicID any, limit any, offset any) *MockScenarioRepository_List_Call {
	return &MockScenarioRepository_List_Call{Call: _e.mock.On("List", ctx, topicID, limit, offset)}
}

func (_c *MockScenarioRepository_List_Call) Run(run func(ctx context.Context, topicID *string, limit int, offset int)) *MockScenarioRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *string
		if args[1] != nil {
			arg1 = args[1].(*string)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockScenarioRepository_List_Call) Return(scenarios []*models.Scenario, err error) *MockScenarioRepository_List_Call {
	_c.Call.Return(scenarios, err)
	return _c
}

func (_c *MockScenarioRepository_List_Call) RunAndReturn(run func(ctx context.Context, topicID *string, limit int, offset int) ([]*models.Scenario, error)) *MockScenarioRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// ListForUser provides a mock function for the type MockScenarioRepository
func (_mock *MockScenarioRepository) ListForUser(ctx context.Context, userID string, limit int, offset int) ([]*models.Scenario, error) {
	ret := _mock.Called(ctx, userID, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for ListForUser")
	}

	var r0 []*models.Scenario
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int, int) ([]*models.Scenario, error)); ok {
		return returnFunc(ctx, userID, limit, offset)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int, int) []*models.Scenario); ok {
		r0 = returnFunc(ctx, userID, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Scenario)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, int, int) error); ok {
		r1 = returnFunc(ctx, userID, limit, offset)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockScenarioRepository_ListForUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListForUser'
type MockScenarioRepository_ListForUser_Call struct {
	*mock.Call
}

// ListForUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - limit int
//   - offset int
func (_e *MockScenarioRepository_Expecter) ListForUser(ctx any, userID any, limit any, offset any) *MockScenarioRepository_ListForUser_Call {
	return &MockScenarioRepository_ListForUser_Call{Call: _e.mock.On("ListForUser", ctx, userID, limit, offset)}
}

func (_c *MockScenarioRepository_ListForUser_Call) Run(run func(ctx context.Context, userID string, limit int, offset int)) *MockScenarioRepository_ListForUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockScenarioRepository_ListForUser_Call) Return(scenarios []*models.Scenario, err error) *MockScenarioRepository_ListForUser_Call {
	_c.Call.Return(scenarios, err)
	return _c
}

func (_c *MockScenarioRepository_ListForUser_Call) RunAndReturn(run func(ctx context.Context, userID string, limit int, offset int) ([]*models.Scenario, error)) *MockScenarioRepository_ListForUser_Call {
	_c.Call.Return(run)
	return _c
}

// WithTx provides a mock function for the type MockScenarioRepository
func (_mock *MockScenarioRepository) WithTx(tx *gorm.DB) repositories.ScenarioRepository {
	ret := _mock.Called(tx)

	if len(ret) == 0 {
		panic("no return value specified for WithTx")
	}

	var r0 repositories.ScenarioRepository
	if returnFunc, ok := ret.Get(0).(func(*gorm.DB) repositories.ScenarioRepository); ok {
		r0 = returnFunc(tx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(repositories.ScenarioRepository)
		}
	}
	return r0
}

// MockScenarioRepository_WithTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WithTx'
type MockScenarioRepository_WithTx_Call struct {
	*mock.Call
}

// WithTx is a helper method to define mock.On call
//   - tx *gorm.DB
func (_e *MockScenarioRepository_Expecter) WithTx(tx any) *MockScenarioRepository_WithTx_Call {
	return &MockScenarioRepository_WithTx_Call{Call: _e.mock.On("WithTx", tx)}
}

func (_c *MockScenarioRepository_WithTx_Call) Run(run func(tx *gorm.DB)) *MockScenarioRepository_WithTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *gorm.DB
		if args[0] != nil {
			arg0 = args[0].(*gorm.DB)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockScenarioRepository_WithTx_Call) Return(scenarioRepository repositories.ScenarioRepository) *MockScenarioRepository_WithTx_Call {
	_c.Call.Return(scenarioRepository)
	return _c
}

func (_c *MockScenarioRepository_WithTx_Call) RunAndReturn(run func(tx *gorm.DB) repositories.ScenarioRepository) *MockScenarioRepository_WithTx_Call {
	_c.Call.Return(run)
	return _c
}
