// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"engflex-api/internal/common/enums"
	"engflex-api/internal/database/models"
	"engflex-api/internal/database/repositories"

	mock "github.com/stretchr/testify/mock"
	"gorm.io/gorm"
)

// NewMockConversationRepository creates a new instance of MockConversationRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockConversationRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockConversationRepository {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockConversationRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockConversationRepository is an autogenerated mock type for the ConversationRepository type
type MockConversationRepository struct {
	mock.Mock
}

type MockConversationRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockConversationRepository) EXPECT() *MockConversationRepository_Expecter {
	return &MockConversationRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockConversationRepository
func (_mock *MockConversationRepository) Create(ctx context.Context, m *models.Conversation) error {
	ret := _mock.Called(ctx, m)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *models.Conversation) error); ok {
		r0 = returnFunc(ctx, m)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockConversationRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockConversationRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - m *models.Conversation
func (_e *MockConversationRepository_Expecter) Create(ctx any, m any) *MockConversationRepository_Create_Call {
	return &MockConversationRepository_Create_Call{Call: _e.mock.On("Create", ctx, m)}
}

func (_c *MockConversationRepository_Create_Call) Run(run func(ctx context.Context, m *models.Conversation)) *MockConversationRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *models.Conversation
		if args[1] != nil {
			arg1 = args[1].(*models.Conversation)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockConversationRepository_Create_Call) Return(err error) *MockConversationRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockConversationRepository_Create_Call) RunAndReturn(run func(ctx context.Context, m *models.Conversation) error) *MockConversationRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// CreateClosingActive provides a mock function for the type MockConversationRepository
func (_mock *MockConversationRepository) CreateClosingActive(ctx context.Context, m *models.Conversation) error {
	ret := _mock.Called(ctx, m)

	if len(ret) == 0 {
		panic("no return value specified for CreateClosingActive")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *models.Conversation) error); ok {
		r0 = returnFunc(ctx, m)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockConversationRepository_CreateClosingActive_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateClosingActive'
type MockConversationRepository_CreateClosingActive_Call struct {
	*mock.Call
}

// CreateClosingActive is a helper method to define mock.On call
//   - ctx context.Context
//   - m *models.Conversation
func (_e *MockConversationRepository_Expecter) CreateClosingActive(ctx any, m any) *MockConversationRepository_CreateClosingActive_Call {
	return &MockConversationRepository_CreateClosingActive_Call{Call: _e.mock.On("CreateClosingActive", ctx, m)}
}

func (_c *MockConversationRepository_CreateClosingActive_Call) Run(run func(ctx context.Context, m *models.Conversation)) *MockConversationRepository_CreateClosingActive_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *models.Conversation
		if args[1] != nil {
			arg1 = args[1].(*models.Conversation)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockConversationRepository_CreateClosingActive_Call) Return(err error) *MockConversationRepository_CreateClosingActive_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockConversationRepository_CreateClosingActive_Call) RunAndReturn(run func(ctx context.Context, m *models.Conversation) error) *MockConversationRepository_CreateClosingActive_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type MockConversationRepository
func (_mock *MockConversationRepository) GetByID(ctx context.Context, id string) (*models.Conversation, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *models.Conversation
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*models.Conversation, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *models.Conversation); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Conversation)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockConversationRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockConversationRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockConversationRepository_Expecter) GetByID(ctx any, id any) *MockConversationRepository_GetByID_Call {
	return &MockConversationRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockConversationRepository_GetByID_Call) Run(run func(ctx context.Context, id string)) *MockConversationRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockConversationRepository_GetByID_Call) Return(conversation *models.Conversation, err error) *MockConversationRepository_GetByID_Call {
	_c.Call.Return(conversation, err)
	return _c
}

func (_c *MockConversationRepository_GetByID_Call) RunAndReturn(run func(ctx context.Context, id string) (*models.Conversation, error)) *MockConversationRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// SetEnded provides a mock function for the type MockConversationRepository
func (_mock *MockConversationRepository) SetEnded(ctx context.Context, id string, durationSec *int) (int64, error) {
	ret := _mock.Called(ctx, id, durationSec)

	if len(ret) == 0 {
		panic("no return value specified for SetEnded")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *int) (int64, error)); ok {
		return returnFunc(ctx, id, durationSec)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *int) int64); ok {
		r0 = returnFunc(ctx, id, durationSec)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, *int) error); ok {
		r1 = returnFunc(ctx, id, durationSec)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockConversationRepository_SetEnded_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetEnded'
type MockConversationRepository_SetEnded_Call struct {
	*mock.Call
}

// SetEnded is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - durationSec *int
func (_e *MockConversationRepository_Expecter) SetEnded(ctx any, id any, durationSec any) *MockConversationRepository_SetEnded_Call {
	return &MockConversationRepository_SetEnded_Call{Call: _e.mock.On("SetEnded", ctx, id, durationSec)}
}

func (_c *MockConversationRepository_SetEnded_Call) Run(run func(ctx context.Context, id string, durationSec *int)) *MockConversationRepository_SetEnded_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *int
		if args[2] != nil {
			arg2 = args[2].(*int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockConversationRepository_SetEnded_Call) Return(n int64, err error) *MockConversationRepository_SetEnded_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockConversationRepository_SetEnded_Call) RunAndReturn(run func(ctx context.Context, id string, durationSec *int) (int64, error)) *MockConversationRepository_SetEnded_Call {
	_c.Call.Return(run)
	return _c
}

// SetSpeechStart provides a mock function for the type MockConversationRepository
func (_mock *MockConversationRepository) SetSpeechStart(ctx context.Context, id string, speechSessionID string, startResponse []byte) (int64, error) {
	ret := _mock.Called(ctx, id, speechSessionID, startResponse)

	if len(ret) == 0 {
		panic("no return value specified for SetSpeechStart")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, []byte) (int64, error)); ok {
		return returnFunc(ctx, id, speechSessionID, startResponse)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, []byte) int64); ok {
		r0 = returnFunc(ctx, id, speechSessionID, startResponse)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, []byte) error); ok {
		r1 = returnFunc(ctx, id, speechSessionID, startResponse)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockConversationRepository_SetSpeechStart_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetSpeechStart'
type MockConversationRepository_SetSpeechStart_Call struct {
	*mock.Call
}

// SetSpeechStart is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - speechSessionID string
//   - startResponse []byte
func (_e *MockConversationRepository_Expecter) SetSpeechStart(ctx any, id any, speechSessionID any, startResponse any) *MockConversationRepository_SetSpeechStart_Call {
	return &MockConversationRepository_SetSpeechStart_Call{Call: _e.mock.On("SetSpeechStart", ctx, id, speechSessionID, startResponse)}
}

func (_c *MockConversationRepository_SetSpeechStart_Call) Run(run func(ctx context.Context, id string, speechSessionID string, startResponse []byte)) *MockConversationRepository_SetSpeechStart_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 []byte
		if args[3] != nil {
			arg3 = args[3].([]byte)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockConversationRepository_SetSpeechStart_Call) Return(n int64, err error) *MockConversationRepository_SetSpeechStart_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockConversationRepository_SetSpeechStart_Call) RunAndReturn(run func(ctx context.Context, id string, speechSessionID string, startResponse []byte) (int64, error)) *MockConversationRepository_SetSpeechStart_Call {
	_c.Call.Return(run)
	return _c
}

// SetStatus provides a mock function for the type MockConversationRepository
func (_mock *MockConversationRepository) SetStatus(ctx context.Context, id string, from enums.ConversationStatus, to enums.ConversationStatus) (int64, error) {
	ret := _mock.Called(ctx, id, from, to)

	if len(ret) == 0 {
		panic("no return value specified for SetStatus")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, enums.ConversationStatus, enums.ConversationStatus) (int64, error)); ok {
		return returnFunc(ctx, id, from, to)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, enums.ConversationStatus, enums.ConversationStatus) int64); ok {
		r0 = returnFunc(ctx, id, from, to)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, enums.ConversationStatus, enums.ConversationStatus) error); ok {
		r1 = returnFunc(ctx, id, from, to)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockConversationRepository_SetStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetStatus'
type MockConversationRepository_SetStatus_Call struct {
	*mock.Call
}

// SetStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - from enums.ConversationStatus
//   - to enums.ConversationStatus
func (_e *MockConversationRepository_Expecter) SetStatus(ctx any, id any, from any, to any) *MockConversationRepository_SetStatus_Call {
	return &MockConversationRepository_SetStatus_Call{Call: _e.mock.On("SetStatus", ctx, id, from, to)}
}

func (_c *MockConversationRepository_SetStatus_Call) Run(run func(ctx context.Context, id string, from enums.ConversationStatus, to enums.ConversationStatus)) *MockConversationRepository_SetStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 enums.ConversationStatus
		if args[2] != nil {
			arg2 = args[2].(enums.ConversationStatus)
		}
		var arg3 enums.ConversationStatus
		if args[3] != nil {
			arg3 = args[3].(enums.ConversationStatus)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockConversationRepository_SetStatus_Call) Return(n int64, err error) *MockConversationRepository_SetStatus_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockConversationRepository_SetStatus_Call) RunAndReturn(run func(ctx context.Context, id string, from enums.ConversationStatus, to enums.ConversationStatus) (int64, error)) *MockConversationRepository_SetStatus_Call {
	_c.Call.Return(run)
	return _c
}

// WithTx provides a mock function for the type MockConversationRepository
func (_mock *MockConversationRepository) WithTx(tx *gorm.DB) repositories.ConversationRepository {
	ret := _mock.Called(tx)

	if len(ret) == 0 {
		panic("no return value specified for WithTx")
	}

	var r0 repositories.ConversationRepository
	if returnFunc, ok := ret.Get(0).(func(*gorm.DB) repositories.ConversationRepository); ok {
		r0 = returnFunc(tx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(repositories.ConversationRepository)
		}
	}
	return r0
}

// MockConversationRepository_WithTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WithTx'
type MockConversationRepository_WithTx_Call struct {
	*mock.Call
}

// WithTx is a helper method to define mock.On call
//   - tx *gorm.DB
func (_e *MockConversationRepository_Expecter) WithTx(tx any) *MockConversationRepository_WithTx_Call {
	return &MockConversationRepository_WithTx_Call{Call: _e.mock.On("WithTx", tx)}
}

func (_c *MockConversationRepository_WithTx_Call) Run(run func(tx *gorm.DB)) *MockConversationRepository_WithTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *gorm.DB
		if args[0] != nil {
			arg0 = args[0].(*gorm.DB)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockConversationRepository_WithTx_Call) Return(conversationRepository repositories.ConversationRepository) *MockConversationRepository_WithTx_Call {
	_c.Call.Return(conversationRepository)
	return _c
}

func (_c *MockConversationRepository_WithTx_Call) RunAndReturn(run func(tx *gorm.DB) repositories.ConversationRepository) *MockConversationRepository_WithTx_Call {
	_c.Call.Return(run)
	return _c
}
