// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"engflex-api/internal/database/models"
	"engflex-api/internal/database/repositories"

	mock "github.com/stretchr/testify/mock"
	"gorm.io/gorm"
)

// NewMockLessonRepository creates a new instance of MockLessonRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLessonRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLessonRepository {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockLessonRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockLessonRepository is an autogenerated mock type for the LessonRepository type
type MockLessonRepository struct {
	mock.Mock
}

type MockLessonRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLessonRepository) EXPECT() *MockLessonRepository_Expecter {
	return &MockLessonRepository_Expecter{mock: &_m.Mock}
}

// GetByID provides a mock function for the type MockLessonRepository
func (_mock *MockLessonRepository) GetByID(ctx context.Context, id string) (*models.Lesson, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *models.Lesson
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*models.Lesson, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *models.Lesson); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Lesson)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockLessonRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockLessonRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockLessonRepository_Expecter) GetByID(ctx any, id any) *MockLessonRepository_GetByID_Call {
	return &MockLessonRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockLessonRepository_GetByID_Call) Run(run func(ctx context.Context, id string)) *MockLessonRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockLessonRepository_GetByID_Call) Return(lesson *models.Lesson, err error) *MockLessonRepository_GetByID_Call {
	_c.Call.Return(lesson, err)
	return _c
}

func (_c *MockLessonRepository_GetByID_Call) RunAndReturn(run func(ctx context.Context, id string) (*models.Lesson, error)) *MockLessonRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetDetail provides a mock function for the type MockLessonRepository
func (_mock *MockLessonRepository) GetDetail(ctx context.Context, id string) (*models.Lesson, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetDetail")
	}

	var r0 *models.Lesson
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*models.Lesson, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *models.Lesson); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Lesson)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockLessonRepository_GetDetail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDetail'
type MockLessonRepository_GetDetail_Call struct {
	*mock.Call
}

// GetDetail is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockLessonRepository_Expecter) GetDetail(ctx any, id any) *MockLessonRepository_GetDetail_Call {
	return &MockLessonRepository_GetDetail_Call{Call: _e.mock.On("GetDetail", ctx, id)}
}

func (_c *MockLessonRepository_GetDetail_Call) Run(run func(ctx context.Context, id string)) *MockLessonRepository_GetDetail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockLessonRepository_GetDetail_Call) Return(lesson *models.Lesson, err error) *MockLessonRepository_GetDetail_Call {
	_c.Call.Return(lesson, err)
	return _c
}

func (_c *MockLessonRepository_GetDetail_Call) RunAndReturn(run func(ctx context.Context, id string) (*models.Lesson, error)) *MockLessonRepository_GetDetail_Call {
	_c.Call.Return(run)
	return _c
}

// GetDetailBySlug provides a mock function for the type MockLessonRepository
func (_mock *MockLessonRepository) GetDetailBySlug(ctx context.Context, slug string) (*models.Lesson, error) {
	ret := _mock.Called(ctx, slug)

	if len(ret) == 0 {
		panic("no return value specified for GetDetailBySlug")
	}

	var r0 *models.Lesson
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*models.Lesson, error)); ok {
		return returnFunc(ctx, slug)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *models.Lesson); ok {
		r0 = returnFunc(ctx, slug)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Lesson)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, slug)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockLessonRepository_GetDetailBySlug_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDetailBySlug'
type MockLessonRepository_GetDetailBySlug_Call struct {
	*mock.Call
}

// GetDetailBySlug is a helper method to define mock.On call
//   - ctx context.Context
//   - slug string
func (_e *MockLessonRepository_Expecter) GetDetailBySlug(ctx any, slug any) *MockLessonRepository_GetDetailBySlug_Call {
	return &MockLessonRepository_GetDetailBySlug_Call{Call: _e.mock.On("GetDetailBySlug", ctx, slug)}
}

func (_c *MockLessonRepository_GetDetailBySlug_Call) Run(run func(ctx context.Context, slug string)) *MockLessonRepository_GetDetailBySlug_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockLessonRepository_GetDetailBySlug_Call) Return(lesson *models.Lesson, err error) *MockLessonRepository_GetDetailBySlug_Call {
	_c.Call.Return(lesson, err)
	return _c
}

func (_c *MockLessonRepository_GetDetailBySlug_Call) RunAndReturn(run func(ctx context.Context, slug string) (*models.Lesson, error)) *MockLessonRepository_GetDetailBySlug_Call {
	_c.Call.Return(run)
	return _c
}

// WithTx provides a mock function for the type MockLessonRepository
func (_mock *MockLessonRepository) WithTx(tx *gorm.DB) repositories.LessonRepository {
	ret := _mock.Called(tx)

	if len(ret) == 0 {
		panic("no return value specified for WithTx")
	}

	var r0 repositories.LessonRepository
	if returnFunc, ok := ret.Get(0).(func(*gorm.DB) repositories.LessonRepository); ok {
		r0 = returnFunc(tx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(repositories.LessonRepository)
		}
	}
	return r0
}

// MockLessonRepository_WithTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WithTx'
type MockLessonRepository_WithTx_Call struct {
	*mock.Call
}

// WithTx is a helper method to define mock.On call
//   - tx *gorm.DB
func (_e *MockLessonRepository_Expecter) WithTx(tx any) *MockLessonRepository_WithTx_Call {
	return &MockLessonRepository_WithTx_Call{Call: _e.mock.On("WithTx", tx)}
}

func (_c *MockLessonRepository_WithTx_Call) Run(run func(tx *gorm.DB)) *MockLessonRepository_WithTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *gorm.DB
		if args[0] != nil {
			arg0 = args[0].(*gorm.DB)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockLessonRepository_WithTx_Call) Return(lessonRepository repositories.LessonRepository) *MockLessonRepository_WithTx_Call {
	_c.Call.Return(lessonRepository)
	return _c
}

func (_c *MockLessonRepository_WithTx_Call) RunAndReturn(run func(tx *gorm.DB) repositories.LessonRepository) *MockLessonRepository_WithTx_Call {
	_c.Call.Return(run)
	return _c
}
