// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"engflex-api/internal/database/repositories"

	mock "github.com/stretchr/testify/mock"
	"gorm.io/gorm"
)

// NewMockLessonRepository creates a new instance of MockLessonRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLessonRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLessonRepository {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockLessonRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockLessonRepository is an autogenerated mock type for the LessonRepository type
type MockLessonRepository struct {
	mock.Mock
}

type MockLessonRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLessonRepository) EXPECT() *MockLessonRepository_Expecter {
	return &MockLessonRepository_Expecter{mock: &_m.Mock}
}

// WithTx provides a mock function for the type MockLessonRepository
func (_mock *MockLessonRepository) WithTx(tx *gorm.DB) repositories.LessonRepository {
	ret := _mock.Called(tx)

	if len(ret) == 0 {
		panic("no return value specified for WithTx")
	}

	var r0 repositories.LessonRepository
	if returnFunc, ok := ret.Get(0).(func(*gorm.DB) repositories.LessonRepository); ok {
		r0 = returnFunc(tx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(repositories.LessonRepository)
		}
	}
	return r0
}

// MockLessonRepository_WithTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WithTx'
type MockLessonRepository_WithTx_Call struct {
	*mock.Call
}

// WithTx is a helper method to define mock.On call
//   - tx *gorm.DB
func (_e *MockLessonRepository_Expecter) WithTx(tx any) *MockLessonRepository_WithTx_Call {
	return &MockLessonRepository_WithTx_Call{Call: _e.mock.On("WithTx", tx)}
}

func (_c *MockLessonRepository_WithTx_Call) Run(run func(tx *gorm.DB)) *MockLessonRepository_WithTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *gorm.DB
		if args[0] != nil {
			arg0 = args[0].(*gorm.DB)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockLessonRepository_WithTx_Call) Return(lessonRepository repositories.LessonRepository) *MockLessonRepository_WithTx_Call {
	_c.Call.Return(lessonRepository)
	return _c
}

func (_c *MockLessonRepository_WithTx_Call) RunAndReturn(run func(tx *gorm.DB) repositories.LessonRepository) *MockLessonRepository_WithTx_Call {
	_c.Call.Return(run)
	return _c
}
