// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"engflex-api/internal/database/repositories"

	mock "github.com/stretchr/testify/mock"
	"gorm.io/gorm"
)

// NewMockUserProfileRepository creates a new instance of MockUserProfileRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserProfileRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserProfileRepository {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockUserProfileRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockUserProfileRepository is an autogenerated mock type for the UserProfileRepository type
type MockUserProfileRepository struct {
	mock.Mock
}

type MockUserProfileRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserProfileRepository) EXPECT() *MockUserProfileRepository_Expecter {
	return &MockUserProfileRepository_Expecter{mock: &_m.Mock}
}

// WithTx provides a mock function for the type MockUserProfileRepository
func (_mock *MockUserProfileRepository) WithTx(tx *gorm.DB) repositories.UserProfileRepository {
	ret := _mock.Called(tx)

	if len(ret) == 0 {
		panic("no return value specified for WithTx")
	}

	var r0 repositories.UserProfileRepository
	if returnFunc, ok := ret.Get(0).(func(*gorm.DB) repositories.UserProfileRepository); ok {
		r0 = returnFunc(tx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(repositories.UserProfileRepository)
		}
	}
	return r0
}

// MockUserProfileRepository_WithTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WithTx'
type MockUserProfileRepository_WithTx_Call struct {
	*mock.Call
}

// WithTx is a helper method to define mock.On call
//   - tx *gorm.DB
func (_e *MockUserProfileRepository_Expecter) WithTx(tx any) *MockUserProfileRepository_WithTx_Call {
	return &MockUserProfileRepository_WithTx_Call{Call: _e.mock.On("WithTx", tx)}
}

func (_c *MockUserProfileRepository_WithTx_Call) Run(run func(tx *gorm.DB)) *MockUserProfileRepository_WithTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *gorm.DB
		if args[0] != nil {
			arg0 = args[0].(*gorm.DB)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockUserProfileRepository_WithTx_Call) Return(userProfileRepository repositories.UserProfileRepository) *MockUserProfileRepository_WithTx_Call {
	_c.Call.Return(userProfileRepository)
	return _c
}

func (_c *MockUserProfileRepository_WithTx_Call) RunAndReturn(run func(tx *gorm.DB) repositories.UserProfileRepository) *MockUserProfileRepository_WithTx_Call {
	_c.Call.Return(run)
	return _c
}
