// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"engflex-api/internal/database/repositories"

	mock "github.com/stretchr/testify/mock"
	"gorm.io/gorm"
)

// NewMockLessonCategoryRepository creates a new instance of MockLessonCategoryRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLessonCategoryRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLessonCategoryRepository {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockLessonCategoryRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockLessonCategoryRepository is an autogenerated mock type for the LessonCategoryRepository type
type MockLessonCategoryRepository struct {
	mock.Mock
}

type MockLessonCategoryRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLessonCategoryRepository) EXPECT() *MockLessonCategoryRepository_Expecter {
	return &MockLessonCategoryRepository_Expecter{mock: &_m.Mock}
}

// WithTx provides a mock function for the type MockLessonCategoryRepository
func (_mock *MockLessonCategoryRepository) WithTx(tx *gorm.DB) repositories.LessonCategoryRepository {
	ret := _mock.Called(tx)

	if len(ret) == 0 {
		panic("no return value specified for WithTx")
	}

	var r0 repositories.LessonCategoryRepository
	if returnFunc, ok := ret.Get(0).(func(*gorm.DB) repositories.LessonCategoryRepository); ok {
		r0 = returnFunc(tx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(repositories.LessonCategoryRepository)
		}
	}
	return r0
}

// MockLessonCategoryRepository_WithTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WithTx'
type MockLessonCategoryRepository_WithTx_Call struct {
	*mock.Call
}

// WithTx is a helper method to define mock.On call
//   - tx *gorm.DB
func (_e *MockLessonCategoryRepository_Expecter) WithTx(tx any) *MockLessonCategoryRepository_WithTx_Call {
	return &MockLessonCategoryRepository_WithTx_Call{Call: _e.mock.On("WithTx", tx)}
}

func (_c *MockLessonCategoryRepository_WithTx_Call) Run(run func(tx *gorm.DB)) *MockLessonCategoryRepository_WithTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *gorm.DB
		if args[0] != nil {
			arg0 = args[0].(*gorm.DB)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockLessonCategoryRepository_WithTx_Call) Return(lessonCategoryRepository repositories.LessonCategoryRepository) *MockLessonCategoryRepository_WithTx_Call {
	_c.Call.Return(lessonCategoryRepository)
	return _c
}

func (_c *MockLessonCategoryRepository_WithTx_Call) RunAndReturn(run func(tx *gorm.DB) repositories.LessonCategoryRepository) *MockLessonCategoryRepository_WithTx_Call {
	_c.Call.Return(run)
	return _c
}
