// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"engflex-api/internal/common/enums"
	"engflex-api/internal/database/models"
	"engflex-api/internal/database/repositories"

	mock "github.com/stretchr/testify/mock"
	"gorm.io/gorm"
)

// NewMockLessonSectionRepository creates a new instance of MockLessonSectionRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLessonSectionRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLessonSectionRepository {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockLessonSectionRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockLessonSectionRepository is an autogenerated mock type for the LessonSectionRepository type
type MockLessonSectionRepository struct {
	mock.Mock
}

type MockLessonSectionRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLessonSectionRepository) EXPECT() *MockLessonSectionRepository_Expecter {
	return &MockLessonSectionRepository_Expecter{mock: &_m.Mock}
}

// GetByID provides a mock function for the type MockLessonSectionRepository
func (_mock *MockLessonSectionRepository) GetByID(ctx context.Context, id string) (*models.LessonSection, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *models.LessonSection
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*models.LessonSection, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *models.LessonSection); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.LessonSection)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockLessonSectionRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockLessonSectionRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockLessonSectionRepository_Expecter) GetByID(ctx any, id any) *MockLessonSectionRepository_GetByID_Call {
	return &MockLessonSectionRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockLessonSectionRepository_GetByID_Call) Run(run func(ctx context.Context, id string)) *MockLessonSectionRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockLessonSectionRepository_GetByID_Call) Return(lessonSection *models.LessonSection, err error) *MockLessonSectionRepository_GetByID_Call {
	_c.Call.Return(lessonSection, err)
	return _c
}

func (_c *MockLessonSectionRepository_GetByID_Call) RunAndReturn(run func(ctx context.Context, id string) (*models.LessonSection, error)) *MockLessonSectionRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockLessonSectionRepository
func (_mock *MockLessonSectionRepository) List(ctx context.Context) ([]*models.LessonSection, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*models.LessonSection
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]*models.LessonSection, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []*models.LessonSection); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.LessonSection)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockLessonSectionRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockLessonSectionRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockLessonSectionRepository_Expecter) List(ctx any) *MockLessonSectionRepository_List_Call {
	return &MockLessonSectionRepository_List_Call{Call: _e.mock.On("List", ctx)}
}

func (_c *MockLessonSectionRepository_List_Call) Run(run func(ctx context.Context)) *MockLessonSectionRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockLessonSectionRepository_List_Call) Return(lessonSections []*models.LessonSection, err error) *MockLessonSectionRepository_List_Call {
	_c.Call.Return(lessonSections, err)
	return _c
}

func (_c *MockLessonSectionRepository_List_Call) RunAndReturn(run func(ctx context.Context) ([]*models.LessonSection, error)) *MockLessonSectionRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// ListWithUnits provides a mock function for the type MockLessonSectionRepository
func (_mock *MockLessonSectionRepository) ListWithUnits(ctx context.Context, level enums.CEFR) ([]*models.LessonSection, error) {
	ret := _mock.Called(ctx, level)

	if len(ret) == 0 {
		panic("no return value specified for ListWithUnits")
	}

	var r0 []*models.LessonSection
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, enums.CEFR) ([]*models.LessonSection, error)); ok {
		return returnFunc(ctx, level)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, enums.CEFR) []*models.LessonSection); ok {
		r0 = returnFunc(ctx, level)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.LessonSection)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, enums.CEFR) error); ok {
		r1 = returnFunc(ctx, level)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockLessonSectionRepository_ListWithUnits_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListWithUnits'
type MockLessonSectionRepository_ListWithUnits_Call struct {
	*mock.Call
}

// ListWithUnits is a helper method to define mock.On call
//   - ctx context.Context
//   - level enums.CEFR
func (_e *MockLessonSectionRepository_Expecter) ListWithUnits(ctx any, level any) *MockLessonSectionRepository_ListWithUnits_Call {
	return &MockLessonSectionRepository_ListWithUnits_Call{Call: _e.mock.On("ListWithUnits", ctx, level)}
}

func (_c *MockLessonSectionRepository_ListWithUnits_Call) Run(run func(ctx context.Context, level enums.CEFR)) *MockLessonSectionRepository_ListWithUnits_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 enums.CEFR
		if args[1] != nil {
			arg1 = args[1].(enums.CEFR)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockLessonSectionRepository_ListWithUnits_Call) Return(lessonSections []*models.LessonSection, err error) *MockLessonSectionRepository_ListWithUnits_Call {
	_c.Call.Return(lessonSections, err)
	return _c
}

func (_c *MockLessonSectionRepository_ListWithUnits_Call) RunAndReturn(run func(ctx context.Context, level enums.CEFR) ([]*models.LessonSection, error)) *MockLessonSectionRepository_ListWithUnits_Call {
	_c.Call.Return(run)
	return _c
}

// WithTx provides a mock function for the type MockLessonSectionRepository
func (_mock *MockLessonSectionRepository) WithTx(tx *gorm.DB) repositories.LessonSectionRepository {
	ret := _mock.Called(tx)

	if len(ret) == 0 {
		panic("no return value specified for WithTx")
	}

	var r0 repositories.LessonSectionRepository
	if returnFunc, ok := ret.Get(0).(func(*gorm.DB) repositories.LessonSectionRepository); ok {
		r0 = returnFunc(tx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(repositories.LessonSectionRepository)
		}
	}
	return r0
}

// MockLessonSectionRepository_WithTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WithTx'
type MockLessonSectionRepository_WithTx_Call struct {
	*mock.Call
}

// WithTx is a helper method to define mock.On call
//   - tx *gorm.DB
func (_e *MockLessonSectionRepository_Expecter) WithTx(tx any) *MockLessonSectionRepository_WithTx_Call {
	return &MockLessonSectionRepository_WithTx_Call{Call: _e.mock.On("WithTx", tx)}
}

func (_c *MockLessonSectionRepository_WithTx_Call) Run(run func(tx *gorm.DB)) *MockLessonSectionRepository_WithTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *gorm.DB
		if args[0] != nil {
			arg0 = args[0].(*gorm.DB)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockLessonSectionRepository_WithTx_Call) Return(lessonSectionRepository repositories.LessonSectionRepository) *MockLessonSectionRepository_WithTx_Call {
	_c.Call.Return(lessonSectionRepository)
	return _c
}

func (_c *MockLessonSectionRepository_WithTx_Call) RunAndReturn(run func(tx *gorm.DB) repositories.LessonSectionRepository) *MockLessonSectionRepository_WithTx_Call {
	_c.Call.Return(run)
	return _c
}
