// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"engflex-api/internal/database/models"
	"engflex-api/internal/database/repositories"

	mock "github.com/stretchr/testify/mock"
	"gorm.io/gorm"
)

// NewMockVocabularyCategoryRepository creates a new instance of MockVocabularyCategoryRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockVocabularyCategoryRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockVocabularyCategoryRepository {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockVocabularyCategoryRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockVocabularyCategoryRepository is an autogenerated mock type for the VocabularyCategoryRepository type
type MockVocabularyCategoryRepository struct {
	mock.Mock
}

type MockVocabularyCategoryRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockVocabularyCategoryRepository) EXPECT() *MockVocabularyCategoryRepository_Expecter {
	return &MockVocabularyCategoryRepository_Expecter{mock: &_m.Mock}
}

// Count provides a mock function for the type MockVocabularyCategoryRepository
func (_mock *MockVocabularyCategoryRepository) Count(ctx context.Context) (int64, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Count")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (int64, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) int64); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockVocabularyCategoryRepository_Count_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Count'
type MockVocabularyCategoryRepository_Count_Call struct {
	*mock.Call
}

// Count is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockVocabularyCategoryRepository_Expecter) Count(ctx any) *MockVocabularyCategoryRepository_Count_Call {
	return &MockVocabularyCategoryRepository_Count_Call{Call: _e.mock.On("Count", ctx)}
}

func (_c *MockVocabularyCategoryRepository_Count_Call) Run(run func(ctx context.Context)) *MockVocabularyCategoryRepository_Count_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockVocabularyCategoryRepository_Count_Call) Return(n int64, err error) *MockVocabularyCategoryRepository_Count_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockVocabularyCategoryRepository_Count_Call) RunAndReturn(run func(ctx context.Context) (int64, error)) *MockVocabularyCategoryRepository_Count_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function for the type MockVocabularyCategoryRepository
func (_mock *MockVocabularyCategoryRepository) Create(ctx context.Context, category *models.VocabularyCategory) error {
	ret := _mock.Called(ctx, category)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *models.VocabularyCategory) error); ok {
		r0 = returnFunc(ctx, category)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockVocabularyCategoryRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockVocabularyCategoryRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - category *models.VocabularyCategory
func (_e *MockVocabularyCategoryRepository_Expecter) Create(ctx any, category any) *MockVocabularyCategoryRepository_Create_Call {
	return &MockVocabularyCategoryRepository_Create_Call{Call: _e.mock.On("Create", ctx, category)}
}

func (_c *MockVocabularyCategoryRepository_Create_Call) Run(run func(ctx context.Context, category *models.VocabularyCategory)) *MockVocabularyCategoryRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *models.VocabularyCategory
		if args[1] != nil {
			arg1 = args[1].(*models.VocabularyCategory)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockVocabularyCategoryRepository_Create_Call) Return(err error) *MockVocabularyCategoryRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockVocabularyCategoryRepository_Create_Call) RunAndReturn(run func(ctx context.Context, category *models.VocabularyCategory) error) *MockVocabularyCategoryRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockVocabularyCategoryRepository
func (_mock *MockVocabularyCategoryRepository) Delete(ctx context.Context, id string) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockVocabularyCategoryRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockVocabularyCategoryRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockVocabularyCategoryRepository_Expecter) Delete(ctx any, id any) *MockVocabularyCategoryRepository_Delete_Call {
	return &MockVocabularyCategoryRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockVocabularyCategoryRepository_Delete_Call) Run(run func(ctx context.Context, id string)) *MockVocabularyCategoryRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockVocabularyCategoryRepository_Delete_Call) Return(err error) *MockVocabularyCategoryRepository_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockVocabularyCategoryRepository_Delete_Call) RunAndReturn(run func(ctx context.Context, id string) error) *MockVocabularyCategoryRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type MockVocabularyCategoryRepository
func (_mock *MockVocabularyCategoryRepository) GetByID(ctx context.Context, id string) (*models.VocabularyCategory, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *models.VocabularyCategory
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*models.VocabularyCategory, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *models.VocabularyCategory); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.VocabularyCategory)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockVocabularyCategoryRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockVocabularyCategoryRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockVocabularyCategoryRepository_Expecter) GetByID(ctx any, id any) *MockVocabularyCategoryRepository_GetByID_Call {
	return &MockVocabularyCategoryRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockVocabularyCategoryRepository_GetByID_Call) Run(run func(ctx context.Context, id string)) *MockVocabularyCategoryRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockVocabularyCategoryRepository_GetByID_Call) Return(vocabularyCategory *models.VocabularyCategory, err error) *MockVocabularyCategoryRepository_GetByID_Call {
	_c.Call.Return(vocabularyCategory, err)
	return _c
}

func (_c *MockVocabularyCategoryRepository_GetByID_Call) RunAndReturn(run func(ctx context.Context, id string) (*models.VocabularyCategory, error)) *MockVocabularyCategoryRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockVocabularyCategoryRepository
func (_mock *MockVocabularyCategoryRepository) List(ctx context.Context, limit int, offset int) ([]*models.VocabularyCategory, error) {
	ret := _mock.Called(ctx, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*models.VocabularyCategory
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int) ([]*models.VocabularyCategory, error)); ok {
		return returnFunc(ctx, limit, offset)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int) []*models.VocabularyCategory); ok {
		r0 = returnFunc(ctx, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.VocabularyCategory)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, int) error); ok {
		r1 = returnFunc(ctx, limit, offset)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockVocabularyCategoryRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockVocabularyCategoryRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - limit int
//   - offset int
func (_e *MockVocabularyCategoryRepository_Expecter) List(ctx any, limit any, offset any) *MockVocabularyCategoryRepository_List_Call {
	return &MockVocabularyCategoryRepository_List_Call{Call: _e.mock.On("List", ctx, limit, offset)}
}

func (_c *MockVocabularyCategoryRepository_List_Call) Run(run func(ctx context.Context, limit int, offset int)) *MockVocabularyCategoryRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockVocabularyCategoryRepository_List_Call) Return(vocabularyCategorys []*models.VocabularyCategory, err error) *MockVocabularyCategoryRepository_List_Call {
	_c.Call.Return(vocabularyCategorys, err)
	return _c
}

func (_c *MockVocabularyCategoryRepository_List_Call) RunAndReturn(run func(ctx context.Context, limit int, offset int) ([]*models.VocabularyCategory, error)) *MockVocabularyCategoryRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockVocabularyCategoryRepository
func (_mock *MockVocabularyCategoryRepository) Update(ctx context.Context, category *models.VocabularyCategory) error {
	ret := _mock.Called(ctx, category)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *models.VocabularyCategory) error); ok {
		r0 = returnFunc(ctx, category)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockVocabularyCategoryRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockVocabularyCategoryRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - category *models.VocabularyCategory
func (_e *MockVocabularyCategoryRepository_Expecter) Update(ctx any, category any) *MockVocabularyCategoryRepository_Update_Call {
	return &MockVocabularyCategoryRepository_Update_Call{Call: _e.mock.On("Update", ctx, category)}
}

func (_c *MockVocabularyCategoryRepository_Update_Call) Run(run func(ctx context.Context, category *models.VocabularyCategory)) *MockVocabularyCategoryRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *models.VocabularyCategory
		if args[1] != nil {
			arg1 = args[1].(*models.VocabularyCategory)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockVocabularyCategoryRepository_Update_Call) Return(err error) *MockVocabularyCategoryRepository_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockVocabularyCategoryRepository_Update_Call) RunAndReturn(run func(ctx context.Context, category *models.VocabularyCategory) error) *MockVocabularyCategoryRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// WithTx provides a mock function for the type MockVocabularyCategoryRepository
func (_mock *MockVocabularyCategoryRepository) WithTx(tx *gorm.DB) repositories.VocabularyCategoryRepository {
	ret := _mock.Called(tx)

	if len(ret) == 0 {
		panic("no return value specified for WithTx")
	}

	var r0 repositories.VocabularyCategoryRepository
	if returnFunc, ok := ret.Get(0).(func(*gorm.DB) repositories.VocabularyCategoryRepository); ok {
		r0 = returnFunc(tx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(repositories.VocabularyCategoryRepository)
		}
	}
	return r0
}

// MockVocabularyCategoryRepository_WithTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WithTx'
type MockVocabularyCategoryRepository_WithTx_Call struct {
	*mock.Call
}

// WithTx is a helper method to define mock.On call
//   - tx *gorm.DB
func (_e *MockVocabularyCategoryRepository_Expecter) WithTx(tx any) *MockVocabularyCategoryRepository_WithTx_Call {
	return &MockVocabularyCategoryRepository_WithTx_Call{Call: _e.mock.On("WithTx", tx)}
}

func (_c *MockVocabularyCategoryRepository_WithTx_Call) Run(run func(tx *gorm.DB)) *MockVocabularyCategoryRepository_WithTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *gorm.DB
		if args[0] != nil {
			arg0 = args[0].(*gorm.DB)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockVocabularyCategoryRepository_WithTx_Call) Return(vocabularyCategoryRepository repositories.VocabularyCategoryRepository) *MockVocabularyCategoryRepository_WithTx_Call {
	_c.Call.Return(vocabularyCategoryRepository)
	return _c
}

func (_c *MockVocabularyCategoryRepository_WithTx_Call) RunAndReturn(run func(tx *gorm.DB) repositories.VocabularyCategoryRepository) *MockVocabularyCategoryRepository_WithTx_Call {
	_c.Call.Return(run)
	return _c
}
