/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as ErrorRouteImport } from './routes/error'
import { Route as NotFoundRouteImport } from './routes/not-found'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppAboutRouteImport } from './routes/_app/about'
import { Route as SignInSplatRouteImport } from './routes/sign-in.$'
import { Route as SignUpSplatRouteImport } from './routes/sign-up.$'
import { Route as AppLessonsIndexRouteImport } from './routes/_app/lessons/index'
import { Route as AppVocabularyIndexRouteImport } from './routes/_app/vocabulary/index'
import { Route as AppVocabularyItemIdRouteImport } from './routes/_app/vocabulary/$itemId'
import { Route as AppVoiceIndexRouteImport } from './routes/_app/voice/index'
import { Route as AppVoicePreviewRouteImport } from './routes/_app/voice/preview'
import { Route as AppVoiceScenariosRouteImport } from './routes/_app/voice/scenarios'
import { Route as AppLessonsLessonIdIndexRouteImport } from './routes/_app/lessons/$lessonId/index'
import { Route as AppVoiceRoomConversationIdRouteImport } from './routes/_app/voice/room/$conversationId'
import { Route as AppLessonsLessonIdPartsPartRouteImport } from './routes/_app/lessons/$lessonId/parts/$part'

const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const ErrorRoute = ErrorRouteImport.update({
  id: '/error',
  path: '/error',
  getParentRoute: () => rootRouteImport,
} as any)
const NotFoundRoute = NotFoundRouteImport.update({
  id: '/not-found',
  path: '/not-found',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAboutRoute = AppAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => AppRouteRoute,
} as any)
const SignInSplatRoute = SignInSplatRouteImport.update({
  id: '/sign-in/$',
  path: '/sign-in/$',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpSplatRoute = SignUpSplatRouteImport.update({
  id: '/sign-up/$',
  path: '/sign-up/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppLessonsIndexRoute = AppLessonsIndexRouteImport.update({
  id: '/lessons/',
  path: '/lessons/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppVocabularyIndexRoute = AppVocabularyIndexRouteImport.update({
  id: '/vocabulary/',
  path: '/vocabulary/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppVocabularyItemIdRoute = AppVocabularyItemIdRouteImport.update({
  id: '/vocabulary/$itemId',
  path: '/vocabulary/$itemId',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppVoiceIndexRoute = AppVoiceIndexRouteImport.update({
  id: '/voice/',
  path: '/voice/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppVoicePreviewRoute = AppVoicePreviewRouteImport.update({
  id: '/voice/preview',
  path: '/voice/preview',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppVoiceScenariosRoute = AppVoiceScenariosRouteImport.update({
  id: '/voice/scenarios',
  path: '/voice/scenarios',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppLessonsLessonIdIndexRoute = AppLessonsLessonIdIndexRouteImport.update({
  id: '/lessons/$lessonId/',
  path: '/lessons/$lessonId/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppVoiceRoomConversationIdRoute =
  AppVoiceRoomConversationIdRouteImport.update({
    id: '/voice/room/$conversationId',
    path: '/voice/room/$conversationId',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppLessonsLessonIdPartsPartRoute =
  AppLessonsLessonIdPartsPartRouteImport.update({
    id: '/lessons/$lessonId/parts/$part',
    path: '/lessons/$lessonId/parts/$part',
    getParentRoute: () => AppRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/error': typeof ErrorRoute
  '/not-found': typeof NotFoundRoute
  '/onboarding': typeof OnboardingRoute
  '/about': typeof AppAboutRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/vocabulary/$itemId': typeof AppVocabularyItemIdRoute
  '/voice/preview': typeof AppVoicePreviewRoute
  '/voice/scenarios': typeof AppVoiceScenariosRoute
  '/lessons/': typeof AppLessonsIndexRoute
  '/vocabulary/': typeof AppVocabularyIndexRoute
  '/voice/': typeof AppVoiceIndexRoute
  '/voice/room/$conversationId': typeof AppVoiceRoomConversationIdRoute
  '/lessons/$lessonId/': typeof AppLessonsLessonIdIndexRoute
  '/lessons/$lessonId/parts/$part': typeof AppLessonsLessonIdPartsPartRoute
}
export interface FileRoutesByTo {
  '/error': typeof ErrorRoute
  '/not-found': typeof NotFoundRoute
  '/onboarding': typeof OnboardingRoute
  '/about': typeof AppAboutRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/': typeof AppIndexRoute
  '/vocabulary/$itemId': typeof AppVocabularyItemIdRoute
  '/voice/preview': typeof AppVoicePreviewRoute
  '/voice/scenarios': typeof AppVoiceScenariosRoute
  '/lessons': typeof AppLessonsIndexRoute
  '/vocabulary': typeof AppVocabularyIndexRoute
  '/voice': typeof AppVoiceIndexRoute
  '/voice/room/$conversationId': typeof AppVoiceRoomConversationIdRoute
  '/lessons/$lessonId': typeof AppLessonsLessonIdIndexRoute
  '/lessons/$lessonId/parts/$part': typeof AppLessonsLessonIdPartsPartRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteRouteWithChildren
  '/error': typeof ErrorRoute
  '/not-found': typeof NotFoundRoute
  '/onboarding': typeof OnboardingRoute
  '/_app/about': typeof AppAboutRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/_app/': typeof AppIndexRoute
  '/_app/vocabulary/$itemId': typeof AppVocabularyItemIdRoute
  '/_app/voice/preview': typeof AppVoicePreviewRoute
  '/_app/voice/scenarios': typeof AppVoiceScenariosRoute
  '/_app/lessons/': typeof AppLessonsIndexRoute
  '/_app/vocabulary/': typeof AppVocabularyIndexRoute
  '/_app/voice/': typeof AppVoiceIndexRoute
  '/_app/voice/room/$conversationId': typeof AppVoiceRoomConversationIdRoute
  '/_app/lessons/$lessonId/': typeof AppLessonsLessonIdIndexRoute
  '/_app/lessons/$lessonId/parts/$part': typeof AppLessonsLessonIdPartsPartRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/error'
    | '/not-found'
    | '/onboarding'
    | '/about'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/vocabulary/$itemId'
    | '/voice/preview'
    | '/voice/scenarios'
    | '/lessons/'
    | '/vocabulary/'
    | '/voice/'
    | '/voice/room/$conversationId'
    | '/lessons/$lessonId/'
    | '/lessons/$lessonId/parts/$part'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/error'
    | '/not-found'
    | '/onboarding'
    | '/about'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/'
    | '/vocabulary/$itemId'
    | '/voice/preview'
    | '/voice/scenarios'
    | '/lessons'
    | '/vocabulary'
    | '/voice'
    | '/voice/room/$conversationId'
    | '/lessons/$lessonId'
    | '/lessons/$lessonId/parts/$part'
  id:
    | '__root__'
    | '/_app'
    | '/error'
    | '/not-found'
    | '/onboarding'
    | '/_app/about'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/_app/'
    | '/_app/vocabulary/$itemId'
    | '/_app/voice/preview'
    | '/_app/voice/scenarios'
    | '/_app/lessons/'
    | '/_app/vocabulary/'
    | '/_app/voice/'
    | '/_app/voice/room/$conversationId'
    | '/_app/lessons/$lessonId/'
    | '/_app/lessons/$lessonId/parts/$part'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRouteRoute: typeof AppRouteRouteWithChildren
  ErrorRoute: typeof ErrorRoute
  NotFoundRoute: typeof NotFoundRoute
  OnboardingRoute: typeof OnboardingRoute
  SignInSplatRoute: typeof SignInSplatRoute
  SignUpSplatRoute: typeof SignUpSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/error': {
      id: '/error'
      path: '/error'
      fullPath: '/error'
      preLoaderRoute: typeof ErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/not-found': {
      id: '/not-found'
      path: '/not-found'
      fullPath: '/not-found'
      preLoaderRoute: typeof NotFoundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/about': {
      id: '/_app/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AppAboutRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/sign-in/$': {
      id: '/sign-in/$'
      path: '/sign-in/$'
      fullPath: '/sign-in/$'
      preLoaderRoute: typeof SignInSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up/$': {
      id: '/sign-up/$'
      path: '/sign-up/$'
      fullPath: '/sign-up/$'
      preLoaderRoute: typeof SignUpSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/lessons/': {
      id: '/_app/lessons/'
      path: '/lessons'
      fullPath: '/lessons/'
      preLoaderRoute: typeof AppLessonsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/vocabulary/': {
      id: '/_app/vocabulary/'
      path: '/vocabulary'
      fullPath: '/vocabulary/'
      preLoaderRoute: typeof AppVocabularyIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/vocabulary/$itemId': {
      id: '/_app/vocabulary/$itemId'
      path: '/vocabulary/$itemId'
      fullPath: '/vocabulary/$itemId'
      preLoaderRoute: typeof AppVocabularyItemIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/voice/': {
      id: '/_app/voice/'
      path: '/voice'
      fullPath: '/voice/'
      preLoaderRoute: typeof AppVoiceIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/voice/preview': {
      id: '/_app/voice/preview'
      path: '/voice/preview'
      fullPath: '/voice/preview'
      preLoaderRoute: typeof AppVoicePreviewRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/voice/scenarios': {
      id: '/_app/voice/scenarios'
      path: '/voice/scenarios'
      fullPath: '/voice/scenarios'
      preLoaderRoute: typeof AppVoiceScenariosRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/lessons/$lessonId/': {
      id: '/_app/lessons/$lessonId/'
      path: '/lessons/$lessonId'
      fullPath: '/lessons/$lessonId/'
      preLoaderRoute: typeof AppLessonsLessonIdIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/voice/room/$conversationId': {
      id: '/_app/voice/room/$conversationId'
      path: '/voice/room/$conversationId'
      fullPath: '/voice/room/$conversationId'
      preLoaderRoute: typeof AppVoiceRoomConversationIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/lessons/$lessonId/parts/$part': {
      id: '/_app/lessons/$lessonId/parts/$part'
      path: '/lessons/$lessonId/parts/$part'
      fullPath: '/lessons/$lessonId/parts/$part'
      preLoaderRoute: typeof AppLessonsLessonIdPartsPartRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface AppRouteRouteChildren {
  AppAboutRoute: typeof AppAboutRoute
  AppIndexRoute: typeof AppIndexRoute
  AppVocabularyItemIdRoute: typeof AppVocabularyItemIdRoute
  AppVoicePreviewRoute: typeof AppVoicePreviewRoute
  AppVoiceScenariosRoute: typeof AppVoiceScenariosRoute
  AppLessonsIndexRoute: typeof AppLessonsIndexRoute
  AppVocabularyIndexRoute: typeof AppVocabularyIndexRoute
  AppVoiceIndexRoute: typeof AppVoiceIndexRoute
  AppVoiceRoomConversationIdRoute: typeof AppVoiceRoomConversationIdRoute
  AppLessonsLessonIdIndexRoute: typeof AppLessonsLessonIdIndexRoute
  AppLessonsLessonIdPartsPartRoute: typeof AppLessonsLessonIdPartsPartRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppAboutRoute: AppAboutRoute,
  AppIndexRoute: AppIndexRoute,
  AppVocabularyItemIdRoute: AppVocabularyItemIdRoute,
  AppVoicePreviewRoute: AppVoicePreviewRoute,
  AppVoiceScenariosRoute: AppVoiceScenariosRoute,
  AppLessonsIndexRoute: AppLessonsIndexRoute,
  AppVocabularyIndexRoute: AppVocabularyIndexRoute,
  AppVoiceIndexRoute: AppVoiceIndexRoute,
  AppVoiceRoomConversationIdRoute: AppVoiceRoomConversationIdRoute,
  AppLessonsLessonIdIndexRoute: AppLessonsLessonIdIndexRoute,
  AppLessonsLessonIdPartsPartRoute: AppLessonsLessonIdPartsPartRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppRouteRoute: AppRouteRouteWithChildren,
  ErrorRoute: ErrorRoute,
  NotFoundRoute: NotFoundRoute,
  OnboardingRoute: OnboardingRoute,
  SignInSplatRoute: SignInSplatRoute,
  SignUpSplatRoute: SignUpSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
