/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as ErrorRouteImport } from './routes/error'
import { Route as NotFoundRouteImport } from './routes/not-found'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppAboutRouteImport } from './routes/_app/about'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminLessonsRouteImport } from './routes/admin/lessons'
import { Route as AdminScenariosRouteImport } from './routes/admin/scenarios'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminVideosRouteImport } from './routes/admin/videos'
import { Route as AdminVocabularyRouteImport } from './routes/admin/vocabulary'
import { Route as SignInSplatRouteImport } from './routes/sign-in.$'
import { Route as SignUpSplatRouteImport } from './routes/sign-up.$'
import { Route as AppLessonsIndexRouteImport } from './routes/_app/lessons/index'
import { Route as AppVocabularyIndexRouteImport } from './routes/_app/vocabulary/index'
import { Route as AppVocabularyItemIdRouteImport } from './routes/_app/vocabulary/$itemId'
import { Route as AppVoiceIndexRouteImport } from './routes/_app/voice/index'
import { Route as AppVoicePreviewRouteImport } from './routes/_app/voice/preview'
import { Route as AppLessonsLessonIdIndexRouteImport } from './routes/_app/lessons/$lessonId/index'
import { Route as AppVoiceRoomConversationIdRouteImport } from './routes/_app/voice/room/$conversationId'
import { Route as AppVoiceScenariosIndexRouteImport } from './routes/_app/voice/scenarios/index'
import { Route as AppVoiceScenariosScenarioIdRouteImport } from './routes/_app/voice/scenarios/$scenarioId'
import { Route as AppLessonsLessonIdPartsPartRouteImport } from './routes/_app/lessons/$lessonId/parts/$part'

const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ErrorRoute = ErrorRouteImport.update({
  id: '/error',
  path: '/error',
  getParentRoute: () => rootRouteImport,
} as any)
const NotFoundRoute = NotFoundRouteImport.update({
  id: '/not-found',
  path: '/not-found',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAboutRoute = AppAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => AppRouteRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminLessonsRoute = AdminLessonsRouteImport.update({
  id: '/lessons',
  path: '/lessons',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminScenariosRoute = AdminScenariosRouteImport.update({
  id: '/scenarios',
  path: '/scenarios',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminVideosRoute = AdminVideosRouteImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminVocabularyRoute = AdminVocabularyRouteImport.update({
  id: '/vocabulary',
  path: '/vocabulary',
  getParentRoute: () => AdminRouteRoute,
} as any)
const SignInSplatRoute = SignInSplatRouteImport.update({
  id: '/sign-in/$',
  path: '/sign-in/$',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpSplatRoute = SignUpSplatRouteImport.update({
  id: '/sign-up/$',
  path: '/sign-up/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppLessonsIndexRoute = AppLessonsIndexRouteImport.update({
  id: '/lessons/',
  path: '/lessons/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppVocabularyIndexRoute = AppVocabularyIndexRouteImport.update({
  id: '/vocabulary/',
  path: '/vocabulary/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppVocabularyItemIdRoute = AppVocabularyItemIdRouteImport.update({
  id: '/vocabulary/$itemId',
  path: '/vocabulary/$itemId',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppVoiceIndexRoute = AppVoiceIndexRouteImport.update({
  id: '/voice/',
  path: '/voice/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppVoicePreviewRoute = AppVoicePreviewRouteImport.update({
  id: '/voice/preview',
  path: '/voice/preview',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppLessonsLessonIdIndexRoute = AppLessonsLessonIdIndexRouteImport.update({
  id: '/lessons/$lessonId/',
  path: '/lessons/$lessonId/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppVoiceRoomConversationIdRoute =
  AppVoiceRoomConversationIdRouteImport.update({
    id: '/voice/room/$conversationId',
    path: '/voice/room/$conversationId',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppVoiceScenariosIndexRoute = AppVoiceScenariosIndexRouteImport.update({
  id: '/voice/scenarios/',
  path: '/voice/scenarios/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppVoiceScenariosScenarioIdRoute =
  AppVoiceScenariosScenarioIdRouteImport.update({
    id: '/voice/scenarios/$scenarioId',
    path: '/voice/scenarios/$scenarioId',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppLessonsLessonIdPartsPartRoute =
  AppLessonsLessonIdPartsPartRouteImport.update({
    id: '/lessons/$lessonId/parts/$part',
    path: '/lessons/$lessonId/parts/$part',
    getParentRoute: () => AppRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/error': typeof ErrorRoute
  '/not-found': typeof NotFoundRoute
  '/onboarding': typeof OnboardingRoute
  '/about': typeof AppAboutRoute
  '/admin/lessons': typeof AdminLessonsRoute
  '/admin/scenarios': typeof AdminScenariosRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/videos': typeof AdminVideosRoute
  '/admin/vocabulary': typeof AdminVocabularyRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/admin/': typeof AdminIndexRoute
  '/vocabulary/$itemId': typeof AppVocabularyItemIdRoute
  '/voice/preview': typeof AppVoicePreviewRoute
  '/lessons/': typeof AppLessonsIndexRoute
  '/vocabulary/': typeof AppVocabularyIndexRoute
  '/voice/': typeof AppVoiceIndexRoute
  '/voice/room/$conversationId': typeof AppVoiceRoomConversationIdRoute
  '/voice/scenarios/$scenarioId': typeof AppVoiceScenariosScenarioIdRoute
  '/lessons/$lessonId/': typeof AppLessonsLessonIdIndexRoute
  '/voice/scenarios/': typeof AppVoiceScenariosIndexRoute
  '/lessons/$lessonId/parts/$part': typeof AppLessonsLessonIdPartsPartRoute
}
export interface FileRoutesByTo {
  '/error': typeof ErrorRoute
  '/not-found': typeof NotFoundRoute
  '/onboarding': typeof OnboardingRoute
  '/about': typeof AppAboutRoute
  '/admin/lessons': typeof AdminLessonsRoute
  '/admin/scenarios': typeof AdminScenariosRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/videos': typeof AdminVideosRoute
  '/admin/vocabulary': typeof AdminVocabularyRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/': typeof AppIndexRoute
  '/admin': typeof AdminIndexRoute
  '/vocabulary/$itemId': typeof AppVocabularyItemIdRoute
  '/voice/preview': typeof AppVoicePreviewRoute
  '/lessons': typeof AppLessonsIndexRoute
  '/vocabulary': typeof AppVocabularyIndexRoute
  '/voice': typeof AppVoiceIndexRoute
  '/voice/room/$conversationId': typeof AppVoiceRoomConversationIdRoute
  '/voice/scenarios/$scenarioId': typeof AppVoiceScenariosScenarioIdRoute
  '/lessons/$lessonId': typeof AppLessonsLessonIdIndexRoute
  '/voice/scenarios': typeof AppVoiceScenariosIndexRoute
  '/lessons/$lessonId/parts/$part': typeof AppLessonsLessonIdPartsPartRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteRouteWithChildren
  '/admin': typeof AdminRouteRouteWithChildren
  '/error': typeof ErrorRoute
  '/not-found': typeof NotFoundRoute
  '/onboarding': typeof OnboardingRoute
  '/_app/about': typeof AppAboutRoute
  '/admin/lessons': typeof AdminLessonsRoute
  '/admin/scenarios': typeof AdminScenariosRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/videos': typeof AdminVideosRoute
  '/admin/vocabulary': typeof AdminVocabularyRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/_app/': typeof AppIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/_app/vocabulary/$itemId': typeof AppVocabularyItemIdRoute
  '/_app/voice/preview': typeof AppVoicePreviewRoute
  '/_app/lessons/': typeof AppLessonsIndexRoute
  '/_app/vocabulary/': typeof AppVocabularyIndexRoute
  '/_app/voice/': typeof AppVoiceIndexRoute
  '/_app/voice/room/$conversationId': typeof AppVoiceRoomConversationIdRoute
  '/_app/voice/scenarios/$scenarioId': typeof AppVoiceScenariosScenarioIdRoute
  '/_app/lessons/$lessonId/': typeof AppLessonsLessonIdIndexRoute
  '/_app/voice/scenarios/': typeof AppVoiceScenariosIndexRoute
  '/_app/lessons/$lessonId/parts/$part': typeof AppLessonsLessonIdPartsPartRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/error'
    | '/not-found'
    | '/onboarding'
    | '/about'
    | '/admin/lessons'
    | '/admin/scenarios'
    | '/admin/users'
    | '/admin/videos'
    | '/admin/vocabulary'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/admin/'
    | '/vocabulary/$itemId'
    | '/voice/preview'
    | '/lessons/'
    | '/vocabulary/'
    | '/voice/'
    | '/voice/room/$conversationId'
    | '/voice/scenarios/$scenarioId'
    | '/lessons/$lessonId/'
    | '/voice/scenarios/'
    | '/lessons/$lessonId/parts/$part'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/error'
    | '/not-found'
    | '/onboarding'
    | '/about'
    | '/admin/lessons'
    | '/admin/scenarios'
    | '/admin/users'
    | '/admin/videos'
    | '/admin/vocabulary'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/'
    | '/admin'
    | '/vocabulary/$itemId'
    | '/voice/preview'
    | '/lessons'
    | '/vocabulary'
    | '/voice'
    | '/voice/room/$conversationId'
    | '/voice/scenarios/$scenarioId'
    | '/lessons/$lessonId'
    | '/voice/scenarios'
    | '/lessons/$lessonId/parts/$part'
  id:
    | '__root__'
    | '/_app'
    | '/admin'
    | '/error'
    | '/not-found'
    | '/onboarding'
    | '/_app/about'
    | '/admin/lessons'
    | '/admin/scenarios'
    | '/admin/users'
    | '/admin/videos'
    | '/admin/vocabulary'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/_app/'
    | '/admin/'
    | '/_app/vocabulary/$itemId'
    | '/_app/voice/preview'
    | '/_app/lessons/'
    | '/_app/vocabulary/'
    | '/_app/voice/'
    | '/_app/voice/room/$conversationId'
    | '/_app/voice/scenarios/$scenarioId'
    | '/_app/lessons/$lessonId/'
    | '/_app/voice/scenarios/'
    | '/_app/lessons/$lessonId/parts/$part'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRouteRoute: typeof AppRouteRouteWithChildren
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  ErrorRoute: typeof ErrorRoute
  NotFoundRoute: typeof NotFoundRoute
  OnboardingRoute: typeof OnboardingRoute
  SignInSplatRoute: typeof SignInSplatRoute
  SignUpSplatRoute: typeof SignUpSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/error': {
      id: '/error'
      path: '/error'
      fullPath: '/error'
      preLoaderRoute: typeof ErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/not-found': {
      id: '/not-found'
      path: '/not-found'
      fullPath: '/not-found'
      preLoaderRoute: typeof NotFoundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/about': {
      id: '/_app/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AppAboutRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/lessons': {
      id: '/admin/lessons'
      path: '/lessons'
      fullPath: '/admin/lessons'
      preLoaderRoute: typeof AdminLessonsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/scenarios': {
      id: '/admin/scenarios'
      path: '/scenarios'
      fullPath: '/admin/scenarios'
      preLoaderRoute: typeof AdminScenariosRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/videos': {
      id: '/admin/videos'
      path: '/videos'
      fullPath: '/admin/videos'
      preLoaderRoute: typeof AdminVideosRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/vocabulary': {
      id: '/admin/vocabulary'
      path: '/vocabulary'
      fullPath: '/admin/vocabulary'
      preLoaderRoute: typeof AdminVocabularyRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/sign-in/$': {
      id: '/sign-in/$'
      path: '/sign-in/$'
      fullPath: '/sign-in/$'
      preLoaderRoute: typeof SignInSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up/$': {
      id: '/sign-up/$'
      path: '/sign-up/$'
      fullPath: '/sign-up/$'
      preLoaderRoute: typeof SignUpSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/lessons/': {
      id: '/_app/lessons/'
      path: '/lessons'
      fullPath: '/lessons/'
      preLoaderRoute: typeof AppLessonsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/vocabulary/': {
      id: '/_app/vocabulary/'
      path: '/vocabulary'
      fullPath: '/vocabulary/'
      preLoaderRoute: typeof AppVocabularyIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/vocabulary/$itemId': {
      id: '/_app/vocabulary/$itemId'
      path: '/vocabulary/$itemId'
      fullPath: '/vocabulary/$itemId'
      preLoaderRoute: typeof AppVocabularyItemIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/voice/': {
      id: '/_app/voice/'
      path: '/voice'
      fullPath: '/voice/'
      preLoaderRoute: typeof AppVoiceIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/voice/preview': {
      id: '/_app/voice/preview'
      path: '/voice/preview'
      fullPath: '/voice/preview'
      preLoaderRoute: typeof AppVoicePreviewRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/lessons/$lessonId/': {
      id: '/_app/lessons/$lessonId/'
      path: '/lessons/$lessonId'
      fullPath: '/lessons/$lessonId/'
      preLoaderRoute: typeof AppLessonsLessonIdIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/voice/room/$conversationId': {
      id: '/_app/voice/room/$conversationId'
      path: '/voice/room/$conversationId'
      fullPath: '/voice/room/$conversationId'
      preLoaderRoute: typeof AppVoiceRoomConversationIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/voice/scenarios/': {
      id: '/_app/voice/scenarios/'
      path: '/voice/scenarios'
      fullPath: '/voice/scenarios/'
      preLoaderRoute: typeof AppVoiceScenariosIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/voice/scenarios/$scenarioId': {
      id: '/_app/voice/scenarios/$scenarioId'
      path: '/voice/scenarios/$scenarioId'
      fullPath: '/voice/scenarios/$scenarioId'
      preLoaderRoute: typeof AppVoiceScenariosScenarioIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/lessons/$lessonId/parts/$part': {
      id: '/_app/lessons/$lessonId/parts/$part'
      path: '/lessons/$lessonId/parts/$part'
      fullPath: '/lessons/$lessonId/parts/$part'
      preLoaderRoute: typeof AppLessonsLessonIdPartsPartRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface AppRouteRouteChildren {
  AppAboutRoute: typeof AppAboutRoute
  AppIndexRoute: typeof AppIndexRoute
  AppVocabularyItemIdRoute: typeof AppVocabularyItemIdRoute
  AppVoicePreviewRoute: typeof AppVoicePreviewRoute
  AppLessonsIndexRoute: typeof AppLessonsIndexRoute
  AppVocabularyIndexRoute: typeof AppVocabularyIndexRoute
  AppVoiceIndexRoute: typeof AppVoiceIndexRoute
  AppVoiceRoomConversationIdRoute: typeof AppVoiceRoomConversationIdRoute
  AppVoiceScenariosScenarioIdRoute: typeof AppVoiceScenariosScenarioIdRoute
  AppLessonsLessonIdIndexRoute: typeof AppLessonsLessonIdIndexRoute
  AppVoiceScenariosIndexRoute: typeof AppVoiceScenariosIndexRoute
  AppLessonsLessonIdPartsPartRoute: typeof AppLessonsLessonIdPartsPartRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppAboutRoute: AppAboutRoute,
  AppIndexRoute: AppIndexRoute,
  AppVocabularyItemIdRoute: AppVocabularyItemIdRoute,
  AppVoicePreviewRoute: AppVoicePreviewRoute,
  AppLessonsIndexRoute: AppLessonsIndexRoute,
  AppVocabularyIndexRoute: AppVocabularyIndexRoute,
  AppVoiceIndexRoute: AppVoiceIndexRoute,
  AppVoiceRoomConversationIdRoute: AppVoiceRoomConversationIdRoute,
  AppVoiceScenariosScenarioIdRoute: AppVoiceScenariosScenarioIdRoute,
  AppLessonsLessonIdIndexRoute: AppLessonsLessonIdIndexRoute,
  AppVoiceScenariosIndexRoute: AppVoiceScenariosIndexRoute,
  AppLessonsLessonIdPartsPartRoute: AppLessonsLessonIdPartsPartRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

interface AdminRouteRouteChildren {
  AdminLessonsRoute: typeof AdminLessonsRoute
  AdminScenariosRoute: typeof AdminScenariosRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminVideosRoute: typeof AdminVideosRoute
  AdminVocabularyRoute: typeof AdminVocabularyRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminLessonsRoute: AdminLessonsRoute,
  AdminScenariosRoute: AdminScenariosRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminVideosRoute: AdminVideosRoute,
  AdminVocabularyRoute: AdminVocabularyRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppRouteRoute: AppRouteRouteWithChildren,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  ErrorRoute: ErrorRoute,
  NotFoundRoute: NotFoundRoute,
  OnboardingRoute: OnboardingRoute,
  SignInSplatRoute: SignInSplatRoute,
  SignUpSplatRoute: SignUpSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
