// Code generated by tygo. DO NOT EDIT.

//////////
// source: attempt.go

/**
 * CreateAttempt records one practice run. result carries per-type detail
 * (typed schemas come with the practice endpoints). score and duration are
 * optional; free talk has no score.
 */
export interface CreateAttempt {
  lessonId?: string;
  activityId?: string;
  conversationId?: string;
  type: AttemptType;
  score?: number /* float64 */;
  result: { [key: string]: unknown};
  durationSec?: number /* int */;
}
