// Code generated by tygo. DO NOT EDIT.

//////////
// source: attempt.go

/**
 * Attempt is one recorded practice run (the progress source of truth).
 * result stays loosely typed this phase; typed per-practice schemas come
 * with the practice endpoints.
 */
export interface Attempt {
  id: string;
  userId: string;
  lessonId?: string;
  activityId?: string;
  conversationId?: string;
  type: AttemptType;
  score?: number /* float64 */;
  result: { [key: string]: unknown};
  durationSec?: number /* int */;
  createdAt: string /* RFC3339 */;
}
/**
 * ProgressSummary is the dashboard rollup, composed later by services from
 * attempts (streak, minutes, voice metrics) and user_vocabulary (due count).
 */
export interface ProgressSummary {
  streakDays: number /* int */;
  todayMinutes: number /* int */;
  dailyGoalMinutes: number /* int */;
  fluencyPct: number /* int */;
  pronunciationPct: number /* int */;
  wpm: number /* int */;
  dueVocabulary: number /* int */;
}
