// Code generated by tygo. DO NOT EDIT.

//////////
// source: constants.go

export const DefaultPage = 1;
export const DefaultPageSize = 20;
export const MaxPageSize = 100;
/**
 * Shared wire limits. Binding tags on request DTOs must match these
 * (guarded by a limits_test.go per module).
 */
export const NameMaxLength = 255;
export const TitleMaxLength = 255;
export const TermMaxLength = 255;
export const MeaningMaxLength = 1000;
export const TextMaxLength = 10000;

//////////
// source: list.go

/**
 * ListParams are the reusable query params embedded by every list request
 * DTO (lesson hub, vocabulary studio, future attempt/turn lists). Defaults
 * and clamping are owned by utils.ParsePagination (DefaultPage,
 * DefaultPageSize, MaxPageSize), not by binding tags. DTOs embed it with
 * `tstype:",extends"` so tygo emits `interface ListX extends ListParams`;
 * json tags mirror the query keys so generated field names match the wire.
 */
export interface ListParams {
  page: number /* int */;
  pageSize: number /* int */;
  search: string;
}

//////////
// source: response.go

/**
 * Pagination carries page metadata for list endpoints.
 */
export interface Pagination {
  page: number /* int */;
  pageSize: number /* int */;
  total: number /* int64 */;
  totalPages: number /* int */;
}
/**
 * ApiResponse is the shared JSON envelope for every API response.
 * Pagination is nil for non-paginated responses.
 */
export interface ApiResponse {
  message: string;
  data?: any;
  pagination?: Pagination;
}
