// Code generated by tygo. DO NOT EDIT.

//////////
// source: conversation.go

/**
 * Turn is one transcript line. The speaker display name is derived by
 * joining scenario -> persona, not stored on the turn.
 */
export interface Turn {
  id: string;
  position: number /* int */;
  role: TurnRole;
  text: string;
  createdAt: string /* RFC3339 */;
}
/**
 * Conversation is a voice session with its transcript.
 */
export interface Conversation {
  id: string;
  mode: ConversationMode;
  scenarioId?: string;
  status: ConversationStatus;
  startedAt: string /* RFC3339 */;
  endedAt?: string /* RFC3339 */;
  durationSec?: number /* int */;
  turns: Turn[];
}

//////////
// source: conversation_session.go

/**
 * ConversationSession is returned by POST /conversations/:id/start.
 * SessionID is the EngFlex conversation id (the engine id stays server-side).
 */
export interface ConversationSession {
  sessionId: string;
  iceConfig?: IceConfig;
  maxDuration: number /* int */;
}

//////////
// source: feedback.go

/**
 * WordMark highlights one word inside an analyzed turn (feedback.marks[]).
 */
export interface WordMark {
  word: string;
  status: WordMarkStatus;
}
/**
 * PhonemeMark is one pronunciation diagnostic card (/θ/ in "both").
 */
export interface PhonemeMark {
  ipa: string;
  word: string;
  feature: string;
  accuracyPct: number /* int */;
  label: string;
}
/**
 * PhraseUpgrade suggests replacing original with one of replacements
 * ("primary concern" -> "decisive constraint").
 */
export interface PhraseUpgrade {
  original: string;
  replacements: string[];
  category: string;
}
/**
 * TurnFeedback mirrors conversation_turns.feedback (jsonb).
 */
export interface TurnFeedback {
  annotated: string;
  marks: WordMark[];
  phonemes: PhonemeMark[];
  upgrades: PhraseUpgrade[];
  tip: string;
}

//////////
// source: ice.go

/**
 * IceServer is one STUN/TURN entry handed to the browser.
 */
export interface IceServer {
  urls: string[];
  username?: string;
  credential?: string;
}
/**
 * IceConfig is the engine-supplied ICE configuration for a session.
 */
export interface IceConfig {
  iceServers: IceServer[];
}
