// Code generated by tygo. DO NOT EDIT.

//////////
// source: conversation.go

/**
 * Turn is one transcript line. The speaker display name is derived by
 * joining scenario -> persona, not stored on the turn. Feedback mirrors
 * models.ConversationTurn.Feedback — the coaching record the repository
 * joined in — so utils.MapSlice copies the whole thing, payload included.
 */
export interface Turn {
  id: string;
  position: number /* int */;
  role: TurnRole;
  text: string;
  wasInterrupted: boolean;
  feedback?: Feedback;
  createdAt: string /* RFC3339 */;
}
/**
 * Feedback is one coaching record attached to a turn. It mirrors
 * models.Feedback minus the columns this view does not render: user_id,
 * subject_type, and subject_id are relationship facts the join already
 * proved, so only the coaching document crosses the wire. Flattening it
 * instead (turn.feedback.tip) would break utils.Map silently — copier
 * matches field names, and models.Feedback has no Corrected field.
 */
export interface Feedback {
  payload: TurnFeedback;
}
/**
 * Conversation is a voice session with its transcript.
 */
export interface Conversation {
  id: string;
  mode: ConversationMode;
  scenarioId?: string;
  status: ConversationStatus;
  startedAt: string /* RFC3339 */;
  endedAt?: string /* RFC3339 */;
  durationSec?: number /* int */;
  turns: Turn[];
}

//////////
// source: conversation_session.go

/**
 * ConversationSession is returned by POST /conversations/:id/start.
 * SessionID is the EngFlex conversation id (the engine id stays server-side).
 */
export interface ConversationSession {
  sessionId: string;
  iceConfig?: IceConfig;
  maxDuration: number /* int */;
}

//////////
// source: feedback.go

/**
 * AnalysisSpan is one problematic span: the smallest meaningful unit,
 * located by exact substring plus 1-based occurrence.
 */
export interface AnalysisSpan {
  text: string;
  occurrence: number /* int */;
  status: SpanStatus;
  correction: string;
  reason: string;
}
/**
 * Relevance judges whether a learner turn answers its conversation context.
 */
export interface Relevance {
  status: RelevanceStatus;
  reason?: string;
}
/**
 * Alternative is one better phrasing or answer with its reason.
 */
export interface Alternative {
  text: string;
  reason: string;
}
/**
 * SpanAlternatives holds the singular alternatives: language preserves the
 * learner's meaning, contextual answers the conversation better. Null means
 * not produced.
 */
export interface SpanAlternatives {
  language?: Alternative;
  contextual?: Alternative;
}
/**
 * TurnFeedback is the conversation-aware English feedback payload:
 * language spans, conversational relevance, and alternatives.
 */
export interface TurnFeedback {
  corrected: string;
  spans: AnalysisSpan[];
  relevance: Relevance;
  alternatives: SpanAlternatives;
  tip: string;
}

//////////
// source: ice.go

/**
 * IceServer is one STUN/TURN entry handed to the browser.
 */
export interface IceServer {
  urls: string[];
  username?: string;
  credential?: string;
}
/**
 * IceConfig is the engine-supplied ICE configuration for a session.
 */
export interface IceConfig {
  iceServers: IceServer[];
}

//////////
// source: transcript.go

/**
 * TranscriptCommand is the web-facing request for the correction modal.
 * The three actions share the reviewed turn on the engine, so they are one
 * endpoint. The client never names a turn: its row ordinal and the engine's
 * collector position are separate bookkeeping, so the engine resolves the target
 * and hands back its own copy of the text.
 */
export interface TranscriptCommand {
  /**
   * Action is one of review, send, dismiss.
   */
  action: string;
  /**
   * Text is the learner's correction, used only by send.
   */
  text?: string;
}
/**
 * TranscriptResult is the engine's reply: where the review is now, and the
 * transcript text when the action produced any.
 */
export interface TranscriptResult {
  state: string;
  text?: string;
}
/**
 * TranscribeResult is the engine's reply to a retake upload: the sentence it heard.
 */
export interface TranscribeResult {
  text: string;
}
/**
 * MispronouncedWord is one engine-flagged word: expected vs heard IPA.
 */
export interface MispronouncedWord {
  word: string;
  expected: string;
  heard: string;
  confidence: number /* float64 */;
}
/**
 * PronounceResult is the engine's reply to an exercise attempt: the score
 * plus per-word errors. The engine owns scoring; Go forwards verbatim.
 */
export interface PronounceResult {
  score: number /* float64 */;
  transcription: string;
  phonemeErrorRate: number /* float64 */;
  wordErrorRate: number /* float64 */;
  acousticDistance: number /* float64 */;
  errors: MispronouncedWord[];
}
