// Code generated by tygo. DO NOT EDIT.

//////////
// source: conversation.go

/**
 * StartConversation provisions a session. scenarioId is required for
 * roleplay and omitted for free talk.
 */
export interface StartConversation {
  mode: ConversationMode;
  scenarioId?: string;
}
/**
 * WordMarkInput highlights one word inside an analyzed turn. Request-side
 * shapes carry an Input suffix so the contracts barrel can re-export both
 * requests and responses without name collisions (see spec §6).
 */
export interface WordMarkInput {
  word: string;
  status: WordMarkStatus;
}
/**
 * PhonemeMarkInput is one pronunciation diagnostic card (/θ/ in "both").
 */
export interface PhonemeMarkInput {
  ipa: string;
  word: string;
  feature: string;
  accuracyPct: number /* int */;
  label: string;
}
/**
 * PhraseUpgradeInput suggests replacing original with one of replacements.
 */
export interface PhraseUpgradeInput {
  original: string;
  replacements: string[];
  category: string;
}
/**
 * TurnFeedbackInput carries per-turn analysis (word marks, phoneme
 * accuracy, phrase upgrades, coaching tip).
 */
export interface TurnFeedbackInput {
  annotated: string;
  marks: WordMarkInput[];
  phonemes: PhonemeMarkInput[];
  upgrades: PhraseUpgradeInput[];
  tip: string;
}
/**
 * CreateTurn appends one transcript line (used by the voice result
 * ingestion flow). position keeps transcript order deterministic.
 */
export interface CreateTurn {
  position: number /* int */;
  role: TurnRole;
  text: string;
  feedback?: TurnFeedbackInput;
}
