// Code generated by tygo. DO NOT EDIT.

//////////
// source: conversation.go

/**
 * StartConversation provisions a session. scenarioId is required for
 * roleplay and omitted for free talk.
 */
export interface StartConversation {
  mode: ConversationMode;
  scenarioId?: string;
}
/**
 * AnalysisSpanInput is one problematic span in an ingested analysis.
 */
export interface AnalysisSpanInput {
  text: string;
  occurrence: number /* int */;
  status: SpanStatus;
  correction: string;
  reason: string;
}
/**
 * RelevanceInput judges whether a learner turn answers its context.
 */
export interface RelevanceInput {
  status: RelevanceStatus;
  reason?: string;
}
/**
 * AlternativeInput is one better phrasing or answer with its reason.
 */
export interface AlternativeInput {
  text: string;
  reason: string;
}
/**
 * SpanAlternativesInput holds the singular alternatives; null means not produced.
 */
export interface SpanAlternativesInput {
  language?: AlternativeInput;
  contextual?: AlternativeInput;
}
/**
 * TurnFeedbackInput carries per-turn analysis (spans, relevance,
 * alternatives, coaching tip).
 */
export interface TurnFeedbackInput {
  corrected: string;
  spans: AnalysisSpanInput[];
  relevance: RelevanceInput;
  alternatives: SpanAlternativesInput;
  tip: string;
}
/**
 * CreateTurn appends one transcript line (used by the voice result
 * ingestion flow). position keeps transcript order deterministic.
 */
export interface CreateTurn {
  position: number /* int */;
  role: TurnRole;
  text: string;
  feedback?: TurnFeedbackInput;
}
