// Code generated by tygo. DO NOT EDIT.

//////////
// source: activity_type.go

/**
 * ActivityType is a lesson activity type (lesson_activities.type) and the
 * lesson skill tag (lessons.details.skill).
 */
export const ActivityTypeReading = "reading";
export const ActivityTypeDictation = "dictation";
export const ActivityTypeWriting = "writing";
export const ActivityTypeVoice = "voice";
export type ActivityType = typeof ActivityTypeReading | typeof ActivityTypeDictation | typeof ActivityTypeWriting | typeof ActivityTypeVoice;

//////////
// source: attempt_type.go

/**
 * AttemptType is the attempt category (attempts.type). Superset of
 * ActivityType: attempts also come from non-lesson flows (shadowing,
 * flashcard drills, the onboarding benchmark).
 */
export const AttemptTypeReading = "reading";
export const AttemptTypeDictation = "dictation";
export const AttemptTypeWriting = "writing";
export const AttemptTypeVoice = "voice";
export const AttemptTypeShadowing = "shadowing";
export const AttemptTypeFlashcard = "flashcard";
export const AttemptTypeBenchmark = "benchmark";
export type AttemptType = typeof AttemptTypeReading | typeof AttemptTypeDictation | typeof AttemptTypeWriting | typeof AttemptTypeVoice | typeof AttemptTypeShadowing | typeof AttemptTypeFlashcard | typeof AttemptTypeBenchmark;

//////////
// source: cefr.go

/**
 * CEFR is the international proficiency standard used by lessons,
 * vocabulary items, and personas (lessons.cefr_level,
 * vocabulary_items.cefr, personas.default_cefr). Display labels and colors
 * are frontend copy; "B1+" is a product half-step handled by
 * ScenarioDifficulty.
 */
export const CEFRA1 = "A1";
export const CEFRA2 = "A2";
export const CEFRB1 = "B1";
export const CEFRB2 = "B2";
export const CEFRC1 = "C1";
export const CEFRC2 = "C2";
export type CEFR = typeof CEFRA1 | typeof CEFRA2 | typeof CEFRB1 | typeof CEFRB2 | typeof CEFRC1 | typeof CEFRC2;

//////////
// source: conversation_mode.go

/**
 * ConversationMode selects free talk vs roleplay (conversations.mode).
 */
export const ConversationModeFreeTalk = "free_talk";
export const ConversationModeRoleplay = "roleplay";
export type ConversationMode = typeof ConversationModeFreeTalk | typeof ConversationModeRoleplay;

//////////
// source: conversation_status.go

/**
 * ConversationStatus is the session lifecycle state (conversations.status).
 */
export const ConversationStatusLive = "live";
export const ConversationStatusEnded = "ended";
export type ConversationStatus = typeof ConversationStatusLive | typeof ConversationStatusEnded;

//////////
// source: goal.go

/**
 * Goal is the onboarding primary goal (user_profiles.preferences.primary_goal).
 */
export const GoalTravel = "travel";
export const GoalWork = "work";
export const GoalExams = "exams";
export const GoalDaily = "daily";
export const GoalFun = "fun";
export type Goal = typeof GoalTravel | typeof GoalWork | typeof GoalExams | typeof GoalDaily | typeof GoalFun;

//////////
// source: interest_topic.go

/**
 * InterestTopic is an onboarding topic preference
 * (user_profiles.preferences.topics[]).
 */
export const InterestTopicTravel = "travel";
export const InterestTopicBusiness = "business";
export const InterestTopicMoviesTV = "movies_tv";
export const InterestTopicTechnology = "technology";
export const InterestTopicFood = "food";
export const InterestTopicMusic = "music";
export const InterestTopicSports = "sports";
export const InterestTopicNews = "news";
export type InterestTopic = typeof InterestTopicTravel | typeof InterestTopicBusiness | typeof InterestTopicMoviesTV | typeof InterestTopicTechnology | typeof InterestTopicFood | typeof InterestTopicMusic | typeof InterestTopicSports | typeof InterestTopicNews;

//////////
// source: lesson_status.go

/**
 * LessonStatus is the API-only completion status derived from attempts
 * (never stored as a column).
 */
export const LessonStatusUnstarted = "unstarted";
export const LessonStatusInProgress = "in_progress";
export const LessonStatusCompleted = "completed";
export type LessonStatus = typeof LessonStatusUnstarted | typeof LessonStatusInProgress | typeof LessonStatusCompleted;

//////////
// source: level.go

/**
 * Level is the onboarding proficiency bucket
 * (user_profiles.preferences.level).
 */
export const LevelBeginner = "beginner";
export const LevelIntermediate = "intermediate";
export const LevelAdvanced = "advanced";
export type Level = typeof LevelBeginner | typeof LevelIntermediate | typeof LevelAdvanced;

//////////
// source: scenario_difficulty.go

/**
 * ScenarioDifficulty is the scenario difficulty value (scenarios.cefr_level).
 * Separate from CEFR because "B1+" is a product half-step, not a CEFR level.
 */
export const ScenarioDifficultyB1Plus = "B1+";
export const ScenarioDifficultyB2 = "B2";
export const ScenarioDifficultyC1 = "C1";
export type ScenarioDifficulty = typeof ScenarioDifficultyB1Plus | typeof ScenarioDifficultyB2 | typeof ScenarioDifficultyC1;

//////////
// source: turn_role.go

/**
 * TurnRole identifies who produced a conversation turn
 * (conversation_turns.role).
 */
export const TurnRoleUser = "user";
export const TurnRoleAI = "ai";
export type TurnRole = typeof TurnRoleUser | typeof TurnRoleAI;

//////////
// source: vocabulary_domain.go

/**
 * VocabularyDomain groups technical vocabulary (vocabulary_items.domain).
 * Open set: when a domain is added, extend these constants and the
 * chk_vocabulary_items_domain CHECK together.
 */
export const VocabularyDomainBackendDB = "backend_db";
export const VocabularyDomainDistributed = "distributed_systems";
export const VocabularyDomainDevOpsCloud = "devops_cloud";
export const VocabularyDomainFrontendUI = "frontend_ui";
export const VocabularyDomainAIML = "ai_ml";
export type VocabularyDomain = typeof VocabularyDomainBackendDB | typeof VocabularyDomainDistributed | typeof VocabularyDomainDevOpsCloud | typeof VocabularyDomainFrontendUI | typeof VocabularyDomainAIML;

//////////
// source: vocabulary_sort.go

/**
 * VocabularySort is the API-only list sort order for the vocabulary hub.
 */
export const VocabularySortRecent = "recent";
export const VocabularySortMastery = "mastery";
export const VocabularySortAlpha = "alphabetical";
export const VocabularySortInterval = "interval";
export type VocabularySort = typeof VocabularySortRecent | typeof VocabularySortMastery | typeof VocabularySortAlpha | typeof VocabularySortInterval;

//////////
// source: vocabulary_source.go

/**
 * VocabularySource is how a term entered the user's vocabulary set
 * (user_vocabulary.source_type).
 */
export const VocabularySourceLesson = "lesson";
export const VocabularySourceConversation = "conversation";
export const VocabularySourceManual = "manual";
export type VocabularySource = typeof VocabularySourceLesson | typeof VocabularySourceConversation | typeof VocabularySourceManual;

//////////
// source: word_mark_status.go

/**
 * WordMarkStatus is the per-word highlight status inside
 * conversation_turns.feedback.marks[].status (API-only, nested jsonb).
 */
export const WordMarkStatusAccurate = "accurate";
export const WordMarkStatusWarning = "warning";
export const WordMarkStatusError = "error";
export type WordMarkStatus = typeof WordMarkStatusAccurate | typeof WordMarkStatusWarning | typeof WordMarkStatusError;
