// Code generated by tygo. DO NOT EDIT.

//////////
// source: activity_type.go

/**
 * ActivityType is a lesson activity type (lesson_activities.type) and the
 * lesson skill tag (lessons.details.skill).
 */
export const ActivityTypeReading = "reading";
export const ActivityTypeListening = "listening";
export const ActivityTypeWriting = "writing";
export const ActivityTypeSpeaking = "speaking";
export type ActivityType = typeof ActivityTypeReading | typeof ActivityTypeListening | typeof ActivityTypeWriting | typeof ActivityTypeSpeaking;

//////////
// source: attempt_status.go

/**
 * AttemptStatus is the lesson-attempt lifecycle (Moodle parity).
 */
export const AttemptStatusInProgress = "in_progress";
export const AttemptStatusCompleted = "completed";
export const AttemptStatusAbandoned = "abandoned";
export type AttemptStatus = typeof AttemptStatusInProgress | typeof AttemptStatusCompleted | typeof AttemptStatusAbandoned;

//////////
// source: attempt_type.go

/**
 * AttemptType is the attempt category (attempts.type). Superset of
 * ActivityType: attempts also come from non-lesson flows (shadowing,
 * flashcard drills, the onboarding benchmark, standalone dictation).
 */
export const AttemptTypeReading = "reading";
export const AttemptTypeListening = "listening";
export const AttemptTypeWriting = "writing";
export const AttemptTypeSpeaking = "speaking";
export const AttemptTypeShadowing = "shadowing";
export const AttemptTypeFlashcard = "flashcard";
export const AttemptTypeBenchmark = "benchmark";
export const AttemptTypeDictation = "dictation";
export const AttemptTypeLesson = "lesson";
export type AttemptType = typeof AttemptTypeReading | typeof AttemptTypeListening | typeof AttemptTypeWriting | typeof AttemptTypeSpeaking | typeof AttemptTypeShadowing | typeof AttemptTypeFlashcard | typeof AttemptTypeBenchmark | typeof AttemptTypeDictation | typeof AttemptTypeLesson;

//////////
// source: cefr.go

/**
 * CEFR is the international proficiency standard used by lessons,
 * vocabulary items, and personas (lessons.cefr_level,
 * vocabulary_items.cefr, personas.default_cefr). Display labels and colors
 * are frontend copy; "B1+" is a product half-step handled by
 * ScenarioDifficulty.
 */
export const CEFRA1 = "A1";
export const CEFRA2 = "A2";
export const CEFRB1 = "B1";
export const CEFRB2 = "B2";
export const CEFRC1 = "C1";
export const CEFRC2 = "C2";
export type CEFR = typeof CEFRA1 | typeof CEFRA2 | typeof CEFRB1 | typeof CEFRB2 | typeof CEFRC1 | typeof CEFRC2;

//////////
// source: conversation_mode.go

/**
 * ConversationMode selects free talk vs roleplay (conversations.mode).
 */
export const ConversationModeFreeTalk = "free_talk";
export const ConversationModeRoleplay = "roleplay";
export type ConversationMode = typeof ConversationModeFreeTalk | typeof ConversationModeRoleplay;

//////////
// source: conversation_status.go

/**
 * ConversationStatus is the session lifecycle state (conversations.status).
 */
export const ConversationStatusPending = "pending";
export const ConversationStatusLive = "live";
export const ConversationStatusEnded = "ended";
export const ConversationStatusFailed = "failed";
export type ConversationStatus = typeof ConversationStatusPending | typeof ConversationStatusLive | typeof ConversationStatusEnded | typeof ConversationStatusFailed;

//////////
// source: feedback_subject_type.go

/**
 * FeedbackSubjectType names what a feedback row is about. The subject is a
 * polymorphic reference: there is no foreign key, so ownership is verified
 * in the service before a row is written (spec section 3.1).
 */
export type FeedbackSubjectType = string;
/**
 * FeedbackSubjectConversationTurn is one learner turn in a voice
 * conversation. Its payload carries the language block; the speech block
 * stays absent until a provider is chosen (P3).
 */
export const FeedbackSubjectConversationTurn: FeedbackSubjectType = "conversation_turn";
/**
 * FeedbackSubjectWritingResponse and FeedbackSubjectReadingAnswer are
 * reserved for the writing and reading activities; unused in P2.
 */
export const FeedbackSubjectWritingResponse: FeedbackSubjectType = "writing_response";
export const FeedbackSubjectReadingAnswer: FeedbackSubjectType = "reading_answer";

//////////
// source: gender.go

/**
 * Gender selects the TTS voice for a persona
 * (personas.gender).
 */
export const GenderMale = "male";
export const GenderFemale = "female";
export type Gender = typeof GenderMale | typeof GenderFemale;

//////////
// source: goal.go

/**
 * Goal is the onboarding primary goal (user_profiles.preferences.primary_goal).
 */
export const GoalTravel = "travel";
export const GoalWork = "work";
export const GoalExams = "exams";
export const GoalDaily = "daily";
export const GoalFun = "fun";
export type Goal = typeof GoalTravel | typeof GoalWork | typeof GoalExams | typeof GoalDaily | typeof GoalFun;

//////////
// source: interest_topic.go

/**
 * InterestTopic is an onboarding topic preference
 * (user_profiles.preferences.topics[]).
 */
export const InterestTopicTravel = "travel";
export const InterestTopicBusiness = "business";
export const InterestTopicMoviesTV = "movies_tv";
export const InterestTopicTechnology = "technology";
export const InterestTopicFood = "food";
export const InterestTopicMusic = "music";
export const InterestTopicSports = "sports";
export const InterestTopicNews = "news";
export type InterestTopic = typeof InterestTopicTravel | typeof InterestTopicBusiness | typeof InterestTopicMoviesTV | typeof InterestTopicTechnology | typeof InterestTopicFood | typeof InterestTopicMusic | typeof InterestTopicSports | typeof InterestTopicNews;

//////////
// source: lesson_status.go

/**
 * LessonStatus is the API-only completion status derived from attempts
 * (never stored as a column).
 */
export const LessonStatusUnstarted = "unstarted";
export const LessonStatusInProgress = "in_progress";
export const LessonStatusCompleted = "completed";
export type LessonStatus = typeof LessonStatusUnstarted | typeof LessonStatusInProgress | typeof LessonStatusCompleted;

//////////
// source: level.go

/**
 * Level is the onboarding proficiency bucket
 * (user_profiles.preferences.level).
 */
export const LevelBeginner = "beginner";
export const LevelIntermediate = "intermediate";
export const LevelAdvanced = "advanced";
export type Level = typeof LevelBeginner | typeof LevelIntermediate | typeof LevelAdvanced;

//////////
// source: relevance_status.go

/**
 * RelevanceStatus judges whether a learner turn answers its conversation
 * context (conversation_turns.feedback.relevance.status).
 */
export type RelevanceStatus = string;
export const RelevanceRelevant: RelevanceStatus = "relevant";
export const RelevancePartiallyRelevant: RelevanceStatus = "partially_relevant";
export const RelevanceOffTopic: RelevanceStatus = "off_topic";
export const RelevanceNotApplicable: RelevanceStatus = "not_applicable";

//////////
// source: scenario_difficulty.go

/**
 * ScenarioDifficulty is the scenario difficulty value (scenarios.cefr_level).
 * Separate from CEFR because "B1+" is a product half-step, not a CEFR level.
 */
export const ScenarioDifficultyB1Plus = "B1+";
export const ScenarioDifficultyB2 = "B2";
export const ScenarioDifficultyC1 = "C1";
export type ScenarioDifficulty = typeof ScenarioDifficultyB1Plus | typeof ScenarioDifficultyB2 | typeof ScenarioDifficultyC1;

//////////
// source: span_status.go

/**
 * SpanStatus is the severity of one analysis span
 * (conversation_turns.feedback.spans[].status).
 */
export const SpanStatusIncorrect = "incorrect";
export const SpanStatusAwkward = "awkward";
export type SpanStatus = typeof SpanStatusIncorrect | typeof SpanStatusAwkward;

//////////
// source: turn_role.go

/**
 * TurnRole identifies who produced a conversation turn
 * (conversation_turns.role).
 */
export const TurnRoleUser = "user";
export const TurnRoleAI = "ai";
export type TurnRole = typeof TurnRoleUser | typeof TurnRoleAI;

//////////
// source: vocabulary_domain.go

/**
 * VocabularyDomain groups technical vocabulary (vocabulary_items.domain).
 * Open set: when a domain is added, extend these constants and the
 * chk_vocabulary_items_domain CHECK together.
 */
export const VocabularyDomainBackendDB = "backend_db";
export const VocabularyDomainDistributed = "distributed_systems";
export const VocabularyDomainDevOpsCloud = "devops_cloud";
export const VocabularyDomainFrontendUI = "frontend_ui";
export const VocabularyDomainAIML = "ai_ml";
export type VocabularyDomain = typeof VocabularyDomainBackendDB | typeof VocabularyDomainDistributed | typeof VocabularyDomainDevOpsCloud | typeof VocabularyDomainFrontendUI | typeof VocabularyDomainAIML;

//////////
// source: vocabulary_sort.go

/**
 * VocabularySort is the API-only list sort order for the vocabulary hub.
 */
export const VocabularySortRecent = "recent";
export const VocabularySortMastery = "mastery";
export const VocabularySortAlpha = "alphabetical";
export const VocabularySortInterval = "interval";
export type VocabularySort = typeof VocabularySortRecent | typeof VocabularySortMastery | typeof VocabularySortAlpha | typeof VocabularySortInterval;

//////////
// source: vocabulary_source.go

/**
 * VocabularySource is how a term entered the user's vocabulary set
 * (user_vocabulary.source_type).
 */
export const VocabularySourceLesson = "lesson";
export const VocabularySourceConversation = "conversation";
export const VocabularySourceManual = "manual";
export type VocabularySource = typeof VocabularySourceLesson | typeof VocabularySourceConversation | typeof VocabularySourceManual;
