// Code generated by tygo. DO NOT EDIT.

//////////
// source: activity.go

/**
 * QuestionOption is one multiple-choice option; correctness never crosses.
 */
export interface QuestionOption {
  key: string;
  text: string;
}
/**
 * Question is one checkable reading/listening item (answers stay server-side).
 */
export interface Question {
  stem: string;
  instruction: string;
  options: QuestionOption[];
}
export interface ReadingPayload {
  text: string;
  questions: Question[];
}
export interface ListeningPayload {
  audioUrl: string;
  transcript: string;
  questions: Question[];
}
export interface WritingPayload {
  task: string;
  instructions: string;
  stimulus: string;
  minWords: number /* int */;
  maxWords: number /* int */;
  modelAnswer: string;
  checklist: string[];
}
export interface SpeakingItem {
  text: string;
  modelAudioUrl: string;
}
export interface SpeakingPayload {
  items: SpeakingItem[];
}
/**
 * CheckResult is the grading outcome for one question. The explanation is
 * revealed only after the learner commits an answer.
 */
export interface CheckResult {
  correct: boolean;
  correctKey: string;
  explanation: string;
}
/**
 * PhoneDetail is one mispronounced phone: expected vs heard IPA with confidence.
 */
export interface PhoneDetail {
  expected: string;
  heard: string;
  confidence: number /* float64 */;
}
/**
 * ReferencePhone is one reference word's expected IPA, in sentence order.
 * The panel renders it under every word chip, flagged or not.
 */
export interface ReferencePhone {
  word: string;
  phones: string;
}
/**
 * MispronouncedWord is one engine-flagged word: expected vs heard IPA.
 */
export interface MispronouncedWord {
  word: string;
  expected: string;
  heard: string;
  confidence: number /* float64 */;
  phones: PhoneDetail[];
}
/**
 * Prosody carries the learner's pitch and energy contours, downsampled by
 * the engine to at most 120 points each.
 */
export interface Prosody {
  f0: number /* float64 */[];
  energy: number /* float64 */[];
}
/**
 * PronunciationResult is the engine's assessment of one read-aloud attempt.
 */
export interface PronunciationResult {
  score: number /* float64 */;
  transcription: string;
  phonemeErrorRate: number /* float64 */;
  wordErrorRate: number /* float64 */;
  acousticDistance: number /* float64 */;
  errors: MispronouncedWord[];
  prosody: Prosody;
  modelCurve: number /* float64 */[];
  learnerCurve: number /* float64 */[];
  referencePhones: ReferencePhone[];
}
/**
 * Activity is one ordered lesson part. Exactly one payload pointer is set,
 * matching Type. DurationMin and SkillFocus are plain columns on the model.
 */
export interface Activity {
  id: string;
  partNumber: number /* int */;
  type: ActivityType;
  title: string;
  description: string;
  durationMin: number /* int */;
  skillFocus: string;
  reading?: ReadingPayload;
  listening?: ListeningPayload;
  writing?: WritingPayload;
  speaking?: SpeakingPayload;
}
/**
 * TaskVerdict is one checklist judgement with its evidence quote.
 */
export interface TaskVerdict {
  item: string;
  status: string;
  evidence: string;
}
/**
 * Span is one quoted problem with a minimal fix. The array it sits in is the
 * label (grammar vs phrasing).
 */
export interface Span {
  text: string;
  occurrence: number /* int */;
  correction: string;
  reason: string;
}
/**
 * TaskCompletion is section 1; counts live in ScoreSummary, never here.
 */
export interface TaskCompletion {
  verdicts: TaskVerdict[];
  answersPrompt: boolean;
  answersNote: string;
}
/**
 * ScoreSummary is the server-computed header strip.
 */
export interface ScoreSummary {
  pointsCovered: number /* int */;
  pointsTotal: number /* int */;
  score: number /* float64 */;
  wordCount: number /* int */;
  minWords: number /* int */;
  maxWords: number /* int */;
}
/**
 * AttemptSummary lets the UI render run state with zero refetch.
 */
export interface AttemptSummary {
  id: string;
  status: string;
  score?: number /* float64 */;
}
/**
 * WritingScoreResponse is the full wire response: feedback + numbers + run
 * state in one round trip. No copy of the learner paragraph anywhere.
 */
export interface WritingScoreResponse {
  summary: ScoreSummary;
  task: TaskCompletion;
  grammar: Span[];
  phrasing: Span[];
  expressions: string[];
  suggested: string;
  tip: string;
  attempt: AttemptSummary;
}

//////////
// source: lesson.go

/**
 * LessonDetails mirrors lessons.details (jsonb).
 */
export interface LessonDetails {
  estimatedDurationMin?: number /* int */;
  acousticTargetPct?: number /* int */;
  coverImageUrl: string;
  skill?: ActivityType;
}
/**
 * Section is a lesson_sections row: the titled, ordered path group.
 */
export interface Section {
  id: string;
  slug: string;
  title: string;
  description: string;
  cefrBand: CEFR;
  position: number /* int */;
}
/**
 * Lesson is a unit card and the unit detail header. Section repeats per
 * unit so a card renders without wrapper context; the hub groups on it.
 * Part totals are not stored here: the web derives them from the activity
 * list it already fetches per card (a server-side count field is a cache
 * that lies the moment the activities change).
 */
export interface Lesson {
  id: string;
  slug: string;
  title: string;
  section?: Section;
  cefrLevel: CEFR;
  description: string;
  details: LessonDetails;
}
/**
 * UnitSection mirrors models.LessonSection field for field, with Units
 * nested the same way, so one utils.MapSlice copies the whole hub.
 */
export interface UnitSection {
  id: string;
  slug: string;
  title: string;
  description: string;
  cefrBand: CEFR;
  position: number /* int */;
  units: Lesson[];
}
/**
 * LessonDetail is the GET /lessons/:id shape: header + section + ordered
 * activities. No Progress in v1 (attempts stays outside the module).
 */
export interface LessonDetail {
  id: string;
  slug: string;
  title: string;
  section?: Section;
  cefrLevel: CEFR;
  description: string;
  details: LessonDetails;
  activities: Activity[];
}
/**
 * Bookmark is one saved lesson for the caller. Go name CreatedAt matches
 * the model for copier; wire name savedAt is the product term.
 */
export interface Bookmark {
  lessonId: string;
  savedAt: string /* RFC3339 */;
}

//////////
// source: progress.go

/**
 * CheckedQuestion is one already-graded question, rehydrated for resume: the
 * learner's pick plus the reveal (correct key + explanation) the check
 * unlocked. Only ever served for the attempt owner's open run.
 */
export interface CheckedQuestion {
  index: number /* int */;
  key: string;
  correct: boolean;
  correctKey: string;
  explanation: string;
}
/**
 * AttemptProgress is the resume payload: run state plus per-activity graded
 * questions keyed by activity id. Checkable activities only — writing and
 * speaking entries carry no rehydratable answers yet and are omitted.
 */
export interface AttemptProgress {
  attempt: AttemptSummary;
  checks: { [key: string]: CheckedQuestion[]};
}
