// Code generated by tygo. DO NOT EDIT.

//////////
// source: activity.go

/**
 * QuestionOption is one multiple-choice option. Correctness is intentionally
 * not exposed: answer checking becomes a server endpoint (see spec).
 */
export interface QuestionOption {
  key: string;
  text: string;
}
/**
 * Question is one comprehension question of a reading activity.
 */
export interface Question {
  stem: string;
  instruction: string;
  options: QuestionOption[];
}
/**
 * ReadingPayload is lesson_activities.config for type=reading.
 */
export interface ReadingPayload {
  passage: string;
  questions: Question[];
}
/**
 * DictationSentence is one dictation queue item.
 */
export interface DictationSentence {
  prompt: string;
  reference: string;
  audioUrl: string;
  durationMs: number /* int */;
}
/**
 * DictationPayload is lesson_activities.config for type=dictation.
 */
export interface DictationPayload {
  sentences: DictationSentence[];
}
/**
 * WritingPayload is lesson_activities.config for type=writing.
 */
export interface WritingPayload {
  title: string;
  minWords: number /* int */;
  maxWords: number /* int */;
  contextQuestions: string[];
}
/**
 * VoicePayload is lesson_activities.config for type=voice.
 */
export interface VoicePayload {
  scenarioId: string;
}
/**
 * Activity is one ordered lesson part. Exactly one of Reading, Dictation,
 * Writing, or Voice is set, matching Type.
 */
export interface Activity {
  id: string;
  partNumber: number /* int */;
  type: ActivityType;
  title: string;
  description: string;
  durationMin: number /* int */;
  skillFocus: string;
  reading?: ReadingPayload;
  dictation?: DictationPayload;
  writing?: WritingPayload;
  voice?: VoicePayload;
}

//////////
// source: lesson.go

/**
 * Category is a lesson_categories row.
 */
export interface Category {
  id: string;
  slug: string;
  name: string;
}
/**
 * LessonDetails mirrors lessons.details (jsonb).
 */
export interface LessonDetails {
  estimatedDurationMin?: number /* int */;
  acousticTargetPct?: number /* int */;
  coverImageUrl: string;
  skill?: ActivityType;
}
/**
 * LessonProgress is the user-specific state derived from attempts and
 * bookmarks (nil when the user has no interaction with the lesson).
 */
export interface LessonProgress {
  status: LessonStatus;
  percent: number /* int */;
  partsCompleted: number /* int */;
  partsTotal: number /* int */;
  bookmarked: boolean;
  savedAt?: string /* RFC3339 */;
}
/**
 * Lesson is a lesson hub card and the lesson detail header.
 */
export interface Lesson {
  id: string;
  slug: string;
  title: string;
  category?: Category;
  cefrLevel: CEFR;
  description: string;
  details: LessonDetails;
  partCount: number /* int */;
  progress?: LessonProgress;
}
