// Code generated by tygo. DO NOT EDIT.

//////////
// source: lesson_practice.go

/**
 * ListLessonPractice filters the lesson hub (level, category, skill tab,
 * completion status). Pagination/search come from the embedded
 * common.ListParams (tstype:",extends" -> `interface ListLessonPractice extends
 * ListParams`); json tags mirror the query keys so the generated TS field
 * names match the wire.
 */
export interface ListLessonPractice extends ListParams {
  level: CEFR;
  categorySlug: string;
  skill: ActivityType;
  status: LessonStatus;
}
