// Code generated by tygo. DO NOT EDIT.

//////////
// source: lesson.go

/**
 * ListLessons filters the unit hub (level, skill tab, completion status).
 * Pagination/search come from the embedded common.ListParams
 * (tstype:",extends" -> `interface ListLessons extends ListParams`); json tags
 * mirror the query keys so the generated TS field names match the wire.
 */
export interface ListLessons extends ListParams {
  level: CEFR;
  skill: ActivityType;
  status: LessonStatus;
}
/**
 * ListActivities filters GET /lesson-activities (?lessonId= required).
 */
export interface ListActivities {
  lessonId: string;
}
/**
 * SaveBookmark is the POST /lesson-bookmarks body.
 */
export interface SaveBookmark {
  lessonId: string;
}
/**
 * CheckAnswer grades one reading/listening question. min=0, not required:
 * `required` rejects the zero value, and question 0 is valid.
 */
export interface CheckAnswer {
  attemptId: string;
  questionIndex: number /* int */;
  key: string;
}
/**
 * ScoreWriting grades one writing part into the open lesson attempt.
 */
export interface ScoreWriting {
  attemptId: string;
  text: string;
}
