// Code generated by tygo. DO NOT EDIT.

//////////
// source: activity.go

/**
 * QuestionOption is one multiple-choice option; correctness never crosses.
 */
export interface QuestionOption {
  key: string;
  text: string;
}
/**
 * Question is one checkable reading/listening item (answers stay server-side).
 */
export interface Question {
  stem: string;
  instruction: string;
  options: QuestionOption[];
}
export interface ReadingPayload {
  text: string;
  questions: Question[];
}
export interface ListeningPayload {
  audioUrl: string;
  transcript: string;
  questions: Question[];
}
export interface WritingPayload {
  task: string;
  instructions: string;
  stimulus: string;
  minWords: number /* int */;
  maxWords: number /* int */;
  modelAnswer: string;
  checklist: string[];
}
export interface SpeakingItem {
  text: string;
  modelAudioUrl: string;
}
export interface SpeakingPayload {
  items: SpeakingItem[];
}
/**
 * CheckResult is the grading outcome for one question. The explanation is
 * revealed only after the learner commits an answer.
 */
export interface CheckResult {
  correct: boolean;
  correctKey: string;
  explanation: string;
}
/**
 * PhoneDetail is one mispronounced phone: expected vs heard IPA with confidence.
 */
export interface PhoneDetail {
  expected: string;
  heard: string;
  confidence: number /* float64 */;
}
/**
 * ReferencePhone is one reference word's expected IPA, in sentence order.
 * The panel renders it under every word chip, flagged or not.
 */
export interface ReferencePhone {
  word: string;
  phones: string;
}
/**
 * MispronouncedWord is one engine-flagged word: expected vs heard IPA.
 */
export interface MispronouncedWord {
  word: string;
  expected: string;
  heard: string;
  confidence: number /* float64 */;
  phones: PhoneDetail[];
}
/**
 * Prosody carries the learner's pitch and energy contours, downsampled by
 * the engine to at most 120 points each.
 */
export interface Prosody {
  f0: number /* float64 */[];
  energy: number /* float64 */[];
}
/**
 * PronunciationResult is the engine's assessment of one read-aloud attempt.
 */
export interface PronunciationResult {
  score: number /* float64 */;
  transcription: string;
  phonemeErrorRate: number /* float64 */;
  wordErrorRate: number /* float64 */;
  acousticDistance: number /* float64 */;
  errors: MispronouncedWord[];
  prosody: Prosody;
  modelCurve: number /* float64 */[];
  learnerCurve: number /* float64 */[];
  referencePhones: ReferencePhone[];
}
/**
 * Activity is one ordered lesson part. Exactly one payload pointer is set,
 * matching Type. DurationMin and SkillFocus are plain columns on the model.
 */
export interface Activity {
  id: string;
  partNumber: number /* int */;
  type: ActivityType;
  title: string;
  description: string;
  durationMin: number /* int */;
  skillFocus: string;
  reading?: ReadingPayload;
  listening?: ListeningPayload;
  writing?: WritingPayload;
  speaking?: SpeakingPayload;
}

//////////
// source: lesson.go

/**
 * LessonDetails mirrors lessons.details (jsonb).
 */
export interface LessonDetails {
  estimatedDurationMin?: number /* int */;
  acousticTargetPct?: number /* int */;
  coverImageUrl: string;
  skill?: ActivityType;
}
/**
 * Section is a lesson_sections row: the titled, ordered path group.
 */
export interface Section {
  id: string;
  slug: string;
  title: string;
  description: string;
  cefrBand: CEFR;
  position: number /* int */;
}
/**
 * Lesson is a unit card and the unit detail header. Section repeats per
 * unit so a card renders without wrapper context; the hub groups on it.
 * Part totals are not stored here: the web derives them from the activity
 * list it already fetches per card (a server-side count field is a cache
 * that lies the moment the activities change).
 */
export interface Lesson {
  id: string;
  slug: string;
  title: string;
  section?: Section;
  cefrLevel: CEFR;
  description: string;
  details: LessonDetails;
}
/**
 * UnitSection mirrors models.LessonSection field for field, with Units
 * nested the same way, so one utils.MapSlice copies the whole hub.
 */
export interface UnitSection {
  id: string;
  slug: string;
  title: string;
  description: string;
  cefrBand: CEFR;
  position: number /* int */;
  units: Lesson[];
}
/**
 * LessonDetail is the GET /lessons/:id shape: header + section + ordered
 * activities. No Progress in v1 (attempts stays outside the module).
 */
export interface LessonDetail {
  id: string;
  slug: string;
  title: string;
  section?: Section;
  cefrLevel: CEFR;
  description: string;
  details: LessonDetails;
  activities: Activity[];
}
/**
 * Bookmark is one saved lesson for the caller. Go name CreatedAt matches
 * the model for copier; wire name savedAt is the product term.
 */
export interface Bookmark {
  lessonId: string;
  savedAt: string /* RFC3339 */;
}
