// Code generated by tygo. DO NOT EDIT.

//////////
// source: lesson.go

/**
 * ListLessons filters the unit hub (level, skill tab, completion status).
 * Pagination/search come from the embedded common.ListParams
 * (tstype:",extends" -> `interface ListLessons extends ListParams`); json tags
 * mirror the query keys so the generated TS field names match the wire.
 */
export interface ListLessons extends ListParams {
  level: CEFR;
  skill: ActivityType;
  status: LessonStatus;
}
/**
 * ListActivities filters GET /lesson-activities (?lessonId= required).
 */
export interface ListActivities {
  lessonId: string;
}
/**
 * SaveBookmark is the POST /lesson-bookmarks body.
 */
export interface SaveBookmark {
  lessonId: string;
}
