// Code generated by tygo. DO NOT EDIT.

//////////
// source: persona.go

/**
 * Persona is an AI partner row (name feeds turn display names).
 */
export interface Persona {
  id: string;
  name: string;
  roleTitle: string;
  personality: string;
  style: string;
  objective: string;
  defaultCefr?: CEFR;
}

//////////
// source: scenario.go

/**
 * Scenario is one roleplay practice card. Field names mirror the model so
 * utils.Map copies everything automatically — including the nested Details
 * blob, whose struct shape matches models.ScenarioDetail field for field.
 * A non-null Persona marks curated scenarios.
 */
export interface Scenario {
  id: string;
  topic?: ScenarioTopic;
  persona?: Persona;
  title: string;
  objective: string;
  cefrLevel: ScenarioDifficulty;
  maxDuration: number /* int */;
  details: ScenarioDetail;
}
/**
 * ScenarioDetail mirrors models.ScenarioDetail field for field so copier
 * maps the blob without manual lines. Pure scenario substance (context,
 * opening line, terms); nothing coach-generic lives here.
 */
export interface ScenarioDetail {
  role?: string;
  interlocutorRole?: string;
  goalFormat?: string;
  context?: string[];
  opening?: DetailOpening;
  vocab?: string[];
}
/**
 * DetailOpening is the partner's first line on the detail page.
 */
export interface DetailOpening {
  label: string;
  text: string;
}
/**
 * ScenarioTopic mirrors models.ScenarioTopic: the banner taxonomy plus the
 * top-k scenarios the repository attached. utils.MapSlice copies the whole
 * banner — nested scenarios, their personas, and their detail documents — in
 * one call, because every nested type mirrors its model by field name.
 */
export interface ScenarioTopic {
  id: string;
  slug: string;
  name: string;
  shortName: string;
  position: number /* int */;
  scenarios: Scenario[];
}
