// Code generated by tygo. DO NOT EDIT.

//////////
// source: persona.go

/**
 * Persona is an AI partner row (name feeds turn display names).
 */
export interface Persona {
  id: string;
  name: string;
  roleTitle: string;
  personality: string;
  style: string;
  objective: string;
  defaultCefr?: CEFR;
}

//////////
// source: scenario.go

/**
 * Scenario is one roleplay practice card. Durations come from
 * scenarios.details (jsonb); a non-null Persona marks curated scenarios
 * (custom ones show only the "Partner" label).
 */
export interface Scenario {
  id: string;
  topicId: string;
  persona?: Persona;
  title: string;
  objective: string;
  cefrLevel: ScenarioDifficulty;
  durationMin: number /* int */;
  durationMax: number /* int */;
  isCustom: boolean;
}
/**
 * ScenarioTopic is one persona-picker banner with its scenarios.
 */
export interface ScenarioTopic {
  id: string;
  slug: string;
  name: string;
  position: number /* int */;
  scenarios: Scenario[];
}
