// Code generated by tygo. DO NOT EDIT.

//////////
// source: profile.go

/**
 * Preferences mirrors user_profiles.preferences (jsonb). The CEFR range is
 * derived from Level in Go, not stored.
 */
export interface Preferences {
  level: Level;
  primaryGoal: Goal;
  dailyCommitmentMin: number /* int */;
  topics: InterestTopic[];
}
/**
 * Profile is the onboarding profile of the authenticated user.
 */
export interface Profile {
  id: string;
  userId: string;
  preferences: Preferences;
  onboardingCompletedAt?: string /* RFC3339 */;
  createdAt: string /* RFC3339 */;
  updatedAt: string /* RFC3339 */;
}
