// Code generated by tygo. DO NOT EDIT.

//////////
// source: profile.go

/**
 * UpdateProfile carries the onboarding/profile preference fields
 * (all optional; partial update).
 */
export interface UpdateProfile {
  level: Level;
  primaryGoal: Goal;
  dailyCommitmentMin: number /* int */;
  topics: InterestTopic[];
}
