// Code generated by tygo. DO NOT EDIT.

//////////
// source: pagination.go

/**
 * ListScenarios pages the scenario catalog. Scope selects built-in rows
 * (user_id IS NULL) or the caller's own custom rows.
 */
export interface ListScenarios extends ListParams {
  topicId?: string;
  scope: string;
}
