// Code generated by tygo. DO NOT EDIT.

//////////
// source: pagination.go

/**
 * ListScenarios pages the scenario catalog, optionally topic-filtered.
 */
export interface ListScenarios extends ListParams {
  topicId?: string;
}

//////////
// source: persona_pagination.go

/**
 * ListPersonas pages the persona catalog.
 */
export interface ListPersonas extends ListParams {
}
