// Code generated by tygo. DO NOT EDIT.

//////////
// source: video_category.go

export interface CreateVideoCategory {
  slug: string;
  name: string;
}
export interface UpdateVideoCategory {
  slug: string;
  name: string;
}

//////////
// source: video_exercise.go

export interface CreateVideoExercise {
  categoryId?: string;
  title: string;
  description: string;
  videoUrl: string;
  youtubeUrl: string;
  thumbnailUrl: string;
  cefrLevel?: CEFR;
  duration: number /* float64 */;
}
export interface UpdateVideoExercise {
  categoryId?: string;
  title: string;
  description: string;
  videoUrl: string;
  youtubeUrl: string;
  thumbnailUrl: string;
  cefrLevel?: CEFR;
  duration: number /* float64 */;
}

//////////
// source: video_transcript.go

export interface CreateVideoTranscript {
  videoExerciseId: string;
  sequence: number /* int */;
  content: string;
  phonetic: string;
  vietnamese: string;
  startTimestamp: number /* float64 */;
  endTimestamp: number /* float64 */;
}
export interface UpdateVideoTranscript {
  sequence?: number /* int */;
  content?: string;
  phonetic?: string;
  vietnamese?: string;
  startTimestamp?: number /* float64 */;
  endTimestamp?: number /* float64 */;
}
