// Code generated by tygo. DO NOT EDIT.

//////////
// source: video_category.go

export interface VideoCategoryResponse {
  id: string;
  slug: string;
  name: string;
  createdAt: string /* RFC3339 */;
  updatedAt: string /* RFC3339 */;
}

//////////
// source: video_exercise.go

export interface VideoExerciseResponse {
  id: string;
  categoryId?: string;
  title: string;
  description: string;
  videoUrl: string;
  thumbnailUrl: string;
  cefrLevel?: CEFR;
  duration: number /* float64 */;
  createdAt: string /* RFC3339 */;
  updatedAt: string /* RFC3339 */;
  category?: VideoCategoryResponse;
  transcripts?: VideoTranscriptResponse[];
}

//////////
// source: video_transcript.go

export interface VideoTranscriptResponse {
  id: string;
  videoExerciseId: string;
  sequence: number /* int */;
  content: string;
  phonetic: string;
  vietnamese: string;
  startTimestamp: number /* float64 */;
  endTimestamp: number /* float64 */;
  createdAt: string /* RFC3339 */;
  updatedAt: string /* RFC3339 */;
}
