// Code generated by tygo. DO NOT EDIT.

//////////
// source: vocabulary.go

/**
 * VocabularyContext is one labeled usage quote ("Webhook delivery...").
 */
export interface VocabularyContext {
  label: string;
  quote: string;
}
/**
 * Collocation is a fixed phrase with its pattern ("adv + adj").
 */
export interface Collocation {
  phrase: string;
  pattern: string;
  example: string;
}
/**
 * WordForm is one morphology entry (noun/adverb/antonym forms).
 */
export interface WordForm {
  formType: string;
  forms: string[];
}
/**
 * VocabularyDetails mirrors vocabulary_items.details (jsonb): everything the
 * word-detail screen renders beyond the core columns.
 */
export interface VocabularyDetails {
  audioUs: string;
  audioUk: string;
  syllables: string;
  stressTip: string;
  commonSlip: string;
  longDefinition: string;
  etymology: string;
  contexts: VocabularyContext[];
  collocations: Collocation[];
  wordForms: WordForm[];
}
/**
 * UserVocabularyState is the user's row over a shared item.
 */
export interface UserVocabularyState {
  sourceType: VocabularySource;
  sourceId?: string;
  note?: string;
  mastered: boolean;
  srsDueAt?: string /* RFC3339 */;
  createdAt: string /* RFC3339 */;
}
/**
 * VocabularyItem is a vocabulary hub card / word detail payload.
 */
export interface VocabularyItem {
  id: string;
  term: string;
  ipa: string;
  partOfSpeech: string;
  cefr: CEFR;
  domain?: VocabularyDomain;
  definition: string;
  details?: VocabularyDetails;
  userState?: UserVocabularyState;
}
/**
 * VocabularyStats aggregates the hub's four stat cards (computed by
 * services from user_vocabulary).
 */
export interface VocabularyStats {
  totalSaved: number /* int */;
  mastered: number /* int */;
  needsReview: number /* int */;
  customAdditions: number /* int */;
  dueToday: number /* int */;
  retentionPct: number /* int */;
}
