// Code generated by tygo. DO NOT EDIT.

//////////
// source: vocabulary.go

/**
 * ListVocabulary sorts and filters the vocabulary studio. Pagination/search
 * come from the embedded common.ListParams (tstype:",extends" -> `interface
 * ListVocabulary extends ListParams`); json tags mirror the query keys so
 * the generated TS field names match the wire.
 */
export interface ListVocabulary extends ListParams {
  sort: VocabularySort;
  domain: VocabularyDomain;
  cefr: CEFR;
  source: VocabularySource;
}
