import type {
	Persona,
	Scenario,
	ScenarioTopic,
	VideoCategoryResponse,
	VideoExerciseResponse,
	VideoTranscriptResponse,
	VocabularyCategoryResponse,
	VocabularyDeckDetail,
} from "@engflex/contracts";
import type { AdminUser } from "./types";

/** Mock "now" for relative admin copy; matches the other features' fixtures. */
export const ADMIN_TODAY = "2026-09-23T09:00:00Z";

const STAMP = "2026-09-01T08:00:00Z";

export const ADMIN_USERS: AdminUser[] = [
	{
		id: "user_2q8Lk1aAdmin",
		name: "Linh Tran",
		email: "linh.tran@engflex.dev",
		role: "admin",
		status: "active",
		level: "advanced",
		joinedAt: "2026-05-02T08:00:00Z",
		lastActiveAt: "2026-09-23T07:40:00Z",
	},
	{
		id: "user_2q8Lk2bMinh",
		name: "Minh Nguyen",
		email: "minh.nguyen@example.com",
		role: "user",
		status: "active",
		level: "intermediate",
		joinedAt: "2026-06-11T10:20:00Z",
		lastActiveAt: "2026-09-22T21:05:00Z",
	},
	{
		id: "user_2q8Lk3cHoa",
		name: "Hoa Pham",
		email: "hoa.pham@example.com",
		role: "user",
		status: "active",
		level: "beginner",
		joinedAt: "2026-07-03T14:00:00Z",
		lastActiveAt: "2026-09-21T12:30:00Z",
	},
	{
		id: "user_2q8Lk4dQuan",
		name: "Quan Le",
		email: "quan.le@example.com",
		role: "user",
		status: "suspended",
		level: "intermediate",
		joinedAt: "2026-07-19T09:45:00Z",
		lastActiveAt: "2026-08-30T18:10:00Z",
	},
	{
		id: "user_2q8Lk5eAnh",
		name: "Anh Vo",
		email: "anh.vo@example.com",
		role: "user",
		status: "active",
		level: "advanced",
		joinedAt: "2026-08-05T07:15:00Z",
		lastActiveAt: "2026-09-23T06:55:00Z",
	},
	{
		id: "user_2q8Lk6fBao",
		name: "Bao Dang",
		email: "bao.dang@example.com",
		role: "user",
		status: "active",
		level: "beginner",
		joinedAt: "2026-09-10T16:40:00Z",
		lastActiveAt: "2026-09-20T19:20:00Z",
	},
	{
		id: "user_2q8Lk7gThu",
		name: "Thu Hoang",
		email: "thu.hoang@example.com",
		role: "admin",
		status: "active",
		level: "advanced",
		joinedAt: "2026-05-20T11:00:00Z",
		lastActiveAt: "2026-09-19T09:00:00Z",
	},
	{
		id: "user_2q8Lk8hKhoa",
		name: "Khoa Bui",
		email: "khoa.bui@example.com",
		role: "user",
		status: "active",
		level: "intermediate",
		joinedAt: "2026-09-18T13:25:00Z",
		lastActiveAt: "2026-09-22T08:45:00Z",
	},
];

export const ADMIN_VOCABULARY_CATEGORIES: VocabularyCategoryResponse[] = [
	{
		id: "vcat-1",
		name: "Backend & databases",
		description: "Storage, indexing and API design vocabulary.",
		createdAt: STAMP,
		updatedAt: STAMP,
	},
	{
		id: "vcat-2",
		name: "Cloud & DevOps",
		description: "Deployment, observability and incident language.",
		createdAt: STAMP,
		updatedAt: STAMP,
	},
	{
		id: "vcat-3",
		name: "Meetings & reviews",
		description: "Phrases for stand-ups, design reviews and retros.",
		createdAt: STAMP,
		updatedAt: STAMP,
	},
];

export const ADMIN_VOCABULARY_DECKS: VocabularyDeckDetail[] = [
	{
		id: "deck-1",
		categoryId: "vcat-1",
		name: "Database essentials",
		description: "Core terms for schema design and query tuning.",
		thumbnailUrl: "",
		level: "B2",
		isDefault: true,
		createdAt: STAMP,
		updatedAt: STAMP,
	},
	{
		id: "deck-2",
		categoryId: "vcat-2",
		name: "Incident response",
		description: "Talk through outages, postmortems and rollbacks.",
		thumbnailUrl: "",
		level: "C1",
		isDefault: true,
		createdAt: STAMP,
		updatedAt: STAMP,
	},
	{
		id: "deck-3",
		categoryId: "vcat-3",
		name: "Design review phrases",
		description: "Push back, propose trade-offs and agree on next steps.",
		thumbnailUrl: "",
		level: "B2",
		isDefault: false,
		createdAt: STAMP,
		updatedAt: STAMP,
	},
	{
		id: "deck-4",
		name: "Daily stand-up",
		description: "Short, clear updates on progress and blockers.",
		thumbnailUrl: "",
		level: "B1",
		isDefault: false,
		createdAt: STAMP,
		updatedAt: STAMP,
	},
];

export const ADMIN_VIDEO_CATEGORIES: VideoCategoryResponse[] = [
	{
		id: "vidcat-1",
		slug: "tech-talks",
		name: "Tech talks",
		createdAt: STAMP,
		updatedAt: STAMP,
	},
	{
		id: "vidcat-2",
		slug: "interviews",
		name: "Interviews",
		createdAt: STAMP,
		updatedAt: STAMP,
	},
	{
		id: "vidcat-3",
		slug: "product-demos",
		name: "Product demos",
		createdAt: STAMP,
		updatedAt: STAMP,
	},
];

export const ADMIN_VIDEO_EXERCISES: VideoExerciseResponse[] = [
	{
		id: "video-1",
		categoryId: "vidcat-1",
		title: "Scaling Postgres to millions of users",
		description: "A conference talk on partitioning and read replicas.",
		videoUrl: "https://cdn.example.com/videos/scaling-postgres.mp4",
		thumbnailUrl: "",
		cefrLevel: "C1",
		duration: 1260,
		createdAt: STAMP,
		updatedAt: STAMP,
	},
	{
		id: "video-2",
		categoryId: "vidcat-2",
		title: "Behavioral interview: conflict on a team",
		description: "A mock interview answering with the STAR method.",
		videoUrl: "https://cdn.example.com/videos/star-interview.mp4",
		thumbnailUrl: "",
		cefrLevel: "B2",
		duration: 540,
		createdAt: STAMP,
		updatedAt: STAMP,
	},
	{
		id: "video-3",
		categoryId: "vidcat-3",
		title: "Demoing a feature flag dashboard",
		description: "Walking stakeholders through a rollout plan.",
		videoUrl: "https://cdn.example.com/videos/flag-demo.mp4",
		thumbnailUrl: "",
		cefrLevel: "B1",
		duration: 395,
		createdAt: STAMP,
		updatedAt: STAMP,
	},
];

export const ADMIN_VIDEO_TRANSCRIPTS: VideoTranscriptResponse[] = [
	{
		id: "seg-1",
		videoExerciseId: "video-1",
		sequence: 1,
		content: "Today we'll look at how we scaled our primary database.",
		phonetic: "",
		vietnamese:
			"Hôm nay chúng ta sẽ xem cách chúng tôi mở rộng cơ sở dữ liệu chính.",
		startTimestamp: 0,
		endTimestamp: 4.2,
		createdAt: STAMP,
		updatedAt: STAMP,
	},
	{
		id: "seg-2",
		videoExerciseId: "video-1",
		sequence: 2,
		content: "The first bottleneck was write contention on a single table.",
		phonetic: "",
		vietnamese: "Điểm nghẽn đầu tiên là tranh chấp ghi trên một bảng duy nhất.",
		startTimestamp: 4.2,
		endTimestamp: 9.1,
		createdAt: STAMP,
		updatedAt: STAMP,
	},
	{
		id: "seg-3",
		videoExerciseId: "video-2",
		sequence: 1,
		content: "Tell me about a time you disagreed with a teammate.",
		phonetic: "",
		vietnamese:
			"Hãy kể về một lần bạn bất đồng ý kiến với đồng nghiệp trong nhóm.",
		startTimestamp: 0,
		endTimestamp: 3.5,
		createdAt: STAMP,
		updatedAt: STAMP,
	},
	{
		id: "seg-4",
		videoExerciseId: "video-3",
		sequence: 1,
		content: "Let me show you how a rollout is staged by region.",
		phonetic: "",
		vietnamese: "Để tôi cho bạn xem cách triển khai được chia theo khu vực.",
		startTimestamp: 0,
		endTimestamp: 3.8,
		createdAt: STAMP,
		updatedAt: STAMP,
	},
];

export const ADMIN_PERSONAS: Persona[] = [
	{
		id: "persona-1",
		name: "Sarah Chen",
		roleTitle: "Engineering manager",
		personality: "Direct, supportive, time-conscious",
		style: "Asks for concrete numbers and owners",
		objective: "Get a clear status and risk assessment",
		gender: "female",
		defaultCefr: "B2",
	},
	{
		id: "persona-2",
		name: "David Miller",
		roleTitle: "VP of Product",
		personality: "Skeptical, business-focused",
		style: "Pushes back on scope and timelines",
		objective: "Protect the launch date",
		gender: "male",
		defaultCefr: "C1",
	},
	{
		id: "persona-3",
		name: "Priya Kapoor",
		roleTitle: "Senior recruiter",
		personality: "Warm, structured",
		style: "Follows up with behavioral questions",
		objective: "Assess communication and teamwork",
		gender: "female",
		defaultCefr: "B1",
	},
];

const topic = (
	id: string,
	slug: string,
	name: string,
	position: number,
): ScenarioTopic => ({
	id,
	slug,
	name,
	shortName: name,
	position,
	scenarios: [],
});

export const ADMIN_SCENARIO_TOPICS: ScenarioTopic[] = [
	topic("topic-1", "meetings", "Meetings", 1),
	topic("topic-2", "interviews", "Interviews", 2),
	topic("topic-3", "stakeholders", "Stakeholders", 3),
];

export const ADMIN_SCENARIOS: Scenario[] = [
	{
		id: "scenario-1",
		topic: ADMIN_SCENARIO_TOPICS[0],
		persona: ADMIN_PERSONAS[0],
		title: "Report a slipped deadline",
		objective: "Explain the delay, its cause and a recovery plan.",
		cefrLevel: "B2",
		maxDuration: 300,
		details: {},
	},
	{
		id: "scenario-2",
		topic: ADMIN_SCENARIO_TOPICS[2],
		persona: ADMIN_PERSONAS[1],
		title: "Negotiate MVP scope",
		objective: "Trade features for a realistic launch date.",
		cefrLevel: "C1",
		maxDuration: 420,
		details: {},
	},
	{
		id: "scenario-3",
		topic: ADMIN_SCENARIO_TOPICS[1],
		persona: ADMIN_PERSONAS[2],
		title: "Behavioral screening call",
		objective: "Answer two STAR questions with clear structure.",
		cefrLevel: "B1+",
		maxDuration: 360,
		details: {},
	},
];
