// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"engflex-api/internal/modules/conversations/dtos/responses"

	mock "github.com/stretchr/testify/mock"
)

// NewMockPronounceEngine creates a new instance of MockPronounceEngine. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPronounceEngine(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPronounceEngine {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockPronounceEngine{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockPronounceEngine is an autogenerated mock type for the PronounceEngine type
type MockPronounceEngine struct {
	mock.Mock
}

type MockPronounceEngine_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPronounceEngine) EXPECT() *MockPronounceEngine_Expecter {
	return &MockPronounceEngine_Expecter{mock: &_m.Mock}
}

// Pronounce provides a mock function for the type MockPronounceEngine
func (_mock *MockPronounceEngine) Pronounce(ctx context.Context, expectedText string, lang string, audio []byte, mime string) (*responses.PronounceResult, error) {
	ret := _mock.Called(ctx, expectedText, lang, audio, mime)

	if len(ret) == 0 {
		panic("no return value specified for Pronounce")
	}

	var r0 *responses.PronounceResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, []byte, string) (*responses.PronounceResult, error)); ok {
		return returnFunc(ctx, expectedText, lang, audio, mime)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, []byte, string) *responses.PronounceResult); ok {
		r0 = returnFunc(ctx, expectedText, lang, audio, mime)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*responses.PronounceResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, []byte, string) error); ok {
		r1 = returnFunc(ctx, expectedText, lang, audio, mime)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPronounceEngine_Pronounce_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Pronounce'
type MockPronounceEngine_Pronounce_Call struct {
	*mock.Call
}

// Pronounce is a helper method to define mock.On call
//   - ctx context.Context
//   - expectedText string
//   - lang string
//   - audio []byte
//   - mime string
func (_e *MockPronounceEngine_Expecter) Pronounce(ctx any, expectedText any, lang any, audio any, mime any) *MockPronounceEngine_Pronounce_Call {
	return &MockPronounceEngine_Pronounce_Call{Call: _e.mock.On("Pronounce", ctx, expectedText, lang, audio, mime)}
}

func (_c *MockPronounceEngine_Pronounce_Call) Run(run func(ctx context.Context, expectedText string, lang string, audio []byte, mime string)) *MockPronounceEngine_Pronounce_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 []byte
		if args[3] != nil {
			arg3 = args[3].([]byte)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockPronounceEngine_Pronounce_Call) Return(pronounceResult *responses.PronounceResult, err error) *MockPronounceEngine_Pronounce_Call {
	_c.Call.Return(pronounceResult, err)
	return _c
}

func (_c *MockPronounceEngine_Pronounce_Call) RunAndReturn(run func(ctx context.Context, expectedText string, lang string, audio []byte, mime string) (*responses.PronounceResult, error)) *MockPronounceEngine_Pronounce_Call {
	_c.Call.Return(run)
	return _c
}
