// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"engflex-api/internal/modules/conversations/dtos/responses"
	"engflex-api/internal/voice"

	mock "github.com/stretchr/testify/mock"
)

// NewMockVoiceClient creates a new instance of MockVoiceClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockVoiceClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockVoiceClient {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockVoiceClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockVoiceClient is an autogenerated mock type for the VoiceClient type
type MockVoiceClient struct {
	mock.Mock
}

type MockVoiceClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockVoiceClient) EXPECT() *MockVoiceClient_Expecter {
	return &MockVoiceClient_Expecter{mock: &_m.Mock}
}

// AnalyzeTurn provides a mock function for the type MockVoiceClient
func (_mock *MockVoiceClient) AnalyzeTurn(ctx context.Context, req voice.AnalyzeTurnRequest) (*voice.AnalyzeTurnResponse, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for AnalyzeTurn")
	}

	var r0 *voice.AnalyzeTurnResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, voice.AnalyzeTurnRequest) (*voice.AnalyzeTurnResponse, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, voice.AnalyzeTurnRequest) *voice.AnalyzeTurnResponse); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*voice.AnalyzeTurnResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, voice.AnalyzeTurnRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockVoiceClient_AnalyzeTurn_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AnalyzeTurn'
type MockVoiceClient_AnalyzeTurn_Call struct {
	*mock.Call
}

// AnalyzeTurn is a helper method to define mock.On call
//   - ctx context.Context
//   - req voice.AnalyzeTurnRequest
func (_e *MockVoiceClient_Expecter) AnalyzeTurn(ctx any, req any) *MockVoiceClient_AnalyzeTurn_Call {
	return &MockVoiceClient_AnalyzeTurn_Call{Call: _e.mock.On("AnalyzeTurn", ctx, req)}
}

func (_c *MockVoiceClient_AnalyzeTurn_Call) Run(run func(ctx context.Context, req voice.AnalyzeTurnRequest)) *MockVoiceClient_AnalyzeTurn_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 voice.AnalyzeTurnRequest
		if args[1] != nil {
			arg1 = args[1].(voice.AnalyzeTurnRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockVoiceClient_AnalyzeTurn_Call) Return(analyzeTurnResponse *voice.AnalyzeTurnResponse, err error) *MockVoiceClient_AnalyzeTurn_Call {
	_c.Call.Return(analyzeTurnResponse, err)
	return _c
}

func (_c *MockVoiceClient_AnalyzeTurn_Call) RunAndReturn(run func(ctx context.Context, req voice.AnalyzeTurnRequest) (*voice.AnalyzeTurnResponse, error)) *MockVoiceClient_AnalyzeTurn_Call {
	_c.Call.Return(run)
	return _c
}

// Offer provides a mock function for the type MockVoiceClient
func (_mock *MockVoiceClient) Offer(ctx context.Context, engineSessionID string, method string, body []byte) ([]byte, int, error) {
	ret := _mock.Called(ctx, engineSessionID, method, body)

	if len(ret) == 0 {
		panic("no return value specified for Offer")
	}

	var r0 []byte
	var r1 int
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, []byte) ([]byte, int, error)); ok {
		return returnFunc(ctx, engineSessionID, method, body)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, []byte) []byte); ok {
		r0 = returnFunc(ctx, engineSessionID, method, body)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, []byte) int); ok {
		r1 = returnFunc(ctx, engineSessionID, method, body)
	} else {
		r1 = ret.Get(1).(int)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string, string, []byte) error); ok {
		r2 = returnFunc(ctx, engineSessionID, method, body)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockVoiceClient_Offer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Offer'
type MockVoiceClient_Offer_Call struct {
	*mock.Call
}

// Offer is a helper method to define mock.On call
//   - ctx context.Context
//   - engineSessionID string
//   - method string
//   - body []byte
func (_e *MockVoiceClient_Expecter) Offer(ctx any, engineSessionID any, method any, body any) *MockVoiceClient_Offer_Call {
	return &MockVoiceClient_Offer_Call{Call: _e.mock.On("Offer", ctx, engineSessionID, method, body)}
}

func (_c *MockVoiceClient_Offer_Call) Run(run func(ctx context.Context, engineSessionID string, method string, body []byte)) *MockVoiceClient_Offer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 []byte
		if args[3] != nil {
			arg3 = args[3].([]byte)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockVoiceClient_Offer_Call) Return(bytes []byte, n int, err error) *MockVoiceClient_Offer_Call {
	_c.Call.Return(bytes, n, err)
	return _c
}

func (_c *MockVoiceClient_Offer_Call) RunAndReturn(run func(ctx context.Context, engineSessionID string, method string, body []byte) ([]byte, int, error)) *MockVoiceClient_Offer_Call {
	_c.Call.Return(run)
	return _c
}

// Start provides a mock function for the type MockVoiceClient
func (_mock *MockVoiceClient) Start(ctx context.Context, req voice.StartRequest) (*voice.StartResponse, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Start")
	}

	var r0 *voice.StartResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, voice.StartRequest) (*voice.StartResponse, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, voice.StartRequest) *voice.StartResponse); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*voice.StartResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, voice.StartRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockVoiceClient_Start_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Start'
type MockVoiceClient_Start_Call struct {
	*mock.Call
}

// Start is a helper method to define mock.On call
//   - ctx context.Context
//   - req voice.StartRequest
func (_e *MockVoiceClient_Expecter) Start(ctx any, req any) *MockVoiceClient_Start_Call {
	return &MockVoiceClient_Start_Call{Call: _e.mock.On("Start", ctx, req)}
}

func (_c *MockVoiceClient_Start_Call) Run(run func(ctx context.Context, req voice.StartRequest)) *MockVoiceClient_Start_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 voice.StartRequest
		if args[1] != nil {
			arg1 = args[1].(voice.StartRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockVoiceClient_Start_Call) Return(startResponse *voice.StartResponse, err error) *MockVoiceClient_Start_Call {
	_c.Call.Return(startResponse, err)
	return _c
}

func (_c *MockVoiceClient_Start_Call) RunAndReturn(run func(ctx context.Context, req voice.StartRequest) (*voice.StartResponse, error)) *MockVoiceClient_Start_Call {
	_c.Call.Return(run)
	return _c
}

// Transcribe provides a mock function for the type MockVoiceClient
func (_mock *MockVoiceClient) Transcribe(ctx context.Context, conversationID string, audio []byte, mime string) (*responses.TranscribeResult, error) {
	ret := _mock.Called(ctx, conversationID, audio, mime)

	if len(ret) == 0 {
		panic("no return value specified for Transcribe")
	}

	var r0 *responses.TranscribeResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []byte, string) (*responses.TranscribeResult, error)); ok {
		return returnFunc(ctx, conversationID, audio, mime)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []byte, string) *responses.TranscribeResult); ok {
		r0 = returnFunc(ctx, conversationID, audio, mime)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*responses.TranscribeResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, []byte, string) error); ok {
		r1 = returnFunc(ctx, conversationID, audio, mime)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockVoiceClient_Transcribe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Transcribe'
type MockVoiceClient_Transcribe_Call struct {
	*mock.Call
}

// Transcribe is a helper method to define mock.On call
//   - ctx context.Context
//   - conversationID string
//   - audio []byte
//   - mime string
func (_e *MockVoiceClient_Expecter) Transcribe(ctx any, conversationID any, audio any, mime any) *MockVoiceClient_Transcribe_Call {
	return &MockVoiceClient_Transcribe_Call{Call: _e.mock.On("Transcribe", ctx, conversationID, audio, mime)}
}

func (_c *MockVoiceClient_Transcribe_Call) Run(run func(ctx context.Context, conversationID string, audio []byte, mime string)) *MockVoiceClient_Transcribe_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []byte
		if args[2] != nil {
			arg2 = args[2].([]byte)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockVoiceClient_Transcribe_Call) Return(transcribeResult *responses.TranscribeResult, err error) *MockVoiceClient_Transcribe_Call {
	_c.Call.Return(transcribeResult, err)
	return _c
}

func (_c *MockVoiceClient_Transcribe_Call) RunAndReturn(run func(ctx context.Context, conversationID string, audio []byte, mime string) (*responses.TranscribeResult, error)) *MockVoiceClient_Transcribe_Call {
	_c.Call.Return(run)
	return _c
}

// Transcript provides a mock function for the type MockVoiceClient
func (_mock *MockVoiceClient) Transcript(ctx context.Context, conversationID string, action string, text string) (*responses.TranscriptResult, error) {
	ret := _mock.Called(ctx, conversationID, action, text)

	if len(ret) == 0 {
		panic("no return value specified for Transcript")
	}

	var r0 *responses.TranscriptResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) (*responses.TranscriptResult, error)); ok {
		return returnFunc(ctx, conversationID, action, text)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) *responses.TranscriptResult); ok {
		r0 = returnFunc(ctx, conversationID, action, text)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*responses.TranscriptResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = returnFunc(ctx, conversationID, action, text)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockVoiceClient_Transcript_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Transcript'
type MockVoiceClient_Transcript_Call struct {
	*mock.Call
}

// Transcript is a helper method to define mock.On call
//   - ctx context.Context
//   - conversationID string
//   - action string
//   - text string
func (_e *MockVoiceClient_Expecter) Transcript(ctx any, conversationID any, action any, text any) *MockVoiceClient_Transcript_Call {
	return &MockVoiceClient_Transcript_Call{Call: _e.mock.On("Transcript", ctx, conversationID, action, text)}
}

func (_c *MockVoiceClient_Transcript_Call) Run(run func(ctx context.Context, conversationID string, action string, text string)) *MockVoiceClient_Transcript_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockVoiceClient_Transcript_Call) Return(transcriptResult *responses.TranscriptResult, err error) *MockVoiceClient_Transcript_Call {
	_c.Call.Return(transcriptResult, err)
	return _c
}

func (_c *MockVoiceClient_Transcript_Call) RunAndReturn(run func(ctx context.Context, conversationID string, action string, text string) (*responses.TranscriptResult, error)) *MockVoiceClient_Transcript_Call {
	_c.Call.Return(run)
	return _c
}
